### ISSUE TITLE
Delete single message 

### ISSUE THREAD

**Issue by KrzysztofMadejski** [Rhymen/go-whatsapp#100]
Mentioned also in #45 .

It is possible from WhatsApp web, so should be possible to implement here.

Documentation should include information when the user has the right to delete the message: 
- [ ] should it be group creator to delete any message
- [ ] should it be group admin to delete any message
- [ ] can it delete its own messages even if not admin/creator

**Comment by raedok** [comment]
I am also interested in this. I have tried several structures based off of the one in the Read function and based on the message provided by WhatsApp when I do the action from the phone but I cannot figure it out.
If anyone could at least provide a hint I would be grateful.

**Comment by tulir** [comment]
Needed this for my program so I figured out how to send and receive deletions. Generic code, links are to the code in my program that I've actually tested (in case the code below has mistakes).

Delete single own message ([original](https://github.com/tulir/mautrix-whatsapp/blob/master/portal.go#L959-L992)):
```go
import "github.com/Rhymen/go-whatsapp"
import "github.com/Rhymen/go-whatsapp/binary/proto"

...

messageToRevoke := "MESSAGEID"
chatJid := "123@s.whatsapp.net"
// or
chatJid := "123-456@g.us"

// Some variables to get their pointers later
ts := time.Now().Unix()
status := proto.WebMessageInfo_PENDING
protoMsgType := proto.ProtocolMessage_REVOKE
fromMe := true
// Make ID of the revocation event (unrelated to the ID to be revoked)
b := make([]byte, 10)
rand.Read(b)
revocationId := strings.ToUpper(hex.EncodeToString(b))

revocation := &proto.WebMessageInfo{
	Key: &proto.MessageKey{
		FromMe:    &fromMe,
		Id:        &revocationId,
		RemoteJid: &chatJid,
	},
	MessageTimestamp: &ts,
	Message: &proto.Message{
		ProtocolMessage: &proto.ProtocolMessage{
			Type: &protoMsgType,
			Key: &proto.MessageKey{
				FromMe:    &fromMe,
				Id:        &messageToRevoke,
				RemoteJid: &chatJid,
			},
		},
	},
	Status: &status,
}
_, err := conn.Send(revocation)
fmt.Println(err)
```

Handle deletions ([original](https://github.com/tulir/mautrix-whatsapp/blob/master/whatsapp-ext/protomessage.go#L36-L54)):
```go
// HandleRawMessage is called by go-whatsapp
func (handler *YourEventHandler) HandleRawMessage(message *proto.WebMessageInfo) {
	protoMsg := message.GetMessage().GetProtocolMessage()
	if protoMsg.GetType() == proto.ProtocolMessage_REVOKE {
		key := protoMsg.GetKey()
		// Handle deletion
	}
}
```

**Comment by antonforwork** [comment]
works thanks.

**Comment by alejandroguille** [comment]
Some news ?

**Comment by abnt713** [comment]
I think @tulir code works pretty well. I was thinking about exposing this functionality through the Conn object - creating a pull request. Is there any other variable or side effect regarding this functionality? (unexpected app behavior, right protocol message, unstable response or similar)?

**Comment by tguimmaraess** [comment]
> Needed this for my program so I figured out how to send and receive deletions. Generic code below, links are to the code in my program that I've actually tested (in case the code below has mistakes).
> 
> Delete single own message ([original](https://github.com/tulir/mautrix-whatsapp/blob/master/portal.go#L959-L992)):
> 
> ```go
> import "github.com/Rhymen/go-whatsapp"
> import "github.com/Rhymen/go-whatsapp/binary/proto"
> 
> ...
> 
> messageToRevoke := "MESSAGEID"
> chatJid := "123@s.whatsapp.net"
> // or
> chatJid := "123-456@g.us"
> 
> // Some variables to get their pointers later
> ts := time.Now().Unix()
> status := proto.WebMessageInfo_PENDING
> protoMsgType := proto.ProtocolMessage_REVOKE
> // I think you can only delete your own messages anyway
> fromMe := true
> // Make ID of the revocation event (unrelated to the ID to be revoked)
> b := make([]byte, 10)
> rand.Read(b)
> revocationId := strings.ToUpper(hex.EncodeToString(b))
> 
> revocation := &proto.WebMessageInfo{
> 	Key: &proto.MessageKey{
> 		FromMe:    &fromMe,
> 		Id:        &revocationId,
> 		RemoteJid: &chatJid,
> 	},
> 	MessageTimestamp: &ts,
> 	Message: &proto.Message{
> 		ProtocolMessage: &proto.ProtocolMessage{
> 			Type: &protoMsgType,
> 			Key: &proto.MessageKey{
> 				FromMe:    &fromMe,
> 				Id:        &messageToRevoke,
> 				RemoteJid: &chatJid,
> 			},
> 		},
> 	},
> 	Status: &status,
> }
> _, err := conn.Send(revocation)
> fmt.Println(err)
> ```
> 
> Handle deletions ([original](https://github.com/tulir/mautrix-whatsapp/blob/master/whatsapp-ext/protomessage.go#L36-L54)):
> 
> ```go
> // HandleRawMessage is called by go-whatsapp
> func (handler *YourEventHandler) HandleRawMessage(message *proto.WebMessageInfo) {
> 	protoMsg := message.GetMessage().GetProtocolMessage()
> 	if protoMsg.GetType() == proto.ProtocolMessage_REVOKE {
> 		key := protoMsg.GetKey()
> 		// Handle deletion
> 	}
> }
> ```

Thank you for your example, @tulir it's working but I'm in doubt when it comes about TextMessage and Proto messages. I'm trying to use both at the same time but I can't find a way to do it. I want to get the participant id when he/she joins for example. I tried to use the two types (TextMessage and *proto.WebMessageInfo) at the same time but didn't work out. I managed to use both at the same time but `WebMessageInfo_WEB_MESSAGE_INFO_STUBTYPE`  gave me` UNKNOWN ` Could you please tell me how I can do it?

**Comment by gabstv** [comment]
Did anyone try to delete a message with the example code? I always get a send timeout and then nothing happens...

**Comment by gabstv** [comment]
nvm I figured it out in #418
