### ISSUE TITLE
https://github.com/sigalor/whatsapp-web-reveng/issues/73#issuecomment-407896679

### ISSUE THREAD

**Issue by bottookku** [Rhymen/go-whatsapp#103]
how i get it metadata in this app?

https://github.com/sigalor/whatsapp-web-reveng/issues/73#issuecomment-407896679

**Comment by SchulteMK** [comment]
You should be able to call `*Conn.GetGroupMetaData(jid string)` and receive your metadata. It returns a `<-chan string` for now. You have to retrieve the answer from that channel and unmarshal it afterwards. In the future it will probably be wrapped in its own type.

**Comment by bottookku** [comment]
@SchulteMK thanks you
