### ISSUE TITLE
may this program join in channel from link

### ISSUE THREAD

**Issue by bottookku** [Rhymen/go-whatsapp#107]
may this program join in channel from link

**Comment by SchulteMK** [comment]
It should be pretty easy to implement. I hope it is enough to call the execute the `action, invite, code` command. I am done for today, but I will test it in the next few days

Notes:
```
661.--9,,["query","invite","LrL3q23E7r53RXjxxxx"]

661.--17,,["action","invite","LrL3q23E7r53RXjxxxx"]

661.--17,{"status":200,"gid":"491xxxxxxxxxxxx-1551211744@g.us"}
```

**Comment by Rhymen** [comment]
#97

**Comment by bottookku** [comment]
@SchulteMK thank you, but how it code i will use?

**Comment by SchulteMK** [comment]
I actually did not implement it yet.

**Comment by SchulteMK** [comment]
I implemented it really quick, but I did not test it yet. Can you test it and reopen the issue if needed?
