### ISSUE TITLE
Cannot send images

### ISSUE THREAD

**Issue by Mikolasek93** [Rhymen/go-whatsapp#11]
Hello, i cannot send images as used in example. Worked before. Now image is sent, but it cannot be opened within WhatsApp in phone. It stucks app when i click on the photo, there is also no thumbnail.

Could you update examples for images/file sending?

Thanks a lot for your great work!

EDIT: Tried exactly your code from examples and it works, probably fault in my code, sorry for opening invalid ticket, please close it.

**Comment by tkovs** [comment]
It's working here. Can u show ur source exactly?

**Comment by tkovs** [comment]
Did you get it?

**Comment by tkovs** [comment]
I'm sorry, I didn't see that change. Ok.
