### ISSUE TITLE
Implementation Example in REST

### ISSUE THREAD

**Issue by dimaskiddo** [Rhymen/go-whatsapp#110]
Following repository has an implementation of go-whatsapp in REST
[dimaskiddo/go-whatsapp-rest](https://github.com/dimaskiddo/go-whatsapp-rest)
`https://github.com/dimaskiddo/go-whatsapp-rest`

Still Need Some Review
Thanks

**Comment by valaszek** [comment]
Hi Dimas, congratulations for the job.

About 2 min after scanning the qrcode and sending msg the socket is closed. Any idea what that might be?
error writing to socket: write tcp 172.17.0.2:45700->31.13.71.49:443: write: connection reset by peer

**Comment by dimaskiddo** [comment]
yes i see the issue also, i think it's come from the websocket connection got interupted
when the error show, you can't re-use the connection (and may be also due to the gorilla websocket), need some modification in Go WhatsApp Library it self

My idea currently always open new connection then login or restore session for new event (like send text message), after that close the web socket connection (this function still not available)

What i need from the Go WhatsApp is a public function to close the connection, may be like this:

func (wac *Conn) Close() {
  wac.wsConn.Close()
}

Still need some test

**Comment by adiltonvalaszek** [comment]
I understand, but I would like keep alive the connection for receiving the messages. 
Is it a problem with the Go WhatsApp or gorilla websocket Library?

**Comment by dimaskiddo** [comment]
What i know Go WhatsApp already make a keep alived routine with interval between 20 - 90 seconds, i think the problem was related to this issues #74 and issues #106, so when connection dropped out we can't even to restore the session

Will try some sollution in issues #106 by modifying the keep alived interval

**Comment by dimaskiddo** [comment]
![screen shot 2019-03-02 at 12 42 03 am](https://user-images.githubusercontent.com/21129987/53658621-db5df780-3c8b-11e9-8347-1d3910e6455d.png)

Test result after modifying some section in conn.go [[dimaskiddo/whatsapp-go-mod]](https://github.com/dimaskiddo/whatsapp-go-mod) like servers, keep alived, close and reconnect, the websocket was keep alived for near of 1 hours

Still need more test

**Comment by adiltonvalaszek** [comment]
You're right. I got the same result. Thanks.

**Comment by dimaskiddo** [comment]
Clossing my own issue due to not related with go-whatsapp package, sorry :)

**Comment by victormedranop** [comment]
dimaskiddo how you solve this? when i try to send a message disconnect the wac.
i need to restart de solution.

Victor

**Comment by dimaskiddo** [comment]
as i know you can use error handler to do reconnection or restoring session, since the readPump already rewrited.

For this issue (sudden closed conenction) i just do some tweak and changes, as i prefer to use
