### ISSUE TITLE
Handle closing the connection

### ISSUE THREAD

**Issue by KrzysztofMadejski** [Rhymen/go-whatsapp#111]
It would be great to create the `Close` function that would be the same as Reconnect's first few lines:

https://github.com/Rhymen/go-whatsapp/blob/c9a81e9578840e5c04c49c9e6126a1682faf22fc/conn.go#L188-L193

**Comment by KrzysztofMadejski** [comment]
After invoking Close() the code is failing becasue the `readPump` routine keeps running.

```
github.com/gorilla/websocket.(*Conn).NextReader(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/kmadejski/go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:938 +0x59
github.com/gorilla/websocket.(*Conn).ReadMessage(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/kmadejski/go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:1028 +0x86
github.com/matterbridge/go-whatsapp.(*Conn).readPump(0xc0003e6340)
	/home/kmadejski/Projects/go-whatsapp/conn.go:293 +0xb2
created by github.com/matterbridge/go-whatsapp.NewConn
	/home/kmadejski/Projects/go-whatsapp/conn.go:130 +0x2c9
```

**Comment by KrzysztofMadejski** [comment]
Question: what should happen with all the queued messages after the connection has been closed? I think they need to be dropped.

**Comment by KrzysztofMadejski** [comment]
I'm now wondering do I want to have the Close function or do I prefer `go-whatsapp` to reconnect.

**Comment by KrzysztofMadejski** [comment]
My changes here: https://github.com/Rhymen/go-whatsapp/compare/master...KrzysztofMadejski:feature/reconnects

**Comment by SchulteMK** [comment]
`Restore()` and `Disconnect()` are implemented now and should satisfy your suggestions

**Comment by KrzysztofMadejski** [comment]
Thank you @SchulteMK for the great work!
