### ISSUE TITLE
save qrcode as image file

### ISSUE THREAD

**Issue by codenoid** [Rhymen/go-whatsapp#116]
from `<-qr` looks like return a base64 image, but it think it's not a valid base64 image

```
1@e1BI89ppIOMLzneaTuCXiBOD0tQM3UfWBuLkoRuEW0ArtDA677pc+3OI,Kpo9jYA5XBqlnoLkjCwCY+iUj8aFs0HCHuCwfxV7EUc=,gSBDVxw1OahON22s9xdNyg==
```
how i can save qrcode as image file

**Comment by dimaskiddo** [comment]
you can see the example in [dimaskiddo/go-whatsapp-rest](https://github.com/dimaskiddo/go-whatsapp-rest) helper file :)

Hope this helps you

**Comment by codenoid** [comment]
thank you @dimaskiddo 

```
tmp := <-chanqr

png, errPNG := qrcode.Encode(tmp, qrcode.Medium, 256)
if errPNG != nil {
	return
}

fmt.Println(base64.StdEncoding.EncodeToString(png))
```
