### ISSUE TITLE
Document the possible states of connection

### ISSUE THREAD

**Issue by KrzysztofMadejski** [Rhymen/go-whatsapp#120]
What are the possible states of connection and how the wsConn and wsConnOK are set in each case?

I tried to make sense of the current code while working on #111. I left some comments in following commits: https://github.com/Rhymen/go-whatsapp/commit/386b9ac0479f8bb45a1f0fadf03192f77a33ddbe https://github.com/Rhymen/go-whatsapp/commit/f871c283f6c55e07fe43a5630eb36b7cc8741de9 https://github.com/Rhymen/go-whatsapp/commit/fda26629f40ffb57927105c924b14fad8b6d543e https://github.com/Rhymen/go-whatsapp/commit/a98199a4f688aecb110cc38294069425ec15f27b

It would be very helpful to have above question documented.
CC @krombel  @SchulteMK

**Comment by SchulteMK** [comment]
imo not relevant any more due to the reworked structure of the connection
