### ISSUE TITLE
go.mod is case sensitive and the path need to match the module name

### ISSUE THREAD

**Issue by raianfs** [Rhymen/go-whatsapp#121]
The module name of the package is all lower case, but the URL to get the library contains a R.

The module name need to be upgraded.

**Comment by raianfs** [comment]
Looking again, I saw that the names are correct.
But running a project initialized with go mod, show me this error:

build command-line-arguments: cannot load github.com/Rhymen/go-whatsapp: cannot find module providing package github.com/Rhymen/go-whatsapp

If I change import to github.com/rhymen/go-whatsapp  I get this error (as expected)

go: github.com/rhymen/go-whatsapp@v0.0.0: parsing go.mod: unexpected module path "github.com/Rhymen/go-whatsapp"

**Comment by SchulteMK** [comment]
I think we should change all go.mod files to `Rhymen/go-whatsapp`

**Comment by SchulteMK** [comment]
all files should now reference `Rhymen/go-whatsapp`
