### ISSUE TITLE
How get phone number when login? 

### ISSUE THREAD

**Issue by Lucipher** [Rhymen/go-whatsapp#124]
How get phone number when login?

**Comment by fhwedel-hoe** [comment]
It looks like whatsapp.Session.wid contains the logged-in phone's number.

**Comment by hoehermann** [comment]
It looks like whatsapp.Session.wid contains the logged-in phone's number.

See the [example login procedure](https://github.com/Rhymen/go-whatsapp/blob/3f56542bf70be8ff87e23880ef08ec4b88dd1aa2/session.go#L117) how to get the session data.

**Comment by Lucipher** [comment]
@hoehermann 
Thanks,  I got it.
