### ISSUE TITLE
received invalid data

### ISSUE THREAD

**Issue by hoehermann** [Rhymen/go-whatsapp#125]
Whenever go-whatsapp wants to read the server's answer after sending a message (or a read acknowledgement), the connection fails with

    error processing data: received invalid data

and a reconnect is needed. This `ErrInvalidWsData` originates from https://github.com/Rhymen/go-whatsapp/blob/3f56542bf70be8ff87e23880ef08ec4b88dd1aa2/read.go#L59. Messages are sent to the contact, though.

This affects at least my own application and the [echo example](https://github.com/Rhymen/go-whatsapp/blob/3f56542bf70be8ff87e23880ef08ec4b88dd1aa2/examples/echo/main.go).

**Comment by SchulteMK** [comment]
Can you please check if the same error occoured before I merged the latest PR? I tagged the version as v0.0.1 before I merged

**Comment by hoehermann** [comment]
Yes, I just tried with the current master. Strangely enough, the `sendTextMessages` example is not affected.

**Comment by SchulteMK** [comment]
The go.mod of the examples referenced an old version of go-whatsapp. I changed them now to use the latest version.

**Comment by hoehermann** [comment]
Thanks. Your changes at 3fb29d5 seem to have been reverted at 7f76648a.

Also the examples won't work out of the box as they still use `RestoreSession` rather than `RestoreWithSession`.

Related to the original question, I managed to pull some debug output from the communication. This is what is encountered up in `processReadData`:

    Valid data: []string{"!", "1552512078460"}
    Valid data: []string{"1552512078.--0", "REDACTED_JSON"}
    Valid data: []string{"s1", "[\"Conn\",REDACTED_JSON]"}
    Valid data: []string{"d1fc256c5766a1c6.--1f", REDACTED_BINARY}
    Valid data: []string{"s2", "[\"Blocklist\",{\"id\":1,\"blocklist\":[]}]"}
    Valid data: []string{"1552512078.--1", "{\"status\":200}"}
    Valid data: []string{"s3", "[\"Stream\",\"update\",true,\"0.3.2386\"]"}
    Valid data: []string{"s4", "[\"Props\","REDACTED_JSON"]"}
    Valid data: []string{"preempt-d1fc256c5766a1c6.--20", "REDACTED_BINARY"}
    Valid data: []string{"d1fc256c5766a1c6.--21", "REDACTED_BINARY"}
    Valid data: []string{"!", "1552512098856"}
    Valid data: []string{"d1fc256c5766a1c6.--24", "REDACTED_BINARY"}
    Invalid data: []string{"2BA5323571AD0567DD4D", ""}
    error caught in handler: error processing data: received invalid data
    Valid data: []string{"2BA5323571AD0567DD4D", "REDACTED_JSON"}
    echoed message '@echo test6' to user REDACTED@s.whatsapp.net
    Valid data: []string{"s7", "REDACTED_JSON"}
    Valid data: []string{"!", "1552512128854"}

It seems like the function is fed an empty string. The function is then re-invoked with valid data. 

I was under the impression errors fed to the handler are critical and need to be coped with. Seems I was mistaken. In my application, I now ignore this error silently.
