### ISSUE TITLE
whatsapp.Conn has no field or method RestoreSession on example

### ISSUE THREAD

**Issue by njentit** [Rhymen/go-whatsapp#127]
Try running code from examples/sendTextMessages directory got these error:
src/github.com/Rhymen/go-whatsapp/examples/sendTextMessages/main.go:46:21: wac.RestoreSession undefined (type *whatsapp.Conn has no field or method RestoreSession)

**Comment by SchulteMK** [comment]
In #114 we did many changes to the connection and session. The examples are not yet fixed up (blame me)... 
The function signiture changed to `func (wac *Conn) RestoreWithSession(session Session)`. You can use it, it should have the same behavior as before.
Hopefully I can fix up the examples during the next few days

**Comment by houstondapaz** [comment]
I fixed with #142

**Comment by SchulteMK** [comment]
#142
