### ISSUE TITLE
Rhymen - Paid freelance job to implement a sendMessage in the whatsapp-web-reveng project

### ISSUE THREAD

**Issue by alfredbaudisch** [Rhymen/go-whatsapp#13]
@Rhymen I didn't find your e-mail, so trying to contact by here :)

Since you managed to create an implementation of [whatsapp-web-reveng](https://github.com/sigalor/whatsapp-web-reveng) from scratch in Go, you have the knowledge to do the 2 adjustments that we need.

We need an easy way to send and receive messages in the JS code of the base project, basically what you did in your examples/sendTextMessages implementation, which works perfectly.

1) A callback when receiving a message, in the JS server. Example: onMessageReceived(function(payload) {
.... our custom code here
})

`payload` contains the received message, the sender JID, the timestamp and the message JID/ID.

2) An easy way to send a message back to the contact. Basically you will wrap in a JS function all the current hard steps involved in sending a message. This function will basically communicate with the Python backend of the whatsapp-web-reveng, which involves hashing/cryptographing the content, etc. What we want is a simple sendMessage function that wraps and does all the work.

Example: sendMessage(payload).

Are you available for freelance work to do that? If so, please contact me at alfred@fredbots.com (this is a work to be integrated in our platform https://fredbots.com).

**Comment by alfredbaudisch** [comment]
Solved.

**Comment by arunrreddy** [comment]
@alfredbaudisch Can you share your working sendTextMessage code? I am stuck with that.
