### ISSUE TITLE
check if loggedin to whatsapp

### ISSUE THREAD

**Issue by Deewai** [Rhymen/go-whatsapp#131]
The loggedIn field in the Conn struct should be accessible for us to check if we are logged in or not

**Comment by Deewai** [comment]
solved it with this
if instance.WhatsAppConn.Info != nil && instance.WhatsAppConn.Info.Connected {
	instance.DesktopConn = ws
	instanceExists = true
}

**Comment by tgssb** [comment]
How do I check if the device is missing from the internet?

**Comment by Deewai** [comment]
Do you mean to say "check if the device(mobile device) is connected to the internet"?

**Comment by tgssb** [comment]
yes, sorry

**Comment by Deewai** [comment]
apart from the presence messages being sent by whatsapp, i don't know of any other way

**Comment by tgssb** [comment]
if not ask too much, can you give me an example code?
