### ISSUE TITLE
list of connected groups or conversations

### ISSUE THREAD

**Issue by Deewai** [Rhymen/go-whatsapp#134]
How to get a list of groups user is connected to or the list of conversations user has.
Conn.Chats() doesn't seem to return anything useful

**Comment by franklinsales** [comment]
@Deewai 
Did you found a way to do it? I have the same question.

**Comment by sthales** [comment]
Same question...

**Comment by pentateu** [comment]
+1

conn.Contacts() also does not work.

**Comment by Deewai** [comment]
@franklinsales I found a way around it.
After calling the conn.Contacts() and i think conn.Chats(), it updates the contacts lists in conn.Store.Contacts. so you can get the contacts from there after calling the function

**Comment by sthales** [comment]
Using the Chats func I was able to get the list of chats, but curiously it works only with iOS, with Android it returns null

`	return wac.query("chat", "", "", "", "", "", 0, 0)`

**Comment by Deewai** [comment]
@sthales I use android, so i also get null but conn.Store.Contacts gets updated so i make use of that

**Comment by SchulteMK** [comment]
I think @punneetmehta did a great job implementing the missing parts. Thanks!
