### ISSUE TITLE
checking if number is blocked

### ISSUE THREAD

**Issue by elpulga** [Rhymen/go-whatsapp#136]
Is there a method or way to know if the number being used gets blocked?

**Comment by SchulteMK** [comment]
do you mean blocked by whatsapp or by an other user?

**Comment by elpulga** [comment]
By WhatsApp

**Comment by SchulteMK** [comment]
I do not know if there is a method to detect that, but my number did not get blocked since the start of this project. I send and receive messages via `go-whatsapp` every day

**Comment by kickbox** [comment]
@SchulteMK interesting. Sometimes phone numbers get blocked when my friends use it to marketing purposes. After tweaking with message frequency, presense updates, server IP config, I was able to limit the occurrence of such behaviour but to only 40% of the time. Could you please elaborate how have you overcome this, or in general how you have used it please - this would help understanding the WhatsApp ban behaviour.

Do you send messages to contacts who dont have your number saved? How many messages would you send everyday? How many contacts do you send to every day? What is the frequency per minute of each message? Do you host go-whatsapp in a server that is away from your country? Anything unique that you do?
