### ISSUE TITLE
wac.Store.Contacts returns an empty map

### ISSUE THREAD

**Issue by wahyusaputra** [Rhymen/go-whatsapp#137]
Hello, 

I would like to get the list of whatsapp contacts. 

I was following the suggestion from, #21 

I was trying to print the contacts map and get an empty results.

What did I do wrong?
Would you please kindly point me to the right solution?

Many thanks.

```
func main() {
	//create new WhatsApp connection
	wac, err := whatsapp.NewConn(5 * time.Second)
	if err != nil {
		log.Fatalf("error creating connection: %v\n", err)
	}

	//Add handler
	wac.AddHandler(&waHandler{wac})

	//login or restore
	if err := login(wac); err != nil {
		log.Fatalf("error logging in: %v\n", err)
	}
        
	contacts := wac.Store.Contacts
	fmt.Println("contacts: ", contacts)

	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt, syscall.SIGTERM)
	<-c

	//Disconnect safe
	fmt.Println("Shutting down now.")
	session, err := wac.Disconnect()
	if err != nil {
		log.Fatalf("error disconnecting: %v\n", err)
	}
	if err := writeSession(session); err != nil {
		log.Fatalf("error saving session: %v", err)
	}
}
```

**Comment by SchulteMK** [comment]
You have to introduce some kind of delay before retrieving the contacts. Something like this should work for you:
```
	<-time.After(10 * time.Second)
	contacts := wac.Store.Contacts
	fmt.Println("contacts: ", contacts)
```
That is because we are not actively asking for the contacts, but we are saving them as they get send by whatsapp. From the time we are connected successfully to the server we are getting flooded with data for a few seconds. This data also contains contacts.

**Comment by wahyusaputra** [comment]
Yes, it works. 

Many thanks for the help.

Really appreciate it.

Best regards,

Wahyu

**Comment by addi0512** [comment]
can you share handle  `waHandler{wac}` in code .. i still get blank map.
