### ISSUE TITLE
WhatsApp REST API ( FREE )

### ISSUE THREAD

**Issue by punneetmehta** [Rhymen/go-whatsapp#143]
REST API Implementation ( https://wapi.xyz/ ) based on go-whatsapp Library.
Supports all type of Message Sending and Creation of WhatsApp Bots.

Still in beta mode, and open to questions / suggestions and feedback :)
( https://github.com/punneetmehta/wapi_rest )

Start creating awesome applications/bots for WhatsApp.
{ use the RESTAPI, Documentation at https://wapi.xyz/ }

**Comment by carvs** [comment]
If you were looking for approval or recognition from the community using this platform, it may be best to share the API source code on your github, as it is free. I imagine it would be much more useful for everyone.

This is my opinion, but still congratulations on the work. I think you must have worked hard to do all implementations of the API.

**Comment by punneetmehta** [comment]
I am not doing it for approval or any kind of recognition.
I build this out of curiosity, and sharing it for free because a lot of people still haven't figured out how to use the library or how to make it work.

Sharing the API source code is obviously the best solution, 
BUT then there will be no way to stop Spammers from creating marketing applications on the top of it.

**Comment by dimaskiddo** [comment]
It's might be just my feeling that it has the same approach like i've done before in #110 [dimaskiddo/go-whatsapp-rest](https://github.com/dimaskiddo/go-whatsapp-rest) but with more improvement in your server side code, nice works by the way ;)

It would nice if you can share the server side code with some limitation, according to security issue that you concern about

**Comment by punneetmehta** [comment]
@dimaskiddo just saw your code, we have little similarities in our approach, but i must say your code is really well structured.

and, Sharing the server code will result in N number of Marketing Applications, Commercial APIs, similar to what happened with mgp25 Chat-API.

I can suggest a better option, why not collaborate for creating a better secure API service.
We can cover the security part/concern at backend, and still provide the service for free.
What say?

**Comment by pentateu** [comment]
@punneetmehta   "there will be no way to stop Spammers from" this does not make any sense.

What do you mean by "a better secure API service" ? Can you be specific? There is nothing stopping anyone from creating spam tools using this repo right here, is all here. No need for your server-side code. Sharing your code is your way to pay back the community and help others. VEry weak argument and to me looks like you want to $$% capitalize one it later. Also, a free REST API make it even easy to anyone to build spam/marketing tools. So your argument makes zero 0 sense.

**Comment by punneetmehta** [comment]
Yes you are right, anyone can use this repo to create marketing tools.
But I don't want to offer them rest-api ready code for the same purpose.

by "Better Secure API" i mean, somehow to create a logic, that sessionFile need not to be stored at a central server ( or API Server ).
It should be stored at client side and requested or updated as and when required. ( With some 2-way encryption ) { just a thought, i have no idea if it is even feasible or not }
and moreover, all kind of localData needs to be stored at client side only.
Server should just act as a communication medium, between client and whatsapp web.

I already mentioned my concern for "sharing the source code".

and If i want to capitalise it, i would have started it as a paid service only. ( Similar to what other providers are offering )

Coming to your last part, providing  a direct api obviously increases the chance of spamming and marketing tools.
BUT, some kind of logic can be designed to analyse what channels are doing spamming or marketing and can be automatically blocked.
( atleast we can limit the abuse of service )

**Comment by bayuterra** [comment]
how to make webhook sir ?
