### ISSUE TITLE
Invite people to an already created broadcast group/list

### ISSUE THREAD

**Issue by c1nema** [Rhymen/go-whatsapp#151]
Hey people,

First of all. Nice project. Worked fine for everything i needed to do so far. 
But now im stuck at a little problem i don't know how to solve on my own:

I already created a broadcast group/list on my phone by hand (because i guess there is now way of doing this automated) but now i want to invite people automatically into the group/list.

In the protobuf file (def.proto), inside the "WebMessageInfo" message definition there is a enum called STUBTYPE, which in turn got the constants BROADCAST_(CREATE, ADD, REMOVE).

I mean, BROADCAST_ADD sound's like the thing i'm looking for. But i dont know how to craft a message for this and send it away.

I gladly take any help i can get.

BTW, the reason no code snippet is here, because i really cant figure out how to craft the message or even begin to do so.

If any additional information is needed, go ahead and ask. I'll gladly provide anything i got.

**Comment by Ased2235** [comment]
> BTW, the reason no code snippet is here, because i really cant figure out how to craft the message or even begin to do so.
> 
> If any additional information is needed, go ahead and ask. I'll gladly provide anything i got.


did you able to get it working?

**Comment by sthales** [comment]
> but now i want to invite people automatically into the group/list.
To broadcast lists you can't. 
You can't edit lists on WhatsApp Web.
![image](https://user-images.githubusercontent.com/31826331/73295435-6fab4400-41e6-11ea-90ee-d70c711cfe71.png)

> I mean, BROADCAST_ADD sound's like the thing i'm looking for. But i dont know how to craft a message for this and send it away.

This is just the "info" that shows in the chat when you add someone to the list.
![image](https://user-images.githubusercontent.com/31826331/73295241-16431500-41e6-11ea-88e7-c77edfd4be3d.png)
