### ISSUE TITLE
How To Send Message To A Group

### ISSUE THREAD

**Issue by it-sumanp** [Rhymen/go-whatsapp#153]
How Can I send Message to a Group?

To send a message to individuals I am using RemoteJid: "91XXXXXXXXX@s.whatsapp.net".

Do Groups have some similar identifiers 

@Rhymen Please Help

**Comment by codenoid** [comment]
group identity is something like `99229588124-160299122@g.us` alias of `phone_number-createddate@g.us`

**Comment by it-sumanp** [comment]
Thanks for the help , @codenoid 
Let me see if this works :)

**Comment by rhidaytm** [comment]
how example use

**Comment by jackesdavid** [comment]
You will send in the same way you are sending to single persons
But, of course,  you need to joinof the group first. :)

**Comment by jackesdavid** [comment]
And there is a sample on README page

**Comment by rhidaytm** [comment]
i just need to get my group id I tried various samples but it didn't work

**Comment by jackesdavid** [comment]
Hi friend, you can call me on dm, can you send us the sample code you are trying to use?

**Comment by andig** [comment]
> group identity is something like 99229588124-160299122@g.us alias of phone_number-createddate@g.us

@codenoid according to @luawaltzer in https://github.com/Rhymen/go-whatsapp/issues/40#issuecomment-421717459 the group's timestamp is the unix timestamp. How could I find that for an existing group when the exact time isn't displayed in the Whatsapp app?

Would appreciate a howto ;)
