### ISSUE TITLE
Custom handler for contacts

### ISSUE THREAD

**Issue by Deewai** [Rhymen/go-whatsapp#155]
A custom handler for when contacts/chats is updated is very important so. This makes it possible to update the contacts/chats on our application without having to periodically request for contact/chat list. This should not stop the inbuilt handler that updates the contacts/chats in the store. It should just be an addition.

**Comment by timotew** [comment]
@Deewai I think you should close this since the PR has been merged.

**Comment by Deewai** [comment]
@timotew Yea, thanks
