### ISSUE TITLE
Message read

### ISSUE THREAD

**Issue by Mikolasek93** [Rhymen/go-whatsapp#16]
Is it available to determine, if message was read by end-user? 
Could you please provide handler example? Thanks!

**Comment by Rhymen** [comment]
This is currently not possible, because we didn't map all required fields to our custom structs. From what I can see the message proto contains a status field, which can be one of

```
var WebMessageInfo_STATUS_name = map[int32]string{
	0: "ERROR",
	1: "PENDING",
	2: "SERVER_ACK",
	3: "DELIVERY_ACK",
	4: "READ",
	5: "PLAYED",
}
```
We have to either map a few more fields from the proto to our custom message structs or just return the proto without mapping it.

**Comment by Rhymen** [comment]
I added the status field to the message info struct and a couple of constants for the different status so you can play around with it.

**Comment by Mikolasek93** [comment]
Thanks a lot! 
Could you point me to code, that forces web whatsapp to notify your app handlers about incoming messages? Because something like this could be done in "read" acks for my sent messages.
Or how to implement custom handler for detecting "read acks"?
Thanks!

**Comment by SchulteMK** [comment]
The actual calling of the handlers happen [here](https://github.com/Rhymen/go-whatsapp/blob/9bada3ce381e4dfb1331e1ca81abdec1bf098f8c/handler.go#L82). You probably have to imlement an small `AckMessage` type and provide an handler interface for it ([message types and handler interfaces](https://github.com/Rhymen/go-whatsapp/blob/master/message.go)). [Here](https://github.com/Rhymen/go-whatsapp/blob/9bada3ce381e4dfb1331e1ca81abdec1bf098f8c/conn.go#L224) are the JSON messages getting "created". The ack messages are in the json format, so you have to check for acks and dispatch them seperatly with something like `wac.handle(AckMessage{...})`. It is probaly easier to just implement the `JsonMessageHandler` in your code and check for acks there

**Comment by Mikolasek93** [comment]
Oh i see! Perfect! 

Simplified solution:
`
func (*WaHandler) HandleJsonMessage(message string) {
	fmt.Printf("STATUS RECEIVED :%v\n", message)
}
`
Now i can extract info about message status and so on depends on ack 1-sent 2-delivered 3-read 

`
["Msg",{"cmd":"ack","id":"0F739EA8D94AEAF9579812A985DD43C5","ack":2,"from":"420731316166@c.us","to":"420606527569@c.us","t":1534427787}]
`
Thanks a lot!

**Comment by tgssb** [comment]
How do I mark the message as read?

**Comment by roggerlie** [comment]
> 
> 
> Oh i see! Perfect!
> 
> Simplified solution:
> `func (*WaHandler) HandleJsonMessage(message string) { fmt.Printf("STATUS RECEIVED :%v\n", message) }`
> Now i can extract info about message status and so on depends on ack 1-sent 2-delivered 3-read
> 
> `["Msg",{"cmd":"ack","id":"xxxmessageidxxxx","ack":2,"from":"xxxxx@c.us","to":"xxxxx@c.us","t":1534427787}]`
> Thanks a lot!

how do extract json in go ?
please help me

**Comment by sunnybear** [comment]
Can anybody tell me how to check if message has been sent (w/o returned ID). Sometimes messages are sent, but no ID returned.
