### ISSUE TITLE
Contact Name Function

### ISSUE THREAD

**Issue by tgssb** [Rhymen/go-whatsapp#164]
Hello @Rhymen . 

I'm getting the contact name using the code:

>  `getName, _: = wac.Store.Contacts [jid]`

Could you implement a function, similar to getting the contact pic?

>  `getPic, _: = GetProfilePicThumb (jid)`

Eg: 

>  `getPic, _: = GetProfileName (jid)`

I know this is limited because it depends on whether the user has a conversation or the number saved in the contact list. But I think it would help, even if it returned empty in some cases

greetings, thank you
your project has opened many opportunities for me 😃

**Comment by addi0512** [comment]
can you tell me handler to print contacts?

**Comment by tgssb** [comment]
```
getName, _ := wac.Store.Contacts[number+"@s.whatsapp.net"]
fmt.Println(getName)
```

**Comment by Ased2235** [comment]
I think this is what you looking for 
`func Getthumb(wac *whatsapp.Conn, RemoteJID string) string {
// RemoteJID is the sender ID the one who send the text or the media message or basically the WhatsappID just pass it here
profilePicThumb, _ := wac.GetProfilePicThumb(RemoteJID)
profilePic := <- profilePicThumb

thumbnail := ThumbUrl{}
err := json.Unmarshal([]byte(profilePic), &thumbnail)

if err != nil {
    fmt.Println("errr while getting thumbnail", err)
    return ""
}


fmt.Println("getting thumbnail ", thumbnail.Status)
//    return ""
    // meaning thumbnail is not available because the person has no profile pic so what i did is return empty string


// Basically the EURL is what holds the profile picture of the person
return get_image( thumbnail.EURL)	
}


type ThumbUrl struct {
    EURL string 'json:"eurl"'
    Tag string 'json:"tag"'
    Status int64 'json:"status"'
}`
