### ISSUE TITLE
Sudden error on login

### ISSUE THREAD

**Issue by elpulga** [Rhymen/go-whatsapp#165]
Everything was working as intended, and out of the blue I get the following error:

`error decoding login connResp: json: cannot unmarshal array into Go value of type map[string] interface {}`

What could be wrong?

**Comment by tgssb** [comment]
Did you solve it? I have the same problem?

**Comment by tgssb** [comment]
To solve the problem, you need to update the version of WhatsApp Web in code



https://github.com/Rhymen/go-whatsapp/blob/8d76e32a6d8ecad32a173fb8c16660dd1d1c1bea/session.go#L152

**Update to**

`login := []interface{}{"admin", "init", []int{0, 3, 2390}, []string{wac.longClientName, wac.shortClientName}, session.ClientId, true}`



And line



https://github.com/Rhymen/go-whatsapp/blob/8d76e32a6d8ecad32a173fb8c16660dd1d1c1bea/session.go#L306

**Update to**

`init := []interface{}{"admin", "init", []int{0, 3, 2390}, []string{wac.longClientName, wac.shortClientName}, wac.session.ClientId, true}`

It worked for me.

**Comment by breadpanz** [comment]
you can try to check this out https://github.com/dimaskiddo/go-whatsapp-rest/issues/6

**Comment by AbyssEkko** [comment]
having same problem but tgssb solution didnt work, what worked for you?

**Comment by elpulga** [comment]
It happend twice, and both times it just stopped happening after a while (about 40 minutes)

**Comment by AlmogBaku** [comment]
shouldn't we handle it gracefully?
