### ISSUE TITLE
Mark the message as read.

### ISSUE THREAD

**Issue by petrGB** [Rhymen/go-whatsapp#166]
Good afternoon. When I receive messages , they are never marked as read. How can this be implemented? In the example of receiving the message and echo, this does not occur

**Comment by elpulga** [comment]
In your `HandleTextMessage(message whatsapp.TextMessage)` function you have to call

`wac.Read(message.Info.RemoteJid, message.Info.Id)`

**Comment by highness28** [comment]
Use the package Connection struct there is a method `Read` there

```whatsapp.Conn .Read(JID, messageKey)```
