### ISSUE TITLE
HandleRawMessage on GetType() always return REVOKE

### ISSUE THREAD

**Issue by Valdenirmezadri** [Rhymen/go-whatsapp#168]
Hello!
I thinks this may be a issue.
when message.GetMessage().GetProtocolMessage() is nil 
message.GetMessage().GetProtocolMessage().GetType().String() always will be REVOKE

![image](https://user-images.githubusercontent.com/4634624/58963347-5d762480-8783-11e9-8a06-c5efc08b76ea.png)

![image](https://user-images.githubusercontent.com/4634624/58963327-564f1680-8783-11e9-81d9-4f9dab636b17.png)

![image](https://user-images.githubusercontent.com/4634624/58963333-58b17080-8783-11e9-9743-4056d8a105b6.png)

**Comment by orangehaired** [comment]
I encountered the same problem. I was processing it as revoke.
My solution -->
`
	protoMessage := message.GetMessage().GetProtocolMessage()
	if protoMessage != nil && protoMsg.GetType() == proto.ProtocolMessage_REVOKE 
        .... 
`
