### ISSUE TITLE
qr code scan time out

### ISSUE THREAD

**Issue by LevisKimathi** [Rhymen/go-whatsapp#169]
`package main

import (
	"encoding/gob"
	"fmt"
	"os"
	"time"
	"html/template"
	"net/http"
	"github.com/Rhymen/go-whatsapp"
)

type ContactDetails struct {
	Phone   string
	Message string
}

var status bool
var qrcode string

func main() {
	//create new WhatsApp connection
	tmpl := template.Must(template.ParseFiles("forms.html"))

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			tmpl.Execute(w, nil)
			return
		}

		details := ContactDetails{
			Phone:   r.FormValue("phone"),
			Message: r.FormValue("message"),
		}

		watsapp(details.Phone,details.Message,w,r)

		if status == true{
			tmplqr := template.Must(template.ParseFiles("qr.html"))

			http.Redirect(w,r,"http://localhost:8080/qr/",http.StatusFound)
	
			http.HandleFunc("/qr/", func(w http.ResponseWriter, r *http.Request) {
				tmplqr.Execute(w, qrcode)
				
			})
		}
	})

	http.ListenAndServe(":8080", nil)
	
}

func watsapp(Phone string, Message string, w http.ResponseWriter, r *http.Request) {
	tmpl := template.Must(template.ParseFiles("forms.html"))
	wac, err := whatsapp.NewConn(60 * time.Second)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error creating connection: %v\n", err)
		return
	}

	err = login(wac,w,r)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error logging in: %v\n", err)
		return
	}

	<-time.After(60 * time.Second)

	msg := whatsapp.TextMessage{
		Info: whatsapp.MessageInfo{
			RemoteJid: Phone + "@s.whatsapp.net",
		},
		Text: Message,
	}

	err = wac.Send(msg)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error sending message: %v", err)
	}else{
		tmpl.Execute(w, struct{ Success bool }{true})
	}
}

func login(wac *whatsapp.Conn, w http.ResponseWriter, r *http.Request) error {
	//load saved session
	tmpl := template.Must(template.ParseFiles("forms.html"))
	session, err := readSession()
	if err == nil {
		//restore session
		session, err = wac.RestoreWithSession(session)
		if err != nil {
			return fmt.Errorf("restoring failed: %v\n", err)
		}
	} else {
		//no saved session -> regular login
		qr := make(chan string)
		go func() {
			status = true
			qrcode = <-qr
		}()
		session, err = wac.Login(qr)
		if err != nil {
			return fmt.Errorf("error during login: %v\n", err)
		}else{
			tmpl.Execute(w, struct{ Success bool }{true})
		}
	}

	//save session
	err = writeSession(session)
	if err != nil {
		return fmt.Errorf("error saving session: %v\n", err)
	}
	return nil
}

func readSession() (whatsapp.Session, error) {
	session := whatsapp.Session{}
	file, err := os.Open(os.TempDir() + "/whatsappSession.gob")
	if err != nil {
		return session, err
	}
	defer file.Close()
	decoder := gob.NewDecoder(file)
	err = decoder.Decode(&session)
	if err != nil {
		return session, err
	}
	return session, nil
}

func writeSession(session whatsapp.Session) error {
	file, err := os.Create(os.TempDir() + "/whatsappSession.gob")
	if err != nil {
		return err
	}
	defer file.Close()
	encoder := gob.NewEncoder(file)
	err = encoder.Encode(session)
	if err != nil {
		return err
	}
	return nil
}`

Hi I'm new to go lang. I have been trying out this awesome library. What I'm trying to do is show
the qr code on a webpage.
The problem is it always shows error logging in: error during login: qr code scan timed out
immediately after showing the qr code irregardless of the time out that is set
However the code work perfectly when using qrCodeTerminal.
As I said I'm new to go lang. I would appreciate your help.

**Comment by highness28** [comment]
create a new method in qrcodeTerminal.go in the package and insert these below the Get method

```
func (v *qrcodeTerminal) GetContent(content interface{}) (string, error) {
	var qr *qrcode.QRCode
	var err error
	if t, ok := content.(string); ok {
		qr, err = qrcode.New(t, qrcode.RecoveryLevel(v.level))
	} else if t, ok := content.([]byte); ok {
		qr, err = qrcode.New(string(t), qrcode.RecoveryLevel(v.level))
	}
	if qr != nil && err == nil {
		qrCodeString, _ := json.Marshal(qr)
		return string(qrCodeString), nil
	}

	return "", err
}
```

using that code you'll be able to get the qr code details and you can such packages on your front-end side such as react-qr-reader to generate the qr code in your web page

the next thing to do is the service where you'll use that method

```
utils.Cprint.InfoLn("Requesting QR Code")
wac, err := whatsapp.NewConn(5 * time.Second) // we need a new wac in order for us to request a qr code to whatsapp

if err != nil {
	// If code gets here meaning it fails then you have to send a response to front-end to request another one
	utils.Cprint.ErrorLn("Error connecting to whatsapp: %v", err)
}

qrCodeString := make(chan string)
go func() {
	// initialize the qrcodeTerminal which will be the one responsible on generating the qr details
	terminal := qrcodeTerminal.New()

	// after that this is where you will use that code that we inserted in qrcodeTerminal.go
	// qrCodeContent is a string by the way
	qrCodeContent, _ := terminal.GetContent(<-qrCodeString)
}()
```

PS: I just posted a fragment of my code which will solve your problem.

**Comment by highness28** [comment]
Another thing. everytime your qr code timed out or expired your front-end should just request a new one. the requester should always be your front-end and not the other way around.

**Comment by LevisKimathi** [comment]
Thank you highness28. I am currently working on what you have told me.

**Comment by Valdenirmezadri** [comment]
> Another thing. everytime your qr code timed out or expired your front-end should just request a new one. the requester should always be your front-end and not the other way around.

Can you make a example of an re-generate qrcode?

**Comment by highness28** [comment]
> > Another thing. everytime your qr code timed out or expired your front-end should just request a new one. the requester should always be your front-end and not the other way around.
> 
> Can you make a example of an re-generate qrcode?

The response was actually from a channel but the QR is not so I have to device a solution to send the QR string to the front-end side. I created a GRPC request wherein it returns the QR string while the response (timeout/token expiration/qr expiration because whatsapp qr code only last for 15 seconds) is coming from a queue service (RabbitMQ) then is consumed by another service to be send to front-end.

there is actually no re-generate qrcode. there is just generate qr code function. the front-end is the one requesting another qrcode when RabbitMQ sends the response timeout or token expired.

**Comment by axeldeveloper** [comment]
> create a new method in qrcodeTerminal.go in the package and insert these below the Get method
> 
> ```
> func (v *qrcodeTerminal) GetContent(content interface{}) (string, error) {
> 	var qr *qrcode.QRCode
> 	var err error
> 	if t, ok := content.(string); ok {
> 		qr, err = qrcode.New(t, qrcode.RecoveryLevel(v.level))
> 	} else if t, ok := content.([]byte); ok {
> 		qr, err = qrcode.New(string(t), qrcode.RecoveryLevel(v.level))
> 	}
> 	if qr != nil && err == nil {
> 		qrCodeString, _ := json.Marshal(qr)
> 		return string(qrCodeString), nil
> 	}
> 
> 	return "", err
> }
> ```
> 
> using that code you'll be able to get the qr code details and you can such packages on your front-end side such as react-qr-reader to generate the qr code in your web page
> 
> the next thing to do is the service where you'll use that method
> 
> ```
> utils.Cprint.InfoLn("Requesting QR Code")
> wac, err := whatsapp.NewConn(5 * time.Second) // we need a new wac in order for us to request a qr code to whatsapp
> 
> if err != nil {
> 	// If code gets here meaning it fails then you have to send a response to front-end to request another one
> 	utils.Cprint.ErrorLn("Error connecting to whatsapp: %v", err)
> }
> 
> qrCodeString := make(chan string)
> go func() {
> 	// initialize the qrcodeTerminal which will be the one responsible on generating the qr details
> 	terminal := qrcodeTerminal.New()
> 
> 	// after that this is where you will use that code that we inserted in qrcodeTerminal.go
> 	// qrCodeContent is a string by the way
> 	qrCodeContent, _ := terminal.GetContent(<-qrCodeString)
> }()
> ```
> 
> PS: I just posted a fragment of my code which will solve your problem.

How to use qrCodeContent in html
