### ISSUE TITLE
Where are these constants used?

### ISSUE THREAD

**Issue by tkovs** [Rhymen/go-whatsapp#17]
https://github.com/Rhymen/go-whatsapp/blob/1c2b0859f6f337bee23498afba3b37140fccb803/conn.go#L19-L59

**Comment by Rhymen** [comment]
The function `func (wac *Conn) writeBinary(node binary.Node, metric metric, flag flag, tag string) (<-chan string, error)` in _conn.go_ expects a metric. I'm not sure what every metric does, but they need to be put into the binary messages like so `[messageTag],[metric][flag][binaryMessage]`. The function `writeBinary` is called by a couple of functions in the _contacts.go_ and by the `sendProto` function in _message.go_ .

**Comment by tkovs** [comment]
I'll check this soon and reopen if it needs to. Thank you!
