### ISSUE TITLE
load message : runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by ggrikgg** [Rhymen/go-whatsapp#173]
Hello!
I try to load message after id using
`wac.LoadMessagesAfter(k + "@s.whatsapp.net", v ,0)`
everything is okey. but if message id doesn't exist, I have error
![image](https://user-images.githubusercontent.com/49714445/59594800-3c0b2600-90fd-11e9-9690-3aa774681c92.png)
how can I fix it?

**Comment by kaxap** [comment]
@ggrikgg could you please verify that your issue is resolved via #185?

**Comment by ggrikgg** [comment]
yes. now it works good. thank you
