### ISSUE TITLE
sometimes, error on send

### ISSUE THREAD

**Issue by Valdenirmezadri** [Rhymen/go-whatsapp#175]
I can't figure out why

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x9721a8]

goroutine 3307 [running]:
github.com/Valdenirmezadri/htchat-server/vendor/github.com/Rhymen/go-whatsapp.(*Conn).encryptBinaryMessage(0xc000256460, 0xc6f02d, 0x6, 0xc000351800, 0xb47260, 0xc0003fae80, 0x0, 0xc000076700, 0xc0008f2e88, 0x7fb5c66a4000, ...)
	/home/junior/go/src/github.com/Valdenirmezadri/htchat-server/vendor/github.com/Rhymen/go-whatsapp/write.go:112 +0x88
github.com/Valdenirmezadri/htchat-server/vendor/github.com/Rhymen/go-whatsapp.(*Conn).writeBinary(0xc000256460, 0xc6f02d, 0x6, 0xc000351800, 0xb47260, 0xc0003fae80, 0xc28010, 0xc000947400, 0x14, 0xc000947400, ...)
	/home/junior/go/src/github.com/Valdenirmezadri/htchat-server/vendor/github.com/Rhymen/go-whatsapp/write.go:41 +0x79
github.com/Valdenirmezadri/htchat-server/vendor/github.com/Rhymen/go-whatsapp.(*Conn).sendProto(0xc000256460, 0xc0035bf420, 0x14, 0xc000bc5280, 0x1b)
	/home/junior/go/src/github.com/Valdenirmezadri/htchat-server/vendor/github.com/Rhymen/go-whatsapp/message.go:107 +0x247
github.com/Valdenirmezadri/htchat-server/vendor/github.com/Rhymen/go-whatsapp.(*Conn).Send(0xc000256460, 0xbd2880, 0xc0035b3280, 0xc0035b3280, 0x14, 0x0, 0x5ac2a1)
	/home/junior/go/src/github.com/Valdenirmezadri/htchat-server/vendor/github.com/Rhymen/go-whatsapp/message.go:38 +0x1239
github.com/Valdenirmezadri/htchat-server/wp.handleWPMessages()
	/home/junior/go/src/github.com/Valdenirmezadri/htchat-server/wp/handler.go:52 +0x16f
created by github.com/Valdenirmezadri/htchat-server/wp.StartWhatsApp
	/home/junior/go/src/github.com/Valdenirmezadri/htchat-server/wp/start.go:7 +0x52
exit status 2
make: *** [Makefile:2: run] Error 1

**Comment by codenoid** [comment]
update your github.com/Rhymen/go-whatsapp version

**Comment by SchulteMK** [comment]
Did the update resolve the issue?

**Comment by Valdenirmezadri** [comment]
i'm going to merge the master version

**Comment by Valdenirmezadri** [comment]
I believe it is now working

error occoured: error processing data: can't handle binary data when not logged in
