### ISSUE TITLE
Listener is not removed from the map on invalid message

### ISSUE THREAD

**Issue by kaxap** [Rhymen/go-whatsapp#177]
https://github.com/Rhymen/go-whatsapp/blob/c872073bc20e96d3a29f04063efc8f6b6b4b734e/read.go#L59

There can be a message with len(data) == 2 and len(data[1]) == 0 which has a listener in `wac.listener.m`. So when this happens the processReadData will return ErrInvalidWsData error and leave the listener in the map. Shouldn't it remove the listener from the map before returning the error?

**Comment by SchulteMK** [comment]
I share your opinion that the listener should be removed if one exists, because the listener would never been served and it would produce a small memory leak. I am not at my workstation for the next week, can you please make a PR?

**Comment by houstondapaz** [comment]
I opened #180 because the implementation was breaking queries
