### ISSUE TITLE
GetPushName 

### ISSUE THREAD

**Issue by jhow2892** [Rhymen/go-whatsapp#18]
Hello, is it possible to get the PushName of the contact?

**Comment by Rhymen** [comment]
This function is not yet implemented into the api. Whatsapp sends a contacts message immediatly after the connection was established. We would need to store all contacts and then provide a function to search them.

**Comment by Rhymen** [comment]
You can now get the contact from `wac.Store.Contacts[jid]`. The function, that retrieve the updated contacts from the server is already implemented, but it does not update the contacts in the store yet.

**Comment by jhow2892** [comment]
Ola, perfect worked perfectly.
