### ISSUE TITLE
After login I receive 401 error

### ISSUE THREAD

**Issue by modcastro** [Rhymen/go-whatsapp#183]
After Sync QR Code and try send or receive message I see this:

2019/06/29 10:46:24 error logging in: restoring failed: admin login responded with 401

Thanks any help

**Comment by houstondapaz** [comment]
Hi @modcastro , this error is because the session was in closed aon celphone

**Comment by modcastro** [comment]
@houstondapaz Thanks, brother!

**Comment by codenoid** [comment]
is this issue has been solved ? would you close this issue

by the way, i use login retry (3 times) to ensure the account was disconnected/logged out/banned
