### ISSUE TITLE
In Phone App Crash

### ISSUE THREAD

**Issue by AbyssEkko** [Rhymen/go-whatsapp#184]
After sending some messages the app in the phone will crash and then everytime i open it will instantly crash. This happened with two different phones. After this messages wont be send. Any clues on what could be causing this issue?

**Comment by codenoid** [comment]
1. are you using latest Rhymen/go-whatsapp/issues version/commit ?
2. show your sendMsg real code (with exact number format & message)

**Comment by AbyssEkko** [comment]
1- Im on last commit 
2- Something that might be relevant is that everytime a message is sent the following error appears 
> error sending message: sending message timed outexit status 1
this is when running the sendTextMessages with the following parameters:
`	msg := whatsapp.TextMessage{
		Info: whatsapp.MessageInfo{
			RemoteJid: "59895024350@s.whatsapp.net",
		},
		Text: "Message sent by github.com/Rhymen/go-whatsapp",
	}`
3- As for the code im running I have clients that fill in complaints so I update them. I therefore check on my mysql database and pick up the messages that havent been sent. The flow is of 1 message a minute at most. This is the code:
`for {
		var pedidos_env = [][3]string{{}}
		var pedidos_id = pedidos_id[:0]
		pedidos_env = cargar_pedidos_wpp(pedidos_env)
		var direccion = ""
		for i := 1; i < len(pedidos_env); i++ {
			direccion = fmt.Sprintf("%s@s.whatsapp.net",pedidos_env[i][1])
			msg := whatsapp.TextMessage{
			Info: whatsapp.MessageInfo{
				RemoteJid: direccion,
			},
			Text: pedidos_env[i][2],
			}
		
			msgId, err := wac.Send(msg)
			if (err != nil) {
				fmt.Errorf("error mensaje: %v\n", err)
			} else {
				fmt.Println("Message Sent -> ID : "+msgId)
			}
		
			pedidos_id = append(pedidos_id, pedidos_env[i][0])
			<-time.After(3 * time.Second)
		}

		if (len(pedidos_id) > 0) {
			borrar_pedidos_wpp(pedidos_id)
		} 
		//fmt.Print(pedidos_env)
		
		<-time.After(15 * time.Second)
		
	}`
All the numbers i send messages to have the same local prefix "598" and the grand majority throw off an error every time i send one however they are all sent, simillar to what happens with sendTextMesagges

**Comment by codenoid** [comment]
have you try to send message to somewhere with different local prefix / country code ?

**Comment by iileandro** [comment]
I face this issue when I put wrong number format or Mal formed request

Em qua, 3 de jul de 2019 12:16, Jägermeister <notifications@github.com>
escreveu:

**Comment by AbyssEkko** [comment]
I´ve tried sending a message to a number in panama but same error message appeared. Message was sent as it was when i sent it to a number in my country. I dont think is a wrong formed request either as im copying/using same code as sendTextMessages example

**Comment by codenoid** [comment]
i have no idea about that, maybe try to update your whatsapp phone app, debug the input to go-whatsapp (%s -> %v) (and because my go-whatsapp still working fine), by the way about the `timed out` message, i just ignore that, my message still successfully send

**Comment by AbyssEkko** [comment]
I mean the code on the side of ryhmen works just fine, after the app in the phone crashes i can open it and before it instatly crashes i can see newer messages piling up but with the symbol awaiting for connection. However they are never send.

**Comment by AbyssEkko** [comment]
I thought maybe i should just disconnect and reconnect between messages but > Reconnect(); < wont work.

**Comment by iileandro** [comment]
Here in Brazil we have some peculiarities to regional numbers. I need to
remove a digit depending of the target code area. Just because phone system
has added a nineth digit but WhatsApp didn't updated it. So I think that if
we send to another countries, we have this kind of risks. Maybe it's what
is happening to you.



Em qua, 3 de jul de 2019 12:42, AbyssEkko <notifications@github.com>
escreveu:

**Comment by AbyssEkko** [comment]
Here in Uruguay all codes are the same, now i think errors might be related to special characters such as accent or slashes. I got this idea from #152 , I´ll update if it works later.

**Comment by AbyssEkko** [comment]
Errors in console where for special character but what caused the app to crash was that i was using normal whatsapp instead of business. At least for now it is all working.

**Comment by AbyssEkko** [comment]
At the end it didnt fix anything.

**Comment by gonzariosm** [comment]
I have the same problem, any solution for this problem?
