### ISSUE TITLE
Reload Chat litst

### ISSUE THREAD

**Issue by mczarnobai** [Rhymen/go-whatsapp#188]
How can I reload chat list when I receive a message? The chat list is reloading just on login.

**Comment by kaxap** [comment]
What do you mean by 'reload'? Resend all the initial messages again? And why do you need this exactly?

**Comment by mczarnobai** [comment]
When I get a message, I want to sort chat list, the contact with de last message needs to be on "Top" in my user interface list.

I did this manually, with a look up table. One with contacts(phone number and name), and other with messages (phone number and message). 

It is working, but I did not find a way to do this with something like "ReloadChats()"

**Comment by kaxap** [comment]
Yes, you have to manage this manually.
