### ISSUE TITLE
Debugging Binary Data

### ISSUE THREAD

**Issue by orangehaired** [Rhymen/go-whatsapp#189]
Hi @Rhymen, @houstondapaz, @kaxap =)

How do you debug binary data?

I can read json from websocket, but I can't read binary data. I'm the grpc developer an i'm very good on protobuffer. 

For example ban request data: 
<img width="682" alt="Screen Shot 2019-07-08 at 22 21 38" src="https://user-images.githubusercontent.com/48999813/60837643-52bf0d00-a1d1-11e9-9123-dda07b7f2795.png">

<img width="1478" alt="Screen Shot 2019-07-08 at 22 23 08" src="https://user-images.githubusercontent.com/48999813/60837661-61a5bf80-a1d1-11e9-8da9-277de337c13e.png">

Thank u so much for project =)

**Comment by kaxap** [comment]
Hi @orangehaired,

Please refer to decryptBinaryMessage function in read.go https://github.com/Rhymen/go-whatsapp/blob/4c0e263c801b8b5bd7fad1577786ab6c32c2c042/read.go#L98

**Comment by orangehaired** [comment]
> Hi @orangehaired,
> 
> Please refer to decryptBinaryMessage function in read.go
> 
> https://github.com/Rhymen/go-whatsapp/blob/4c0e263c801b8b5bd7fad1577786ab6c32c2c042/read.go#L98

Hi =) 

This websocket datas.

<img width="925" alt="Screen Shot 2019-07-23 at 16 46 51" src="https://user-images.githubusercontent.com/48999813/61718768-4b206c00-ad6c-11e9-843a-e6623fb4e4ec.png">

I have a custom(web side) decrypt func but returned "invalid hmac" error.  Why? I'm sure this datas signed with this key (provided whatsapp web).

<img width="1675" alt="Screen Shot 2019-07-23 at 16 45 21" src="https://user-images.githubusercontent.com/48999813/61718863-75722980-ad6c-11e9-8520-cf2135583a77.png">

I used the mac and enc keys that whatsapp web provides.

<img width="399" alt="Screen Shot 2019-07-23 at 16 44 46" src="https://user-images.githubusercontent.com/48999813/61719073-e9143680-ad6c-11e9-9390-bcefe55e9698.png">

**Comment by 0xhex** [comment]
How can i decrypt this?
3438 382E 2D2D 3331 2C07 80B0 6C18 1D41 5753 2F90 3983 04CF 585C D751 693B CC76 3A2E 3D1C 2056 3D64 741A A0AA FC0A 07D9 8C45 3A0A 389F FE25 61AC 6E04 E750 F179 3776 42A3 E9FA B24E 3B09 C250 C9FC 3627 6169 EEE1 A008 9F53 4D10 B5AC 7ACD F31E C0D7 2F4E 28A8 CFBB D2A7 8EE9 FFA6 4C0E BB75 9E43 6B2A C92C E8BE E1


I Tried this but not working
```
	msg, err := wac.decryptBinaryMessage([]byte("3438 382E 2D2D 3331 2C07 80B0 6C18 1D41 5753 2F90 3983 04CF 585C D751 693B CC76 3A2E 3D1C 2056 3D64 741A A0AA FC0A 07D9 8C45 3A0A 389F FE25 61AC 6E04 E750 F179 3776 42A3 E9FA B24E 3B09 C250 C9FC 3627 6169 EEE1 A008 9F53 4D10 B5AC 7ACD F31E C0D7 2F4E 28A8 CFBB D2A7 8EE9 FFA6 4C0E BB75 9E43 6B2A C92C E8BE E1"))
	if err != nil {
		return nil, err
	}
```

**Comment by kaxap** [comment]
It should be 
```go
msg, err := wac.decryptBinaryMessage([]byte{0x34, 0x38, 0x38, 0x2E, 0x2D, 0x2D, 0x33,...})
```

**Comment by beshoo** [comment]
@0xhex @kaxap
how can we use **decryptBinaryMessage** while we are using the chorme?
I want to decode the chrome outgoing/ incoming messages, Is there a way? since I believe we need te token key!

**Comment by kaxap** [comment]
@beshoo 
just place appropriate break points in JS code, where encrypted messages are already decoded and deserialized.

**Comment by beshoo** [comment]
Please can you show me an example

**Comment by beshoo** [comment]
Please note i want to see the sent and received message.

**Comment by shekohex** [comment]
I'm not using that lib, but I keep an eye on it because I have mine but it is written in Rust instead.
I have a one rust binary for analyzing the packets between Whatsapp web and Whatsapp server.
and I'll share it with you all:

```rust
use crate::settings::Settings;
use anyhow::Result;
use dialoguer::{theme::ColorfulTheme, Confirmation, Input};
use libwa::internal::{verify_and_decrypt_message, Node, NodeContent};
use waproto::{ProstMessage, WebMessageInfo};
mod settings;
fn main() -> Result<()> {
    println!("Loading Settings form ./config/packet-analyzer.toml ..");
    let settings = Settings::new()?;
    let enc = base64::decode(&settings.secrets.enc)?;
    let mac = base64::decode(&settings.secrets.mac)?;
    let theme = ColorfulTheme::default();
    loop {
        let packet = Input::<String>::new()
            .with_prompt("Enter the Packet (in base64)")
            .interact()?;
        let message = base64::decode(&packet)?;
        let sent = Confirmation::with_theme(&theme)
            .with_text("is this a sent packet ?")
            .default(true)
            .show_default(true)
            .interact()?;
        let pad = if sent {
            3 // these there bytes for the [metric, b',', flag]
        } else {
            1 // one for the , it self
        };
        let sep = message
            .iter()
            .position(|x| x == &b',')
            .expect("we should have the `,` separator!")
            + pad;
        let message_tag = std::str::from_utf8(&message[..(sep - pad)])?;
        println!("Message Tag: {}", message_tag);
        let message =
            verify_and_decrypt_message(&enc[..], &mac[..], &message[sep..])?;
        let payload = Node::deserialize(&message)?;
        if let NodeContent::List(nodes) = &payload.content {
            for node in nodes {
                match node.desc.as_ref() {
                    "message" => {
                        handle_message(&node.content)?;
                    },
                    unknown => {
                        eprintln!("got unhandled node of desc: {}", unknown);
                        println!("{:#?}", payload);
                    },
                }
            }
        } else {
            println!("{:#?}", payload);
        }
    }
}

fn handle_message(content: &NodeContent) -> Result<()> {
    if let NodeContent::Binary(ref content) = content {
        let msg = WebMessageInfo::decode(content.as_slice())?;
        println!("{:#?}", msg);
    }
    Ok(())
}
```

Some Notes:
1. Settings: is just a struct to hold the `mac` key and `enc` key, these keys you should find them stored somewhere in the browser (PS: see Application Tab in devtools)
2. I'm using a dialoguer package to make it interactive while debugging.
3. `verify_and_decrypt_message` function is the same as `decryptBinaryMessage` but my code is very decoupled, so I have pure functions that work without depending on Whatsapp session.
4. `WebMessageInfo` generated from the proto file.

**Comment by Ased2235** [comment]
> It should be
> 
> ```go
> msg, err := wac.decryptBinaryMessage([]byte{0x34, 0x38, 0x38, 0x2E, 0x2D, 0x2D, 0x33,...})
> ```

Can you tell me how get that from binary?

**Comment by shekohex** [comment]
Hey all I made a tool to help with that here https://github.com/shekohex/wadump
