### ISSUE TITLE
MessageInfo.Status doesn't work correctly

### ISSUE THREAD

**Issue by brualan** [Rhymen/go-whatsapp#195]
All messages received from other accounts via `HandleTextMessage()` have the error status, regardless of their actual status. However, messages in which `FromMe = true` receive the correct status (read, delivered, etc.)

**Comment by codenoid** [comment]
i use latest `github.com/Rhymen/go-whatsapp/` and latest WhatsApp app from playstore, working fine

**Comment by jackesdavid** [comment]
Do you was able to see why the status is incorrect when receiving?
Thanks in advance!

**Comment by jackesdavid** [comment]
HI @codenoid , I'm always receiving status ERROR (0)  in some messages from remoteJids , I'm using the latest version.

**Comment by ftomza** [comment]
On the latest version, all messages not from the owner have the Error(0) status. How do I get the status of a message?

**Comment by brualan** [comment]
Actually, I'm stopped using this project. And because nobody else experienced same issue, I'm considering that this issue should be closed.

**Comment by ftomza** [comment]
> Actually, I'm stopped using this project. And because nobody else experienced same issue, I'm considering that this issue should be closed.

Are there any alternatives to this project?

**Comment by brualan** [comment]
@ftomza I stopped using WhatsApp all together. I don't know if where are projects that has similar functionality
