### ISSUE TITLE
MessageStatus changed

### ISSUE THREAD

**Issue by Deewai** [Rhymen/go-whatsapp#196]
I believe the MessageStatus numbers have changed. I receive an 'ack' of 2 when a message is delivered and 3 when a message is read. Please confirm this

**Comment by houstondapaz** [comment]
The status returned by "ack" or "acks" is different
`
/** 
* 	ServerAck    = 3
* 	DeliveryAck  = 4
* 	Read         = 5
**/

**Comment by Deewai** [comment]
> ServerAck    = 1
> DeliveryAck  = 2
> Read         = 3

This ius correct but the message status in the code is 
`const (
	Error       MessageStatus = 0
	Pending                   = 1
	ServerAck                 = 2
	DeliveryAck               = 3
	Read                      = 4
	Played                    = 5
)`

**Comment by Deewai** [comment]
Do you mean the message status that comes with a message in the message handler is different from the one that comes with "ack"?

**Comment by houstondapaz** [comment]
Yes

**Comment by Deewai** [comment]
okay, thank you

**Comment by tarikhagustia** [comment]
hi @Deewai how to get Message ACK?
