### ISSUE TITLE
Decrypt Binary Data

### ISSUE THREAD

**Issue by orangehaired** [Rhymen/go-whatsapp#197]
Hi =) 

This websocket data.

<img width="925" alt="Screen Shot 2019-07-23 at 16 46 51" src="https://user-images.githubusercontent.com/48999813/61718768-4b206c00-ad6c-11e9-843a-e6623fb4e4ec.png">

I have a custom(web side) decrypt func but returned "invalid hmac" error.  Why? I'm sure this datas signed with this key (provided whatsapp web).

<img width="1675" alt="Screen Shot 2019-07-23 at 16 45 21" src="https://user-images.githubusercontent.com/48999813/61718863-75722980-ad6c-11e9-8520-cf2135583a77.png">

I used the mac and enc keys that whatsapp web provides.

<img width="399" alt="Screen Shot 2019-07-23 at 16 44 46" src="https://user-images.githubusercontent.com/48999813/61719073-e9143680-ad6c-11e9-9390-bcefe55e9698.png">

**Comment by orangehaired** [comment]
UPDATE: It works for incoming messages but can't decrypt for outgoing (as pictured above). 

I was tried --> https://github.com/shekohex/whatsappweb-rs/blob/master/src/crypto.rs#L192

**Comment by rhsobr** [comment]
Hey @orangehaired , have you reached the solution?
I'm facing same problem here.

**Comment by shekohex** [comment]
Hey all I made a tool to help with that here https://github.com/shekohex/wadump
