### ISSUE TITLE
Message sent successfully, return error.

### ISSUE THREAD

**Issue by Romerito007** [Rhymen/go-whatsapp#20]
error sending message: error decoding sending response: unexpected end of JSON input
Problem only occurs with Mac OS X, would you have an idea why this happens?
I'm not an expert on GO.
It started after the last commit.

**Comment by Rhymen** [comment]
Hey Romerito,

after sending a message, whatsapp responds with an empty message. We tried to decode these empty messages to json, hence the "unexpected end of JSON input" error. As we are filtering these kinds of messages now, the error should not appear anymore.

**Comment by Romerito007** [comment]
OK thank you. Congratulations on the work.
