### ISSUE TITLE
Example get battery status!

### ISSUE THREAD

**Issue by Romerito007** [Rhymen/go-whatsapp#201]
Someone could implement battery status,
I am new to golang. I do not know if this best way to implement!

https://github.com/Rhymen/go-whatsapp/blob/fcfd0abb9aa917ec702b30cda6794acc3f964273/handler.go#L328

{"Description":"action","Attributes":null,"Content":[{"Description":"battery","Attributes":{"live":"false","powersave":"false","value":"57"},"Content":null}]}

```
if con, ok := message.Content.([]interface{}); ok {
	for a := range con {
		if v, ok := con[a].(*proto.WebMessageInfo); ok {
				wac.handle(v)
				wac.handle(ParseProtoMessage(v))
			}
		}
	} else if con, ok := message.Content.([]binary.Node); ok {
		if con[a].Description == "battery" {
			// Implement handlers status battery wac.handle()
		}
        }
}
```

**Comment by codenoid** [comment]
i don't know what "battery status" mean, but : 

```
wac, err := whatsapp.NewConn(5 * time.Second)
wac.info.Battery # percentage of battery
wac.info.Plugged # is charging or not
```

**Comment by Romerito007** [comment]
I'm sorry battery percentage!
The percentage is sent every 2 minutes, I need to enable and disable device charging, send a notification via webhook.
Solved using the handler! Thank you very much. I will close this topic!

**Comment by sthales** [comment]
Same issue here. @krombel why don't you share your solution?
