### ISSUE TITLE
admin login responded with 403

### ISSUE THREAD

**Issue by sandeepmeenuga** [Rhymen/go-whatsapp#205]
admin login responded with 403.

**Comment by SchulteMK** [comment]
Please provide additional information, like logs or your actual code. Probably you are using invalid tokens to restore your session. 

Reopen if needed with additional information

**Comment by tguimmaraess** [comment]
> Please provide additional information, like logs or your actual code. Probably you are using invalid tokens to restore your session.
> 
> Reopen if needed with additional information

I'm getting the same error, could you tell me how do I use these tokens?
