### ISSUE TITLE
keepAlive fail

### ISSUE THREAD

**Issue by Deewai** [Rhymen/go-whatsapp#211]
when go-whatsapp loses connection to the internet, keepAlive fails, which is normal but upon gaining connection back subsequent keepAlive requests still fail even after a wac.Restore() has been made.

**Comment by jackesdavid** [comment]
You need to recover the sassion like WhtasApp web does.... I'm afraid that there is no built-in functionality to start a new session again, you need to do this by yourself....

The `con.AdminTest()`method can help you to check if your already created session is connected or not...
