### ISSUE TITLE
Keep running

### ISSUE THREAD

**Issue by b4-io** [Rhymen/go-whatsapp#212]
Hello,
I was wondering whats the correct way to keep de program running without stopping. I want to send messages when a request to send one is filled but i cant seem to keep the program running continuously, ir un disconnect and connect every 1 minute but the connect fails shortly after.
Therefore id be glad i anyone can iluminate me on how to keep it running. Also once its starts to fail the next time i run it it will fail even earlier.

**Comment by hrizal** [comment]
run as a service

**Comment by AbyssEkko** [comment]
Do you have a link where i can find information about that? Just to be sure im doing the correct thing
