### ISSUE TITLE
"Empty" images until download

### ISSUE THREAD

**Issue by sthales** [Rhymen/go-whatsapp#214]
Hey guys, when I send an image it appears "empty" in the app until the user download it. Does anyone know how can I fix this?

```
content := whatsapp.ImageMessage{
			Info: whatsapp.MessageInfo{
				RemoteJid: jidDest + jidPrefix,
			},
			Content: msgImageStream,
			Type:    msgImageType,
			Caption: msgCaption,
		}
```

<img src="https://user-images.githubusercontent.com/31826331/62874319-68a37e80-bcf7-11e9-9e63-d2a9bc875a52.png" width="300" height="auto"/>

**Comment by SchulteMK** [comment]
You have to fill the thumbnail field of the ImageMessage

**Comment by sthales** [comment]
Oh, now it works. Thanks
