### ISSUE TITLE
AdminTest undefine

### ISSUE THREAD

**Issue by hrizal** [Rhymen/go-whatsapp#221]
when run the first time, there is no error, but after running the second time the message appears.
I saw in conn.go, there is a method (AdminTest)

./main.go:77:18: wac.AdminTest undefined (type *whatsapp.Conn has no field or method AdminTest)

**Comment by codenoid** [comment]
update your github.com/Rhymen/go-whatsapp

**Comment by hrizal** [comment]
already update, 
but it solve ...

1st try i am using non root user
2nd try i am using root user

back to non root user, its work smoothly :)

**Comment by codenoid** [comment]
because your GOPATH will different/undefined when using root user
