### ISSUE TITLE
How are the chats deleted?

### ISSUE THREAD

**Issue by alejandroguille** [Rhymen/go-whatsapp#222]
I was investigating and did not find how the chats are deleted, does anyone know how?

**Comment by RafaelIngenium** [comment]
> I was investigating and did not find how the chats are deleted, does anyone know how?


I have the same demand for development. Someone to help us?

**Comment by RafaelIngenium** [comment]
Mais um com esta demanda de desenvolvimento

**Comment by gabstv** [comment]
There is a hacky way of doing it: #100
