### ISSUE TITLE
Not able to send messages.

### ISSUE THREAD

**Issue by bamjohn2222** [Rhymen/go-whatsapp#224]
I am a completed newbie to golang.

I went into the examples\login folder and ran the command to run
go run main.go
I got the QR code I scanned and the session was started.

After that I went into the examples\sendTextMessages, I edited the main.go file and replaced the number to an actual/real number ran the command as
go run main.go
But I get the error as

> error logging in: restoring failed: admin login responded with 401

Am I doing anything wrong? Because as a newbie I couldn't able to understand much from the readme.md

**Comment by hrizal** [comment]
make sure start with country code without + or zero in front following with mobile number.
test with https://wa.me/<country code+mobile number>

**Comment by bamjohn2222** [comment]
Superb. I did a mistake and added a 0 before the country code. Now it is solved. Thanks.
