### ISSUE TITLE
SubscribePresence() not working for all contacts

### ISSUE THREAD

**Issue by jointfull** [Rhymen/go-whatsapp#23]
I've been trying to investigate this issue for a while now, and I can't figure it out. Maybe you can find a solution for this issue...
I have 3 devices: **A**, **B** and **C**.
I have connected the go-whatsapp to device **A**, and in it i called SubscribePresence() for both **B** and **C**.
However, I only get presence updates for **B**, and no updates at all for **C**.
Moreover, if I turn the screen on the mobile **A** on and go into the chat with **C** (seeing the "Last seen" at the top) - from that point I start getting presence updates for **C** on go-whatsapp.
I suspect that SubscribePresence() is not enough for getting a device's presence updates and maybe another thing should be called to make it happen.. something that the actual WhatsApp application calls or that the actual WhatsApp Web calls and is missing here in go-whatsapp.
As a lead, I think that only when we get the "Last seen" working, it will finally be solved..
Another lead, C was never saved as a contact on device **A** (that means that I see its number in the chat list).
(**B** was once saved as a contact on device **A** but in order to check if having a device saved as a contact is necessary for the presence updates, I deleted **B** from device **A**.. and it still works)
I will appreciate your help.
Thanks.

**Comment by munknex** [comment]
@jointfull Any news?

**Comment by Rhymen** [comment]
Hey jointful,
as I only have one mobile phone on me currently, I cannot reproduce this issue . I guess that you maybe can only subscribe to the presence of one jid. Do you stop getting presence messages from B after you turn on phone A and open chat C? That would be a clue.

You could be reading your channels wrong aswell, so maybe check out this example or post your code.
```
chA, err := wac.SubscribePresence("")
if err != nil {
	fmt.Fprintf(os.Stderr, "error subscribing to presence of chat a: %v\n", err)
}

chB, err := wac.SubscribePresence("")
if err != nil {
	fmt.Fprintf(os.Stderr, "error subscribing to presence of chat b: %v\n", err)
}

for {
	select {
	case p := <-chA:
		fmt.Printf("presence message from chat a: %v\n", p)
	case p := <-chB:
		fmt.Printf("presence message from chat b: %v\n", p)
	}
}
```

**Comment by jointfull** [comment]
Hi Rhymen,
I'm not at work today, but here are the answers to your clarification questions:

1. **B** and **C** have no relation/interference between them. I even tried (in code) to subscribe just to **B**.. just to **C**.. and to both (one time subscribing to **B** before **C** and another time trying to subscribe to **C** before **B**). I even tried setting a 1 second sleep between the two. I even tried subscribing to 3 contacts at once (having the problematic **C** being first/not first..). All above attempts failed to produce any presence updates for **C**.
2. When I subscribe to **B**, and **C**, I get the same status of: "200, OK" (if I remember correctly, I'm not at work, but I definitely remember they had the same response status).
3. When I turn the screen of phone **A** on and go into contact **C**.. the presence updates of **B** continue seamlessly, like they did before I turned the screen of phone **A**.
4. I saw that I only get the presence updates in Go for **C**, once the "Last seen" of contact **C** was presented on phone **A** chat with **C**.

Again.. thanks for the assistance..

**Comment by mertxkaan** [comment]
@jointfull @munknex
If I remember the right date, as of 1.May, Whatsapp changed their code and after that they don't allow you to see online status of the people: 
_(**1**) who don't have you in their contact list,_  
_(**2**) who you didn't chat before,_

If you open the mobile app and click on any contact, you get status updates aproximately _~10mins_ for that contact and then darkness again:)

The contacts in your chat list automatically takes the updates, for the rest you must subscribe (_again who have you in their ContactList_). I don't know if anybody solve this issue until now.

(If my knowledge is incorrect, please let me know)

Thanks

**Comment by hiwaleakshay** [comment]
@jointfull @Rhymen  @mertxkaan  any solution on this? i have reproduced the same issue. 
I can receive presence update for the contacts that i have chat with. (as long as whatsapp is connected to internet on my phone) but not for other contacts in my phone. even if i subscribed them using 
`wac.SubscribePresence("wa_contact@c.us")`

**Comment by 0xhex** [comment]
if anyone solved this issue contact me [PAID job]
efekanpulatli@gmail.com
