### ISSUE TITLE
Read After Send Message

### ISSUE THREAD

**Issue by crisnamurti** [Rhymen/go-whatsapp#230]
When i read after send a message an error occur.

2019/10/02 13:58:16 error occoured: error processing data: received invalid data

**Comment by codenoid** [comment]
but is that matter ?, what do u mean by "read" ?

**Comment by crisnamurti** [comment]
My software listen all messages received by whatsapp and save in a database, and sometimes the software sends message too.
When it send a message the listen channel can't read this message, i need restart the application for this.

**Comment by codenoid** [comment]
totally you can do that, just need buffered channel like [this](https://github.com/Rhymen/go-whatsapp/blob/fc3f792c814c93c512895468a8b7617249b78d59/examples/receiveMessages/main.go#L94) 

or sending a message inside a forever loop (if there is message to send)

**Comment by crisnamurti** [comment]
Ok Thanks.
