### ISSUE TITLE
Send Audio

### ISSUE THREAD

**Issue by wilifabrizio** [Rhymen/go-whatsapp#24]
How to send an audio? what is the mimetype? and else..

**Comment by SchulteMK** [comment]
Sending an audio is basicly the same as sending an image. The sending of an image is provided [here](https://github.com/Rhymen/go-whatsapp/tree/master/examples/sendImage). The AudioMessage is structured like this: 
```
type AudioMessage struct {
	Info          MessageInfo
	Length        uint32
	Type          string
	Content       io.Reader
	url           string
	mediaKey      []byte
	fileEncSha256 []byte
	fileSha256    []byte
	fileLength    uint64
}
```
you have to only fill the exported fields (beginning with an capital letter). Define the receipient in the Info field as RemoteJid. The Length is the length of the audio file in seconds. Type describes the mimetype, which is the actual type of the file. For images it is often `image/jpeg` and for audios sent by whatsapp is `audio/ogg; codecs=opus`. I do not know if whatsapp supports sending audio files in other formats. But you can send every kind of file with the help of `DocumentMessage`. The only downside is, that it appears as an sent audio file and not as an spoken one. Finally you have to provide an `io.Reader` to the media struct, to provide the actual data. The easiest way is to use `os.Open(filePath)` to open a file and get a `*File`, which implements `io.Reader` already.

**Comment by sthales** [comment]
#219
