### ISSUE TITLE
This is not An issue , but i like some help

### ISSUE THREAD

**Issue by victormedranop** [Rhymen/go-whatsapp#244]
I become from java and php, and have this amazing solution. but i have two diferente session from sending and receiving messages. i'm still learning Go. is there a way to reuse the wac connection for do both thing, sending and receiving?

thanks.

Victor

**Comment by jackesdavid** [comment]
There is no reason to have two sessions to send and receive...

**Comment by jackesdavid** [comment]
This is two-way communication why do you need two sessions?
Do you want to receive from one line and send by another?

**Comment by jackesdavid** [comment]
I think you can close this issue e request some help on PM messages

**Comment by gabstv** [comment]
It's problematic to have two (or more) simultaneous sessions for the same ID. The `web.whatsapp` protocol expects only one session at a time. The webapp notifies you if you're running multiple sessions (and prevents you from doing so) for a reason.

**Comment by victormedranop** [comment]
Done, learning more GOLANG !!!!!!!
