### ISSUE TITLE
error downloading media

### ISSUE THREAD

**Issue by codenoid** [Rhymen/go-whatsapp#248]
error from `message.Download()` : `no url present`

**Comment by houstondapaz** [comment]
On messages send from connected phone, we receive 2 or 3 messages and the first doesn't has the url, but second or the third yes

**Comment by Valdenirmezadri** [comment]
Hello, im having the same problem

**Comment by meinto** [comment]
```go
if bytes, err := message.Download(); err == nil {
  // do your stuff
}
```
