### ISSUE TITLE
can't receive reply chats

### ISSUE THREAD

**Issue by xnodcorp** [Rhymen/go-whatsapp#25]
why can't receive reply chats?

**Comment by SchulteMK** [comment]
What do you mean with reply chats? Do you mean messages that are direct replies of other messages or something else?

**Comment by tkovs** [comment]
@xnodcorp is talking about this

![image](https://user-images.githubusercontent.com/8717661/44206522-7fd57d80-a130-11e8-90ef-6f8c0def1405.png)

I verified. The handler example doesn't receive this replies.

**Comment by SchulteMK** [comment]
A default text message gets represented as a `Conversation` in the protobuf definitions. A "reply chat" or "message quote" is represented as an `ExtendedTextMessage` which are not currently implemented right now. We still have to determine the best way of implementing these quoted messages, but I think it is doable in the next few days
