### ISSUE TITLE
How to send image/video thumb

### ISSUE THREAD

**Issue by tgssb** [Rhymen/go-whatsapp#253]
Images and videos don't have a thumb 
![whatsappthumb](https://user-images.githubusercontent.com/28009905/69606024-76f47c80-1000-11ea-87b7-8ce1781c6b39.jpeg)

Any solution?

**Comment by sthales** [comment]
I'm using [ /disintegration/imaging](/disintegration/imaging) for generating thumbnails. Then you have to fill the thumbnail field in imageMessage. (#214)

Try something like this:
```
func getThumbnail(image io.Reader) ([]byte, error) {

	img, _, err := image.Decode(image)
	if err != nil {
		return nil, err
	}

	b := img.Bounds()
	imgWidth := b.Max.X
	imgHeight := b.Max.Y

	thumbWidth := 100
	thumbHeight := 100

	if imgWidth > imgHeight {
		thumbHeight = 56
	} else if imgHeight > thumbWidth {
		thumbWidth = 56
	}

	thumb := imaging.Thumbnail(img, thumbWidth, thumbHeight, imaging.CatmullRom)

	buf := new(bytes.Buffer)
	err = jpeg.Encode(buf, thumb, nil)
	if err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

```

**Comment by Ased2235** [comment]
> I'm using [ /disintegration/imaging](/disintegration/imaging) for generating thumbnails. Then you have to fill the thumbnail field in imageMessage. (#214)
> 
> Try something like this:
> 
> ```
> func getThumbnail(image io.Reader) ([]byte, error) {
> 	img, _, err := image.Decode(image)
> 	if err != nil {
> 		return nil, err
> 	}
> 
> 	b := img.Bounds()
> 	imgWidth := b.Max.X
> 	imgHeight := b.Max.Y
> 
> 	thumbWidth := 100
> 	thumbHeight := 100
> 
> 	if imgWidth > imgHeight {
> 		thumbHeight = 56
> 	} else {
> 		thumbWidth = 56
> 	}
> 
> 	thumb := imaging.Thumbnail(img, thumbWidth, thumbHeight, imaging.CatmullRom)
> 
> 	buf := new(bytes.Buffer)
> 	err = jpeg.Encode(buf, thumb, nil)
> 	if err != nil {
> 		return nil, err
> 	}
> 
> 	return buf.Bytes(), nil
> }
> ```
> 
> //
> 
> ```
> thumb, err := getThumbnail(bytes.NewReader(image))
> if err != nil {
>         fmt.Println(err.Error())
> 	return 
> }
> 
> imageMessage := whatsapp.ImageMessage{
> 	Info:        messageInfo,
> 	ContextInfo: contextInfo,
> 	Content:     content,
> 	Type:        message.Type,
> 	Caption:     message.Caption,
> 	Thumbnail:   thumb,
> }
> ```

Great example, I was generating thumbs from same as original image

**Comment by tgssb** [comment]
> I'm using [ /disintegration/imaging](/disintegration/imaging) for generating thumbnails. Then you have to fill the thumbnail field in imageMessage. (#214)
> 
> Try something like this:
> 
> ```
> func getThumbnail(image io.Reader) ([]byte, error) {
> 	img, _, err := image.Decode(image)
> 	if err != nil {
> 		return nil, err
> 	}
> 
> 	b := img.Bounds()
> 	imgWidth := b.Max.X
> 	imgHeight := b.Max.Y
> 
> 	thumbWidth := 100
> 	thumbHeight := 100
> 
> 	if imgWidth > imgHeight {
> 		thumbHeight = 56
> 	} else {
> 		thumbWidth = 56
> 	}
> 
> 	thumb := imaging.Thumbnail(img, thumbWidth, thumbHeight, imaging.CatmullRom)
> 
> 	buf := new(bytes.Buffer)
> 	err = jpeg.Encode(buf, thumb, nil)
> 	if err != nil {
> 		return nil, err
> 	}
> 
> 	return buf.Bytes(), nil
> }
> ```
> 
> //
> 
> ```
> thumb, err := getThumbnail(bytes.NewReader(image))
> if err != nil {
>         fmt.Println(err.Error())
> 	return 
> }
> 
> imageMessage := whatsapp.ImageMessage{
> 	Info:        messageInfo,
> 	ContextInfo: contextInfo,
> 	Content:     content,
> 	Type:        message.Type,
> 	Caption:     message.Caption,
> 	Thumbnail:   thumb,
> }
> ```

Thank you, solved my problem!
As i say in Brazil, tamo junto!

**Comment by sthales** [comment]
> As i say in Brazil, tamo junto!

"Tamo junto!" 👊🏼

**Comment by victorstsw** [comment]
does not work!

**Comment by dhruv-shipmnts** [comment]
What about videos?
