### ISSUE TITLE
Get message Info by ID

### ISSUE THREAD

**Issue by Ased2235** [Rhymen/go-whatsapp#255]
Hello, Idk if it's possible or not but is there anyway to get message info by id? i'm trying to reply to my own audio message after sending it.

Thank!

**Comment by jackesdavid** [comment]
Are trying to quote you own message ?

**Comment by Ased2235** [comment]
> Are trying to quote you own message ?

Yes

**Comment by houstondapaz** [comment]
I use the LoadMessagesBefore mehtod until find the specific message

**Comment by Ased2235** [comment]
> I use the LoadMessagesBefore mehtod until find the specific message

Can you please give me an example code?

**Comment by houstondapaz** [comment]
like this
```go
func (wa *waHandler) getMessage(number int64, messageID string) (*proto.WebMessageInfo, error) {
	jid := fmt.Sprintf("%d@s.whatsapp.net", number)

	beforeMsg := ""
	beforeMsgIsOwner := true

	for {
		response, err := wa.connection.LoadMessagesBefore(jid, beforeMsg, beforeMsgIsOwner, 20)

		if err != nil {
			return nil, err
		}

		msgs := decodeMessages(response)

		for _, message := range msgs {
			if message.GetKey().GetId() == messageID {
				return message, nil
			}
		}

		if len(msgs) == 0 {
			break
		}

		beforeMsg = *msgs[0].Key.Id
		beforeMsgIsOwner = msgs[0].Key.FromMe != nil && *msgs[0].Key.FromMe
	}

	return nil, fmt.Errorf("message %s of number %d not found", messageID, number)
}```

**Comment by Ased2235** [comment]
Thanks, but I don't understand why we need to pass number? & if so what it do?

Thanks for your help

**Comment by houstondapaz** [comment]
The number is the number of your contact

**Comment by Ased2235** [comment]
> The number is the number of your contact

Oh i see, sorry I didn't read it properly. 

Thanks for your help ❤️

**Comment by Ased2235** [comment]
> like this
> 
> ```go
> func (wa *waHandler) getMessage(number int64, messageID string) (*proto.WebMessageInfo, error) {
> 	jid := fmt.Sprintf("%d@s.whatsapp.net", number)
> 
> 	beforeMsg := ""
> 	beforeMsgIsOwner := true
> 
> 	for {
> 		response, err := wa.connection.LoadMessagesBefore(jid, beforeMsg, beforeMsgIsOwner, 20)
> 
> 		if err != nil {
> 			return nil, err
> 		}
> 
> 		msgs := decodeMessages(response)
> 
> 		for _, message := range msgs {
> 			if message.GetKey().GetId() == messageID {
> 				return message, nil
> 			}
> 		}
> 
> 		if len(msgs) == 0 {
> 			break
> 		}
> 
> 		beforeMsg = *msgs[0].Key.Id
> 		beforeMsgIsOwner = msgs[0].Key.FromMe != nil && *msgs[0].Key.FromMe
> 	}
> 
> 	return nil, fmt.Errorf("message %s of number %d not found", messageID, number)
> }
> ```

i couldn't get your code to work but this works for me so if anyone want to do same thing as me you can use this 
```go
func GetMessage(wac *whatsapp.Conn ,jid string, messageID string) (*proto.WebMessageInfo, error) {
	
	

	beforeMsg := ""
	beforeMsgIsOwner := true
	for {
		response, err := was.LoadMessages(jid, messageID, 3 )

		if err != nil {
			return nil, err
		}

		msgs := decodeMessages(response)

		for _, message := range msgs {
			if message.GetKey().GetId() == messageID {
				return message, nil
			}
		}

		if len(msgs) == 0 {
			break
		}

		beforeMsg = *msgs[0].Key.Id
		beforeMsgIsOwner = msgs[0].Key.FromMe != nil && *msgs[0].Key.FromMe
	}
	fmt.Println(beforeMsg, beforeMsgIsOwner)

	return nil, fmt.Errorf("message %s of number %d not found", messageID, j)
}

func decodeMessages(n *binary.Node) []*proto.WebMessageInfo {

	var messages = make([]*proto.WebMessageInfo, 0)

	if n == nil || n.Attributes == nil || n.Content == nil {
		return messages
	}

	for _, msg := range n.Content.([]interface{}) {
		switch msg.(type) {
		case *proto.WebMessageInfo:
			messages = append(messages, msg.(*proto.WebMessageInfo))
		default:
			log.Println("decodeMessages: Non WebMessage encountered")
		}
	}

	return messages
}
 ```
