### ISSUE TITLE
how get group name?

### ISSUE THREAD

**Issue by xnodcorp** [Rhymen/go-whatsapp#26]
groupMeta, err := wac.GetGroupMetaData(id)
	if err != nil {
		fmt.Println("ERROR! %v", err)
	}
	fmt.Println(<-groupMeta)

result 
{"status":400}

how to get group name?

**Comment by Rhymen** [comment]
Hey xnodcorp,
your code is actually working for me, so I guess your id must be incorrect. The jid for a group chat is created by taking the phone number of the creator and the creation timestamp: `[authorPhoneNo]-[creationTimestamp]@g.us`. An example could be `491726355568-1525266223@g.us`.

I just checked and saw that the contacts message contains the names of the groups. Check out `wac.Store.Contacts[jid].Name`.

**Comment by Rhymen** [comment]
Hey xnodcorp,
you need to go through the login procedure explained in the examples section. You cannot interact with whatsapp without generating the necessary keys. Try to log in and to save the wac struct globally. Then use that instance to call GetGroupMetaData. Don't create a new connection for every call.

**Comment by xnodcorp** [comment]
ok thanks Rhymen
