### ISSUE TITLE
..

### ISSUE THREAD

**Issue by cbalak** [Rhymen/go-whatsapp#260]

**Comment by gabstv** [comment]
> Hi,
> 
> Since this morning, after I scan the QR code the auth token does not validate and request ID is "status": "Invalid LoginRequestID"}
> 
> When I use the regular web.whatsapp.com qr it works... and until today It used to work via your API, but not anymore?
> 
> Please advise if there is an issue your side or mine. Thank you!

what was it?

**Comment by cbalak** [comment]
> > Hi,
> > Since this morning, after I scan the QR code the auth token does not validate and request ID is "status": "Invalid LoginRequestID"}
> > When I use the regular web.whatsapp.com qr it works... and until today It used to work via your API, but not anymore?
> > Please advise if there is an issue your side or mine. Thank you!
> 
> what was it?

Wrong REPO ;-) was meant to post on another thread. So this one might well still work.

**Comment by gabstv** [comment]
oh ok then
