### ISSUE TITLE
Image works in app, but doesn't work in Whatsapp Web

### ISSUE THREAD

**Issue by franklinsales** [Rhymen/go-whatsapp#270]
Hi, I'm trying send image using this package, when I send a image  this image can be view through Whatsapp App, I mean that in app works fine. But this image can't be view through Whatsapp Web. See below the results in Whatsapp Web.

When a send a **_.jpg/jpeg_** (Whatsapp Web): 
![Imgur](https://i.imgur.com/YhAeGQJ.png)

When a send a **_.png_** (Whatsapp Web): 
![Imgur](https://i.imgur.com/VKYtiEs.png)

I don't have no more hypotheses that why the images can be viewd in Whatsapp App and not through Whatspp Web. 

I'm using the last version of package (last commit: 1a11f6d...) and the Go Version: "go1.13.5 linux/amd64"

Can someone help me?

**Comment by franklinsales** [comment]
False issue, the project example is working, so the problem maybe my application.

**Comment by Ased2235** [comment]
Reference to issues #253, this should help you.

**Comment by franklinsales** [comment]
> Reference to issues #253, this should help you.

This solve my problem. The problem was in the thumbnail.

Thank you.

**Comment by Ased2235** [comment]
Yw ♥️
