### ISSUE TITLE
load media info query returning 400 errors

### ISSUE THREAD

**Issue by oriolbcn** [Rhymen/go-whatsapp#271]
I am trying to download not pre-loaded images, therefore issuing a load media query before downloading it.

I understand that at the point of merging this PR https://github.com/Rhymen/go-whatsapp/pull/210 it was working, but right now it's returning a 400.

For reference, this is the query being sent: `wac.query("media", jid, messageId, "", owner, "", 0, 0)`, which should produce the query defined here: https://github.com/sigalor/whatsapp-web-reveng/pull/42#issuecomment-390414969

I'll investigate, but I guess developers that have worked on this before may be able to spot the issue faster. It would also be very helpful if someone else can try to see if I am doing something wrong.

**Comment by oriolbcn** [comment]
I found the error and opened a PR to address it.

**Comment by beshoo** [comment]
@oriolbcn what a great job you made! you are wonderfil
