### ISSUE TITLE
Typing indicator

### ISSUE THREAD

**Issue by amfc** [Rhymen/go-whatsapp#275]
Is there any way to set the typing indicator for a chat?

Thanks!

**Comment by gabstv** [comment]
```wconn.Presence(targetjid, whatsapp.PresenceComposing)```

**Comment by amfc** [comment]
Great! I didn't know it would be related to "presence". It would be cool to have an example on how to use it. Should you for example "reset" it?

Like:

jid := "1555555555@s.whatsapp.net"
str := "42 is the answer"
wac.Presence(jid, whatsapp.PresenceComposing)
time.Sleep(100 * time.Millisecond * len(str))
wac.Presence(jid, whatsapp.PresenceAvailable)
wac.Send(whatsapp.TextMessage{ Info: whatsapp.MessageInfo{ RemoteJid: jid }, Text: str })

**Comment by gabstv** [comment]
@amfc This is also the way I use it. I don't really know if the `PresenceAvailable` is necessary or if a `wac.Send` already resets the state. I send it too, just in case.

**Comment by chatterbro** [comment]
What is the order you are doing it? I often get flooded messages #288 when trying
