### ISSUE TITLE
Get group leave / join 

### ISSUE THREAD

**Issue by Ased2235** [Rhymen/go-whatsapp#276]
Hello, is there any way for check if someone join or left in group? As this feature is available on web.
Thanks

**Comment by Deewai** [comment]
Yes, there is a way to get if a user was added to a group. These kind of information can be found in the HandleJsonMessage handler. The message is received as a string but actually is an array so you will need to decode the message into an []interface{}.
The first index of the array consists of the jsonMessage type. For your case, whenever array[0] = "Chat", then you have a join/leave notification. the data at position 1 consists of a data type of map[string]interface{}. E.g {"id":"The group id", "cmd":"action", "data"["join/leave","id of user who made the action",{"participants":["id's of those affected"]}]}.
By analyzing the data above, information about a join/leave can be gotten or other information concerning the group like a group picture change etc...

**Comment by Ased2235** [comment]
Can you please provide example?

**Comment by Deewai** [comment]
`func (handler Handler) HandleJsonMessage(message string) {
	var array []interface{}
	dec := json.NewDecoder(strings.NewReader(message))
	err := dec.Decode(&array)
	if err == nil{
		if len(array) > 0 {
			if array[0] == "Chat" {
				// save group activity (user join/leave)
				data, ok := array[1].(map[string]interface{})
				if ok {
					groupID := data["id"].(string)
					if data["cmd"] == "action" {
						var chatData []interface{}
						chatData = data["data"].([]interface{})
						action := chatData[0].(string)
						by := chatData[1].(string)
						part, ok := chatData[2].(map[string]interface{})
						if ok {
							if partInterface, ok := part["participants"].([]interface{}); ok {
								for _, v := range partInterface {
									activity := database.GroupActivity{GroupID: groupID, Action: action, By: by, UID: strings.Replace(v.(string), "@c.us", "@s.whatsapp.net", 1)}
									err := conn.InsertGroupActivity(&activity)
									if err != nil {
										log.Println(err)
									}
								}
							}
						}
					}
				}
			}
		}
	}
}`

**Comment by Ased2235** [comment]
What is `database.GroupActivity`? Is it to store on my database or some whatapp functions?

**Comment by Deewai** [comment]
database.GroupActivity is not part of WhatsApp functions. It's just to store the data in my database.

**Comment by Ased2235** [comment]
> `func (handler Handler) HandleJsonMessage(message string) { var array []interface{} dec := json.NewDecoder(strings.NewReader(message)) err := dec.Decode(&array) if err == nil{ if len(array) > 0 { if array[0] == "Chat" { // save group activity (user join/leave) data, ok := array[1].(map[string]interface{}) if ok { groupID := data["id"].(string) if data["cmd"] == "action" { var chatData []interface{} chatData = data["data"].([]interface{}) action := chatData[0].(string) by := chatData[1].(string) part, ok := chatData[2].(map[string]interface{}) if ok { if partInterface, ok := part["participants"].([]interface{}); ok { for _, v := range partInterface { activity := database.GroupActivity{GroupID: groupID, Action: action, By: by, UID: strings.Replace(v.(string), "@c.us", "@s.whatsapp.net", 1)} err := conn.InsertGroupActivity(&activity) if err != nil { log.Println(err) } } } } } } } } } }`


Thanks, this works fine




> database.GroupActivity is not part of WhatsApp functions. It's just to store the data in my database.

I see, `InsertGroupActivity` is also custom code, right? what it do if you don't mind me asking.

**Comment by Deewai** [comment]
You are welcome.
Yes it is.

**Comment by Ased2235** [comment]
> Yes it is.

What it do? if it's related to groups mind sharing?

**Comment by RynKings** [comment]
```
func (wh *waHandler) HandleRawMessage(message *proto.WebMessageInfo) {
	if message.MessageTimestamp == nil {
		return
	}
	if *message.MessageTimestamp < wh.startTime {
		return
	}
	b, err := json.Marshal(message)
	if err != nil {
		fmt.Println(err)
		return
	}
}
```
