### ISSUE TITLE
Not an issue searching for knowlege (best practice for not been banned from whatsapp)

### ISSUE THREAD

**Issue by victormedranop** [Rhymen/go-whatsapp#287]
HI, all. weach are the best practice for NOT been banned from whatsAPP.
yesterday i sent 293 messages then BANNED, today i just add to google account 593 contacts.
and send 593 messages with 1.30 minutos interval and not BANNED. 

please some advice.

Victor

**Comment by beshoo** [comment]
The 293 number you sent to are they in your contacts list? Or not?

**Comment by chatterbro** [comment]
It sounds like you are using this repo for spam. This is strongly against what we stand for. WhatsApp will notice unsolicited messages with contacts that you have never been in touch with before.

**Comment by victormedranop** [comment]
i try it to add to contact in the phone, but no luck.

**Comment by Valdenirmezadri** [comment]
> i try it to add to contact in the phone, but no luck.

can't add users to contact or is there no point in having contacts on cell phone?
