### ISSUE TITLE
QR Scan

### ISSUE THREAD

**Issue by funky81** [Rhymen/go-whatsapp#290]
Hi, i managed to run login example on my terminal.
And QR codes appeared (soo big), then what?
What i suppose to do with this?
Please help.

Thanks

**Comment by andrecpe** [comment]
This is a feature of your terminal. To resolve it you just configure the
terminal to show more lines.
If you are using windows, you can also use the shortcut Ctrl - or + / Ctrl
+ the mouse scroll button

hugs

Isso é uma característica do seu terminal. Para resolver você deve
configurar o terminal para mostrar mais linhas.
Se estiver usando o windows, também é possível usar o atalho Ctrl - ou+ /
Ctrl + o botão de rolagem do mouse.

Abraços

Em sáb., 22 de fev. de 2020 às 12:39, Reski <notifications@github.com>
escreveu:

**Comment by funky81** [comment]
Thanks @andrecpe for your quick response. Ok, finally i can capture it.
Then what i have to do? I try to scan it using whatsapp on android, but seems doesnt work.
I have to reinstall it again.

**Comment by andrecpe** [comment]
Be always welcome Reski,

In general, the examples in the code work well. But in order to respond
correctly, you would need to know how you did it, and what error messages
you are receiving.

Andre Costa

Em sáb., 22 de fev. de 2020 às 19:59, Reski <notifications@github.com>
escreveu:

**Comment by funky81** [comment]
Hi @andrecpe , actually i can try dan success use Login example. 
Can have session although i dont scan qr code.
But i cant go throug with sendTextMessage example.
Always gives me : error logging in: error during login: qr code scan timed out

Thanks

**Comment by funky81** [comment]
maybe because the qr code is too big to scan. 
Have to figure this out

**Comment by andrecpe** [comment]
Hi again Rhymen,

I think your problem is caused because the session is always saved to disk.
Always when starting it will try to restore this file. Try to delete it
before logging in again.

hugs

Andre

Em dom., 23 de fev. de 2020 às 09:05, Reski <notifications@github.com>
escreveu:
