### ISSUE TITLE
sending extendedTextMessage

### ISSUE THREAD

**Issue by hrizal** [Rhymen/go-whatsapp#292]
Does anyone have experience with sending extendedTextMessage?
it's like sending a URL with a preview

**Comment by Ased2235** [comment]
I think you're looking for this

`func Send_Link(title string, text string,url string, description string,thumbnail []byte, to string) {`
  	`title += url`
	`ts := uint64(time.Now().Unix())`
		`status := proto.WebMessageInfo_PENDING`
		`b := make([]byte, 10)`
		`rand.Read(b)`
		`Idsd := strings.ToUpper(hex.EncodeToString(b))`
		`fromMe := true`
		`revocation := &proto.WebMessageInfo{
			Key: &proto.MessageKey{
				FromMe:    &fromMe,
				Id:        &Idsd,
				RemoteJid: &to,
			},
			MessageTimestamp: &ts,
			Message: &proto.Message{
				ExtendedTextMessage :	&proto.ExtendedTextMessage{
					MatchedText :	&url,
					CanonicalUrl :	&url,
					Description :	&description,
					Title :	&title,
					Text :	 &text,
					JpegThumbnail :	thumbnail,`
				`},`
			`},`
			`Status :	&status,`
		`}`

`_, err := Was().Send(revocation)
fmt.Println(err)`

**Comment by hrizal** [comment]
Very nice bro ...
