### ISSUE TITLE
Problem sending message with button.

### ISSUE THREAD

**Issue by Romerito007** [Rhymen/go-whatsapp#296]
Here I sent it from xxxxx1678@s.whatsapp.net to xxxxx8478@s.whatsapp.net, but on WhatsApp the xxxx8478@s.whatsapp.net that sent the message.
I'm sorry for the English! 😅.

![WhatsApp Image 2020-03-14 at 17 31 13](https://user-images.githubusercontent.com/13719169/76690244-090aaa00-661d-11ea-84a4-b3e978ce7f78.jpeg)

`func SendMessageTemplate() (string, error) {

	var response string
	var err error

	Id := utils.GeneratorRandomInfoID()
	Jid := "xxxxxx8478@s.whatsapp.net"

	msgContext := "Be welcome."

	btFooter := "Choose one from the option below. 👇"

	displayText1 := "Yes"
	id1 := "yes"

	displayText2 := "No"
	id2 := "no"

	var buttons []*proto.HydratedTemplateButton

	buttons = append(buttons, &proto.HydratedTemplateButton{
		HydratedButton: &proto.HydratedTemplateButton_QuickReplyButton{
			QuickReplyButton: &proto.HydratedQuickReplyButton{
				DisplayText: &displayText1,
				Id:          &id1,
			},
		},
	})

	buttons = append(buttons, &proto.HydratedTemplateButton{
		HydratedButton: &proto.HydratedTemplateButton_QuickReplyButton{
			QuickReplyButton: &proto.HydratedQuickReplyButton{
				DisplayText: &displayText2,
				Id:          &id2,
			},
		},
	})

	format := &proto.TemplateMessage_HydratedFourRowTemplate{
		HydratedFourRowTemplate: &proto.HydratedFourRowTemplate{
			HydratedContentText: &msgContext,
			HydratedFooterText:  &btFooter,
			HydratedButtons:     buttons,
		},
	}

	content := whatsapp.TemplateMessage{
		Info: whatsapp.MessageInfo{
			RemoteJid: Jid,
			Id:        Id,
			FromMe:    true,
		},
		HydratedTemplate: &proto.HydratedFourRowTemplate{
			HydratedContentText: &msgContext,
			HydratedFooterText:  &btFooter,
			HydratedButtons:     buttons,
			TemplateId:          &Id,
			Title: &proto.HydratedFourRowTemplate_HydratedTitleText{
				HydratedTitleText: msgCaption,
			},
		},
		Format: format,
	}

	response, err = wac.Send(content)
	if err != nil {
		return response, err
	}
	
	return id, nil
}`

`type TemplateMessage struct {
	Info             MessageInfo
	HydratedTemplate *proto.HydratedFourRowTemplate
	Format           interface{}
	ContextInfo      ContextInfo
}

func getTemplateMessageProto(msg TemplateMessage) *proto.WebMessageInfo {

	p := getInfoProto(&msg.Info)

	contextInfo := getContextInfoProto(&msg.ContextInfo)

	if template, ok := msg.Format.(*proto.TemplateMessage_HydratedFourRowTemplate); ok {
		p.Message = &proto.Message{
			TemplateMessage: &proto.TemplateMessage{
				HydratedTemplate: msg.HydratedTemplate,
				Format:           template,
				ContextInfo:      contextInfo,
			},
		}
	}

	if template, ok := msg.Format.(*proto.TemplateMessage_FourRowTemplate); ok {
		p.Message = &proto.Message{
			TemplateMessage: &proto.TemplateMessage{
				HydratedTemplate: msg.HydratedTemplate,
				Format:           template,
				ContextInfo:      contextInfo,
			},
		}
	}
	return p
}`

**Comment by hrizal** [comment]
what do you mean:
You want to send the templateMessage to the destination number, 
but what happens is the templateMessage appears in the sender, correct?

**Comment by Romerito007** [comment]
Yes! other types of messages are sent correctly to the destination number. But when I send messages with buttons, it happens the other way around.

**Comment by beshoo** [comment]
Is this for real? Can you send this type of messages to WhatsApp?

I can not believe since WhatsApp it self dos not support it.

**Comment by Romerito007** [comment]
> Isso é pra valer? Você pode enviar esse tipo de mensagem para o WhatsApp?
> 
> Eu não posso acreditar, já que o WhatsApp não suporta isso.

**Comment by Romerito007** [comment]
> Is this for real? Can you send this type of messages to WhatsApp?
> 
> I can not believe since WhatsApp it self dos not support it.

Yes, it is possible to receive, but when sending whatsapp convert type of message text to chat.

[https://github.com/smashah/sulla/issues/98](https://github.com/smashah/sulla/issues/98)

**Comment by hrizal** [comment]
I have also tried, and true, sent to the sender itself

**Comment by ivenkatraj** [comment]
> Here I sent it from [xxxxx1678@s.whatsapp.net](mailto:xxxxx1678@s.whatsapp.net) to [xxxxx8478@s.whatsapp.net](mailto:xxxxx8478@s.whatsapp.net), but on WhatsApp the [xxxx8478@s.whatsapp.net](mailto:xxxx8478@s.whatsapp.net) that sent the message. I'm sorry for the English! 😅.
> 
> ![WhatsApp Image 2020-03-14 at 17 31 13](https://user-images.githubusercontent.com/13719169/76690244-090aaa00-661d-11ea-84a4-b3e978ce7f78.jpeg)
> 
> `func SendMessageTemplate() (string, error) {
> 
> ```
> var response string
> var err error
> 
> 
> Id := utils.GeneratorRandomInfoID()
> Jid := "xxxxxx8478@s.whatsapp.net"
> 
> msgContext := "Be welcome."
> 
> btFooter := "Choose one from the option below. 👇"
> 
> displayText1 := "Yes"
> id1 := "yes"
> 
> displayText2 := "No"
> id2 := "no"
> 
> var buttons []*proto.HydratedTemplateButton
> 
> buttons = append(buttons, &proto.HydratedTemplateButton{
> 	HydratedButton: &proto.HydratedTemplateButton_QuickReplyButton{
> 		QuickReplyButton: &proto.HydratedQuickReplyButton{
> 			DisplayText: &displayText1,
> 			Id:          &id1,
> 		},
> 	},
> })
> 
> buttons = append(buttons, &proto.HydratedTemplateButton{
> 	HydratedButton: &proto.HydratedTemplateButton_QuickReplyButton{
> 		QuickReplyButton: &proto.HydratedQuickReplyButton{
> 			DisplayText: &displayText2,
> 			Id:          &id2,
> 		},
> 	},
> })
> 
> format := &proto.TemplateMessage_HydratedFourRowTemplate{
> 	HydratedFourRowTemplate: &proto.HydratedFourRowTemplate{
> 		HydratedContentText: &msgContext,
> 		HydratedFooterText:  &btFooter,
> 		HydratedButtons:     buttons,
> 	},
> }
> 
> content := whatsapp.TemplateMessage{
> 	Info: whatsapp.MessageInfo{
> 		RemoteJid: Jid,
> 		Id:        Id,
> 		FromMe:    true,
> 	},
> 	HydratedTemplate: &proto.HydratedFourRowTemplate{
> 		HydratedContentText: &msgContext,
> 		HydratedFooterText:  &btFooter,
> 		HydratedButtons:     buttons,
> 		TemplateId:          &Id,
> 		Title: &proto.HydratedFourRowTemplate_HydratedTitleText{
> 			HydratedTitleText: msgCaption,
> 		},
> 	},
> 	Format: format,
> }
> 
> response, err = wac.Send(content)
> if err != nil {
> 	return response, err
> }
> 
> return id, nil
> ```
> 
> }`
> 
> `type TemplateMessage struct { Info MessageInfo HydratedTemplate *proto.HydratedFourRowTemplate Format interface{} ContextInfo ContextInfo }
> 
> func getTemplateMessageProto(msg TemplateMessage) *proto.WebMessageInfo {
> 
> ```
> p := getInfoProto(&msg.Info)
> 
> contextInfo := getContextInfoProto(&msg.ContextInfo)
> 
> if template, ok := msg.Format.(*proto.TemplateMessage_HydratedFourRowTemplate); ok {
> 	p.Message = &proto.Message{
> 		TemplateMessage: &proto.TemplateMessage{
> 			HydratedTemplate: msg.HydratedTemplate,
> 			Format:           template,
> 			ContextInfo:      contextInfo,
> 		},
> 	}
> }
> 
> if template, ok := msg.Format.(*proto.TemplateMessage_FourRowTemplate); ok {
> 	p.Message = &proto.Message{
> 		TemplateMessage: &proto.TemplateMessage{
> 			HydratedTemplate: msg.HydratedTemplate,
> 			Format:           template,
> 			ContextInfo:      contextInfo,
> 		},
> 	}
> }
> return p
> ```
> 
> }`

Developers please please explain in details how to send messages with interactive button. I can't understand the procedure of how to run the above program. I want to send messages with interactive buttons on whastapp.
