### ISSUE TITLE
Sending files?

### ISSUE THREAD

**Issue by Mikolasek93** [Rhymen/go-whatsapp#3]
All respect to your work, your projects work like a charm and sending messages is ultra fast, which is not I can tell about my "stupid selenium solution".

Are you willing to implement file sending feature?

Thanks for your work!

**Comment by Rhymen** [comment]
Thank you very much Mikolasek93,
we are currently working on uploading and sending files. We are still investigating the file encryption, so we do not know how much longer it will take.

**Comment by SchulteMK** [comment]
Hi,
we are happy to tell you that we successfully implemented media uploading and sending. The interface still needs a little bit of work and we want to try to detect the content type automatically. We added an example to send an image, further documentation will follow.

**Comment by Mikolasek93** [comment]
Glad to hear that! Good job and thanks for info guys 👍
