### ISSUE TITLE
 Error decoding login resp

### ISSUE THREAD

**Issue by Ased2235** [Rhymen/go-whatsapp#304]
`2020/03/26 17:21:57 error logging in: error during login: error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}
`
I'm getting this error since this morning i already updated this library but i'm still getting this error, Can anyone please help me?

**Comment by elpulga** [comment]
I'm having the same Issue.

**Comment by sebbu2** [comment]
same error when using hoehermann/purple-gowhatsapp

**Comment by gtavidian** [comment]
+1

**Comment by sthales** [comment]
Working fine here

**Comment by Ased2235** [comment]
> Working fine here

Did you try restarting?

**Comment by gtavidian** [comment]
definitevly not working

**Comment by borigoto** [comment]
> Working fine here

if you restart your GO, the service down...

**Comment by guilhermegehres** [comment]
it seems that changing the client version to (0, 4, 1307) works again
on session.go line 21 `var waVersion = []int{0, 3, 3324}
` to `var waVersion = []int{0, 4, 1307}`

**Comment by sthales** [comment]
> > Working fine here
> 
> Did you try restarting?

Yep.

> it seems that changing the client version to (0, 4, 1307) works again
> on session.go line 21 `var waVersion = []int{0, 3, 3324} ` to `var waVersion = []int{0, 4, 1307}`


I'm running on 0.4.1307.

**Comment by guilhermegehres** [comment]
or simple use 	`wac, err := whatsapp.NewConn(20 * time.Second)
	wac.SetClientVersion(0, 4, 1307)`

**Comment by p4kl0nc4t** [comment]
> or simple use `wac, err := whatsapp.NewConn(20 * time.Second) wac.SetClientVersion(0, 4, 1307)`

Have you tried it? Does it work?

**Comment by guilhermegehres** [comment]
> > or simple use `wac, err := whatsapp.NewConn(20 * time.Second) wac.SetClientVersion(0, 4, 1307)`
> 
> Have you tried it? Does it work?

yes

**Comment by Ased2235** [comment]
> > or simple use `wac, err := whatsapp.NewConn(20 * time.Second) wac.SetClientVersion(0, 4, 1307)`
> 
> Have you tried it? Does it work?

Yes it's working, i tried that too


> or simple use `wac, err := whatsapp.NewConn(20 * time.Second) wac.SetClientVersion(0, 4, 1307)`

Thanks <3

**Comment by p4kl0nc4t** [comment]
Guys, do you have a dynamic way to solve this problem in the future? E.g by scraping the latest version number from something and use it, is that possible?

**Comment by Ased2235** [comment]
> Guys, do you have a dynamic way to solve this problem in the future? E.g by scraping the latest version number from something and use it, is that possible?

ye i think there a way to get the update Version from chrome but i don't how

**Comment by sthales** [comment]
> Guys, do you have a dynamic way to solve this problem in the future? E.g by scraping the latest version number from something and use it, is that possible?

Look at /examples/checkNewVersion

**Comment by olmari** [comment]
Would general question be that do we always want to exactly report newest version or however this works, automatically?

**Comment by Ased2235** [comment]
> Would general question be that do we always want to exactly report newest version or however this works, automatically?
> 

That works automatically. Anyways i'll be closing this issue since it's solved 



> EDIT: anyway, good find :)

Yep
