### ISSUE TITLE
WhatsApp has stopped working with 0.3.3324 clients

### ISSUE THREAD

**Issue by j-f-r** [Rhymen/go-whatsapp#305]
The current master (and latest release) of this repository uses version 0.3.3324, however the server started responding with `["Cmd",{"type":"update"}]`, and the `Login` function stopped working.

I tried changing `waVersion` to `[]int{0, 4, 1307}`, and the QR code generation started working again. However I'm not sure what are the implications of using this newer version.

Has someone else ran into this issue?

**Comment by sthales** [comment]
#304

**Comment by alejandroguille** [comment]
Is it the same mistake?:

error logging in: error during login: error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}

**Comment by adarosci** [comment]
Update version

session.go ->
var waVersion = []int{0, 4, 2080}

**Comment by j-f-r** [comment]
@alejandroguille yes, it is the same error.

@adarosci there's already an exposed method that does it:
```
wac.SetClientVersion(0, 4, 1307)
```

**Comment by izhur** [comment]
After resolving this problem 
```
error logging in: error during login: error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}
```
with
```
wac.SetClientVersion(0, 4, 1307)
```
or
```
wac.SetClientVersion(0, 4, 2080)
```

The QR code generated successfully, but it can't be scan on my whatsapp application, with message:

```
couldn't scan code. Make sure you're on web.whastapp.com and scan again 
```

**Comment by Ased2235** [comment]
This might help #304

**Comment by izhur** [comment]
> This might help #304

Not working on my case. QR Code can be generated but, whatsapp won't scan the generated QR Code.

**Comment by p4kl0nc4t** [comment]
Mine is still working. It shows an error to decode tag 174 but it works (I can send and read messages). I don't know what actually happens under the hood.
