### ISSUE TITLE
error when try to login

### ISSUE THREAD

**Issue by ANNASBlackHat** [Rhymen/go-whatsapp#311]
when I try this little code :

import (
    whatsapp "github.com/Rhymen/go-whatsapp"
)
wac, err := whatsapp.NewConn(20 * time.Second)
	if err != nil {
		fmt.Println("conn err : ", err)
	}
	qrChan := make(chan string)
	go func() {
		fmt.Printf("qr code: %v\n", <-qrChan)
		//show qr code or save it somewhere to scan
	}()
	_, err = wac.Login(qrChan)
	if err != nil {
		fmt.Println("login err : ", err)
	}

I got an error : 
 error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}

it's happen either using old version or the latest

**Comment by cht368** [comment]
Duplicate of #305

**Comment by cht368** [comment]
#304

**Comment by ANNASBlackHat** [comment]
wow, that's work
thanks
