### ISSUE TITLE
QR Code Scan

### ISSUE THREAD

**Issue by AI-man001** [Rhymen/go-whatsapp#314]
After scaning the QR Code I get this error:

**_error caught in handler: error processing data: error decoding binary: could not decode binary: invalid string with tag 174_** 

what is the problem. I'm running echo example. If I rerun the program, I get the same error

**Comment by izhur** [comment]
https://github.com/Rhymen/go-whatsapp/issues/305#issuecomment-605530653

waClient  version of the original https://web.whatsapp.com/ keep changing. Right now you should use 

```
wac.SetClientVersion(0, 4, 2088)
```

**Comment by RynKings** [comment]
> [#305 (comment)](https://github.com/Rhymen/go-whatsapp/issues/305#issuecomment-605530653)
> 
> waClient version of the original https://web.whatsapp.com/ keep changing. Right now you should use
> 
> ```
> wac.SetClientVersion(0, 4, 2088)
> ```

not working :"

**Comment by janamcroods** [comment]
wac.SetClientVersion(0, 4, 2088)
 not working     "error": "unexpected end of JSON input" in go-whatsapp-rest

**Comment by cleitonoliveira** [comment]
> [#305 (comment)](https://github.com/Rhymen/go-whatsapp/issues/305#issuecomment-605530653)
> 
> waClient version of the original https://web.whatsapp.com/ keep changing. Right now you should use
> 
> ```
> wac.SetClientVersion(0, 4, 2088)
> ```

It's possible to keep version outside the exec so it doesn't need to be generated again?
