### ISSUE TITLE
 New message from a new contact

### ISSUE THREAD

**Issue by Mateus-pilo** [Rhymen/go-whatsapp#315]
When I receive a new message from a new contact, I call wac.Store.Contacts[RemoteJid]
it returns the empty object look like this:
```
type waHandler struct{
	c *whatsapp.Conn
	jid string
	created uint64
}


func (h *waHandler) HandleTextMessage(message whatsapp.TextMessage) {
	if message.Info.FromMe == false && message.Info.Timestamp >= h.created  {
		contact:= h.c.Store.Contacts[message.Info.RemoteJid]
return  { Jid:"" Name:"" Notify:"" Short:"" }

**Comment by x00b** [comment]
The Store.Contacts retrieves data from a contact (if) stored on the cellphone of the whatsapp account. If the contact is not stored in the cellphone, it will retrieve empty.

**Comment by Mateus-pilo** [comment]
> O Store.Contacts recupera dados de um contato (se) armazenado no celular da conta do whatsapp. Se o contato não estiver armazenado no celular, ele será recuperado vazio.


Right. how would I get the name or notification name, I try call Store.Chats(RemoteJid), but not success.

**Comment by x00b** [comment]
There is no way. The only way to retrieve a contact data is if the cellphone has the contact stored in it. The picture can be retrieved(see #164 ) if the contact has it set to public.

**Comment by Mateus-pilo** [comment]
> There is no way. The only way to retrieve a contact data is if the cellphone has the contact stored in it. The picture can be retrieved(see #164 ) if the contact has it set to public.

ok my friend thank so much, i will close the issue.
