### ISSUE TITLE
Send Image or Document error

### ISSUE THREAD

**Issue by adarosci** [Rhymen/go-whatsapp#318]
with the latest update version 2080, started and give error when sending images and document
image upload failed: upload responsed with%! d (float64 = 404)

anyone with this problem?

**Comment by x00b** [comment]
See #316

**Comment by adarosci** [comment]
current problem is resolved with update file media.go

**Comment by Dilshat** [comment]
The problem still persists, using latest version

**Comment by x00b** [comment]
Latest release is not the working version of the library. Please see the date of the issues and use the master branch instead of any release.
