### ISSUE TITLE
how to resize qrcode

### ISSUE THREAD

**Issue by roggerlie** [Rhymen/go-whatsapp#32]
how to change the qrcode size

please help, im beginner golang

![screenshot from 2018-08-31 09-36-58](https://user-images.githubusercontent.com/11186656/44889722-7425b180-ad01-11e8-8dca-c762adceb6d6.png)

**Comment by SchulteMK** [comment]
It depends on the font size you use in the console. If you print on console you cannot change it within the go program sadly. Try to find an option in your IDE to change the font size (I cannot find one:/). On my laptop I always detached the console from the main GoLand window. Mybe it is enough for you. Compiling your program and starting it within the os terminal (smaller font size) will help.

Your last choice would be to export the qr code to an image and open it manually, or print the base64 version to console and copy it to some online qr code generator. But you have to be quick... the qr code times out after 20 seconds.

**Comment by roggerlie** [comment]
thank you for answering, as you use using the terminal and zoom out on the terminal.
thank you 😁
