### ISSUE TITLE
runtime error on sending messages

### ISSUE THREAD

**Issue by stiivo** [Rhymen/go-whatsapp#325]
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x7cb993]
goroutine 69 [running]:
github.com/Rhymen/go-whatsapp.(*Conn).sendProto(0x0, 0xc0004b4120, 0xc0003aa516, 0x1c, 0x0)
	/home/steven/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200330124403-6f3b367bb101/message.go:101 +0x93
github.com/Rhymen/go-whatsapp.(*Conn).Send(0x0, 0xa345c0, 0xc00025dc20, 0xc00025dc20, 0x444ccc, 0x30, 0x9bbf20)
	/home/steven/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200330124403-6f3b367bb101/message.go:72 +0x438
main.sendWhatsAppMessage(0xc0003aa516, 0x1c, 0xc0003aa533, 0x3)
	/home/steven/WhatsappMattermost/WhatsappMattermost.go:188 +0xcf
main.HandleMsgFromDebuggingChannel(0xc000101f20)
	/home/steven/WhatsappMattermost/WhatsappMattermost.go:312 +0x2c0
main.HandleWebSocketResponse(...)
	/home/steven/WhatsappMattermost/WhatsappMattermost.go:284
main.initMM.func1(0xc000106000)
	/home/steven/WhatsappMattermost/WhatsappMattermost.go:140 +0x41
created by main.initMM
	/home/steven/WhatsappMattermost/WhatsappMattermost.go:136 +0x23b`

im pretty new to golang so i got stuck on this error. thanks in advance for any help

**Comment by x00b** [comment]
The wac was nil when you tried to Send() the message. Add a if wac == nil { tryToRestore() } logic before trying to send it
