### ISSUE TITLE
Set User Agent

### ISSUE THREAD

**Issue by hariadivicky** [Rhymen/go-whatsapp#326]
Hi Rhymen, please provide function to set user agent such as browser like this : _Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:74.0) Gecko/20100101 Firefox/74.0_

thanks in advance

**Comment by necaticanyildirim** [comment]
I think you are trying to set a client name instead of an user agent.
func (wac *Conn) SetClientName(long, short string) error

**Comment by hariadivicky** [comment]
Thanks neca, sorry for my ignorance on api docs. thanks for help

**Comment by rhsobr** [comment]
Why not setting up the UserAgent too? 🤔
