### ISSUE TITLE
Receiving Share Location

### ISSUE THREAD

**Issue by lutpiero** [Rhymen/go-whatsapp#33]
Is it possible to send and receive Location share ?

**Comment by SchulteMK** [comment]
It is not implemented as ist own message type right now, but you can receive alle messages via the `RawMessageHandler` and extract the needed `LocationMessage` yourself. It should contain any Information you need. See [here](https://github.com/Rhymen/go-whatsapp/blob/92ffb4c11a14df04cc0fd8b285b8ef2efb023d54/binary/proto/def.pb.go#L889)
