### ISSUE TITLE
Connection failed code: 1000, text:

### ISSUE THREAD

**Issue by adarosci** [Rhymen/go-whatsapp#333]
anyone see this error?
I have this error happening frequently

"Connection failed, underlying error: server closed connection,code: 1000,text:"

**Comment by 0xhex** [comment]
yes same issue any solution?

**Comment by h2o10** [comment]
looks like whatsapp stopping this client. Even other clients like https://github.com/sigalor/whatsapp-web-reveng are also not working.

**Comment by gvn182** [comment]
I have problem to reconnect, reading a new QR code works..

**Comment by h2o10** [comment]
Even QR code also not getting generated. @gvn182 can you tell us how you are generating QR code?

**Comment by gvn182** [comment]
I use Whatsapp reveng python and there qr is working..

**Comment by ramacatur** [comment]
Hai, I have some problem `Connection failed code: 1000, text:`. I try see web.whatsapp and I get message ws 

`1587435287.--0,["admin","init",[2,2013,7],["Mac OS","Chrome","10.15.4"],"v2zYRN9qQ+OHWxegMgNsPA==",true]`

I try change client version to 2,2013,7 but connection timeout. And I try add client version "10.15.4" for client name and login succesfully.

So, I add variable `clientVersion   string` in `conn.go` file.
In `session.go` file I change SetClientName function to 

`func (wac *Conn) SetClientName(long, short, version string) error {
	if wac.session != nil && (wac.session.EncKey != nil || wac.session.MacKey != nil) {
		return fmt.Errorf("cannot change client name after logging in")
	}
	wac.longClientName, wac.shortClientName, wac.clientVersion = long, short, version
	return nil
}`

I change in Login function and other function with code

`login := []interface{}{"admin", "init", waVersion, []string{wac.longClientName, wac.shortClientName}, session.ClientId, true}`

to

`login := []interface{}{"admin", "init", waVersion, []string{wac.longClientName, wac.shortClientName, wac.clientVersion}, session.ClientId, true}`

Sorry my bad language.

**Comment by 0xhex** [comment]
@ramacatur this worked however when you logout whatsapp and reopen, you need to re generate QR Code,other way it gives code 1000 text: etc.

:((((((

**Comment by x00b** [comment]
Yes, session restoration is not working.

**Comment by adarosci** [comment]
in file session.go line 372 

replace
login := []interface{}{"admin", "init", waVersion, []string{wac.longClientName, wac.shortClientName}, b64ClientId, true}

login := []interface{}{"admin", "init", waVersion, []string{wac.longClientName, wac.shortClientName, "10.15.4"}, b64ClientId, true}

**Comment by ramacatur** [comment]
> @ramacatur this worked however when you close whatsapp and reopen, you need to re generate QR Code,other way it gives code 1000 text: etc.
> 
> :((((((

In file `session.go`, `Restore` function, change this code 👍 

`init := []interface{}{"admin", "init", waVersion, []string{wac.longClientName, wac.shortClientName}, wac.session.ClientId, true}`

to

`init := []interface{}{"admin", "init", waVersion, []string{wac.longClientName, wac.shortClientName, wac.clientVersion}, wac.session.ClientId, true}`

**Comment by beshoo** [comment]
Any patch to make things back to normal?

**Comment by x00b** [comment]
Yes, a pull request was opened and things are working.
