### ISSUE TITLE
Login connection timed out

### ISSUE THREAD

**Issue by cht368** [Rhymen/go-whatsapp#334]
Last few hours I got "login connection timed out" error message when trying to login via session. Tried to change waVersion but still get timed out. Does anyone get this error message too?

**Comment by h2o10** [comment]
looks like whatsapp stopping this client. Even other clients like `https://github.com/sigalor/whatsapp-web-reveng` are also not working.

**Comment by x00b** [comment]
+1

**Comment by 0xhex** [comment]
+1

**Comment by mfalfaruqi** [comment]
+1

**Comment by reptildarat** [comment]
+1

**Comment by rizalfr** [comment]
+1

**Comment by gvn182** [comment]
Just a note, generating a new qr code on whatsapp-web-reveng works..

**Comment by h2o10** [comment]
but for me even QR code also not generating. I'm using whatsapp-web-reveng  docker.

<img width="889" alt="Screenshot 2020-04-21 at 8 16 34 AM" src="https://user-images.githubusercontent.com/46250897/79819836-7a6e1300-83a8-11ea-81da-a9da4cf73df3.png">

**Comment by x00b** [comment]
Generating QrCode with the go-whatsapp is not working either

**Comment by gvn182** [comment]
What version are you using? I'm using [0,4,2088] and it's generating.. (whatsapp-web-reveng)

**Comment by x00b** [comment]
i'm using 0,4,2088 too

**Comment by x00b** [comment]
And running example/checkNewVersion gives a panic `panic: runtime error: index out of range [0] with length 0`

**Comment by sthales** [comment]
Current version is 2.2013.7

**Comment by gvn182** [comment]
Guys I got it working here in whatsapp reveng, I think it will work on go as well:
Add the version to the init array like so: the important part here is: "Mac OS", "Chrome", "VERSION HERE"

`1587436001.--0,["admin","init",[2,2013,7],["Mac OS","Chrome","10.15.4"],"xxxx",true]`

**Comment by ramacatur** [comment]
Hai, I have some problem `Connection failed code: 1000, text:`. I try see web.whatsapp and I get message ws 

`1587435287.--0,["admin","init",[2,2013,7],["Mac OS","Chrome","10.15.4"],"v2zYRN9qQ+OHWxegMgNsPA==",true]`

I try change client version to 2,2013,7 but connection timeout. And I try add client version "10.15.4" for client name and login succesfully.

So, I add variable `clientVersion   string` in `conn.go` file.
In `session.go` file I change SetClientName function to 

`func (wac *Conn) SetClientName(long, short, version string) error {
	if wac.session != nil && (wac.session.EncKey != nil || wac.session.MacKey != nil) {
		return fmt.Errorf("cannot change client name after logging in")
	}
	wac.longClientName, wac.shortClientName, wac.clientVersion = long, short, version
	return nil
}`

I change in Login function and other function with code

`login := []interface{}{"admin", "init", waVersion, []string{wac.longClientName, wac.shortClientName}, session.ClientId, true}`

to

`login := []interface{}{"admin", "init", waVersion, []string{wac.longClientName, wac.shortClientName, wac.clientVersion}, session.ClientId, true}`

Sorry my bad language.

**Comment by sthales** [comment]
> Guys I got it working here in whatsapp reveng, I think it will work on go as well:
> Add the version to the init array like so: the important part here is: "Mac OS", "Chrome", "VERSION HERE"
> 
> `1587436001.--0,["admin","init",[2,2013,7],["Mac OS","Chrome","10.15.4"],"xxxx",true]`

Thanks! It works!

**Comment by cht368** [comment]
It did connect but didn't listen and no message got through for me

**Comment by cht368** [comment]
Login and reconnecting process got significantly slower for me

**Comment by x00b** [comment]
Also need to change in session.go to

`init := []interface{}{"admin", "init", waVersion, []string{wac.longClientName, wac.shortClientName}, wac.session.ClientId, true}`

to

 `init := []interface{}{"admin", "init", waVersion, []string{wac.longClientName, wac.shortClientName, wac.clientVersion}, wac.session.ClientId, true}`

**Comment by kennethreitz** [comment]
I Love This Community

**Comment by akangaziz** [comment]
awesome

**Comment by qqqaq** [comment]
I love too

**Comment by beshoo** [comment]
in my script i have this :

```
func StartWithSession(sessions []storage.WASession) {
        for _, waSession := range sessions {
                session := SessionFromWASession(waSession)
                go func(waSession storage.WASession) {
                        Retry(10, time.Millisecond*1000, func() error {
                                wac, err := NewConn(waSession.ProxyURL)
                                if err != nil {
                                        log.Errorf("StartWithSession Connect failed%v for wid %v", err, session.Wid)
                                        return err
                                }
                                wac.SetClientName(longName, shortName )

```
it seems there is an error here   `wac.SetClientName(longName, shortName )` and i would pass client Virsion string ? but how ? any advice

**Comment by x00b** [comment]
`wac.SetClientName("Long name", "shor Name", "10.15.14")`

**Comment by beshoo** [comment]
yes I know but why it dos not take it directly from the baselib! @x00b

**Comment by ramacatur** [comment]
> yes I know but why it dos not take it directly from the baselib! @x00b

You can add default client version value in `NewConn` function file `conn.go`
```
wac := &Conn{
		handler:    make([]Handler, 0),
		msgCount:   0,
		msgTimeout: timeout,
		Store:      newStore(),

		longClientName:  "github.com/rhymen/go-whatsapp",
		shortClientName: "go-whatsapp",
		clientVersion:   "10.15.14",
	}
```

**Comment by beshoo** [comment]
I did that already but my question is , why user has to add this value, it has to be preset in the lib.

**Comment by beshoo** [comment]
I am confused, in the master branch
https://github.com/Rhymen/go-whatsapp/blob/master/conn.go
There is nothing about clientVirsion  

But in my 
/root/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200408093540-2f227c53b44f
```

type Conn struct {
        ws       *websocketWrapper
        listener *listenerWrapper

        connected bool
        loggedIn  bool
        wg        *sync.WaitGroup

        session        *Session
        sessionLock    uint32
        handler        []Handler
        msgCount       int
        msgTimeout     time.Duration
        Info           *Info
        Store          *Store
        ServerLastSeen time.Time

        longClientName  string
        shortClientName string
        clientVersion   string

        loginSessionLock sync.RWMutex
        Proxy            func(*http.Request) (*url.URL, error)

        writerLock sync.RWMutex
}

```

What I am missing?

**Comment by x00b** [comment]
Its was added to web.whatsapp tonight.

**Comment by beshoo** [comment]
> Its was added to web.whatsapp tonight.

Thank you for your reply, I mean it would be nice if the PL has this update as well so normal users will not go through this problem.
