### ISSUE TITLE
cannot unmarshal array into Go value of type map[string]interface {}

### ISSUE THREAD

**Issue by e1milio** [Rhymen/go-whatsapp#340]
my application worked but stopped working

cannot unmarshal array into Go value of type map[string]interface {}

ubuntu 18.04

go.mod

module wi-go

go 1.13

require (
	github.com/Baozisoftware/qrcode-terminal-go v0.0.0-20170407111555-c0650d8dff0f
	github.com/Rhymen/go-whatsapp v0.1.0
	github.com/imroc/req v0.3.0
	github.com/skip2/go-qrcode v0.0.0-20191027152451-9434209cb086
)

**Comment by juliowerner** [comment]
Fixed in master #336, isn't?

**Comment by bryanjack** [comment]
Same here, running on CentOS 7

error logging in: restoring session failed: error decoding login connResp: json: cannot unmarshal array into Go value of type map[string]interface {}
