### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by beshoo** [Rhymen/go-whatsapp#347]
While Running I got this error message after the latest update 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x85fde2d]

goroutine 2791 [running]:
/wa-api/whatsapp.(*WaHandler).HandleError(0xa9a8280, 0x88d5000, 0xab28b38)
        /home/beshoo/go-wapi/wa/whatsapp/handle_error.go:28 +0x6d
created by github.com/Rhymen/go-whatsapp.(*Conn).handleWithCustomHandlers
        /root/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200408093540-2f227c53b44f/handler.go:183 +0x166

```
What is going on?

**Comment by beshoo** [comment]
After some debug i note this is the error which returns

Error connection to WhatsApp servers failed: websocket: close 1006 (abnormal closure): unexpected EOF

But why lib is forcing to fail?

**Comment by mapodesta** [comment]
@beshoo I've similar problem, but my problem it's when i tried to send a message, because my form doesnt' print the qr code and session doesn't start. Do you connect your golang code with data base or graphic interface (html,web,etc) ?

thanks and srry for my english
