### ISSUE TITLE
Having issue when sending a file : image , video etc

### ISSUE THREAD

**Issue by Dilshat** [Rhymen/go-whatsapp#349]
When I follow the example and try to send an image , the client fails with message:
`image upload failed: upload responsed with %!d(float64=404`
using latest version v0.1.0

**Comment by x00b** [comment]
Use the master branch not v0.1.0 or any release.

**Comment by Dilshat** [comment]
> Use the master branch not v0.1.0 or any release.

Thanks, it helped

**Comment by Piyushhbhutoria** [comment]
I am currently facing this issue. I tried downloading from the master but it didn't work for me.

**Comment by swagat-dash** [comment]
Error sending message: to 9316917166 --> image upload failed: upload responsed with %!d(float64=404)

I also get the same error.. I tried compressing and resizing images but nothing helped.

**Comment by odedrosler3** [comment]
have the same:
image upload failed: upload responsed with %!d(float64=404)
