### ISSUE TITLE
Missing incoming chat

### ISSUE THREAD

**Issue by cht368** [Rhymen/go-whatsapp#351]
Sometimes incoming chat didn't detected even when my connection is good. Tried logged everything that went through dispatch() on handler.go but didn't find anything related to missing chat. 
Is there any way to detect missed chat and make the socket more reliable?

**Comment by cht368** [comment]
after further investigation, the message is detected but not as a valid message (it went to default case on handler.go switch)
https://github.com/Rhymen/go-whatsapp/blob/5e33cb4ac5513dfae77f487f67e7e4c42bf20171/handler.go#L177)

any clue why is this happened?

**Comment by gabstv** [comment]
This started happening very frequently today. In some cases, more than half of the messages are not being detected correctly. Text and images.
