### ISSUE TITLE
CPU 100% but memeory is low! But NumGC is growing!

### ISSUE THREAD

**Issue by beshoo** [Rhymen/go-whatsapp#356]
Today while I am testing I note the following
I have an idle session, I sent an image as following 

```
Alloc = 3 MiB   TotalAlloc = 30 MiB     Sys = 16 MiB    NumGC = 283
time="2020-05-05T12:50:46Z" level=info msg="Url /api/send/image"
[mysql] 2020/05/05 12:50:46 packets.go:122: closing bad idle connection: EOF
time="2020-05-05T12:50:46Z" level=info msg=2
```
 CPU jump to 100%, I hade to kill the proc, am not sure if that because "packets.go:122: closing bad idle connection: EOF" !
Do you have any idea why we have such behavior?
Is it the number of NumGC ? it is quite big!
    // NumGC is the number of completed GC cycles.
@x00b Any Idea ?

**Comment by x00b** [comment]
That's weird. This idle session when you tried to send the image was activated/online?

The high GC i think might be a default behavior of go garbage collector(which is not a good thing), but if you could give more details about it we will figure things out

**Comment by beshoo** [comment]
I am not that expert in goLang, A freelancer make an API for me and he disappears :) 
Well, I am trying to understand how things is going on, I am PHP dev.
>That's weird. This idle session when you tried to send the image was activated/online?
Yes it was online.

PS: How can I contact you private?

**Comment by beshoo** [comment]
> That's weird. This idle session when you tried to send the image was activated/online?
> 
> The high GC i think might be a default behavior of go garbage collector(which is not a good thing), but if you could give more details about it we will figure things out
> 
> edit: i am thinking that the default gc behavior isn't helping at all. Theres quite a lot of articles talking about this spikes and high cycles and how it causes other problems that should not exist.

Agien i have the same situation , but I note that device sent : 
**`Process Que Recieved Signal PAUSE`**

Then I sent the message vie the API....!

**Comment by beshoo** [comment]
Again sending a message while PAUSE is activated turn CPU to 100%

**Comment by beshoo** [comment]
SOLVED
There is an infinite loop checking the PAUSE
