### ISSUE TITLE
Simulations Of "ErrConnectionFailed connection to WhatsApp servers failed: websocket: close 1006" and session problems!

### ISSUE THREAD

**Issue by beshoo** [Rhymen/go-whatsapp#357]
Dear all, How can I close the websocket to simulate ErrConnectionFailed and other types of errors!
I don't want to do it form the code, I need to do it form the Linux level
How can I kill the session, My API will reconnect but I need to see all scenarios
Sometimes wh.Wac.Info is nil sometimes it is not.
sometimes *(wh.Session) the session is nill. I need to know how can I simulate that without going back to the code.

Regards

**Comment by beshoo** [comment]
SOLVED

**Comment by JEK58** [comment]
Could you tell us how you solved it? I get this error quite often…
