### ISSUE TITLE
Number being banned

### ISSUE THREAD

**Issue by bryanjack** [Rhymen/go-whatsapp#359]
Anyone facing number being banned after sending multiple message?
I'm getting banned after send approx 5 message to different number, and some number are new number. And the message I sent is not simultaneously, with time difference 1-2 minutes.
If you have any workaround, please share..

Thanks

**Comment by beshoo** [comment]
Thats completely a normal behaviour when you send to strangers.

You have to send to who have your number in his address book.

**Comment by gabstv** [comment]
Your phone was probably reported as spam. This can happen, regardless of what method you use to send messages (even if you use the official app).
Sending unsolicited marketing messages is not allowed, according to the Terms of Service.

**Comment by beshoo** [comment]
@bryanjack please close this issue since it is not related.
