### ISSUE TITLE
Closing the WhatsApp

### ISSUE THREAD

**Issue by Mateus-pilo** [Rhymen/go-whatsapp#360]
When I go a long time without receiving a message or some time without activity, the WhatsApp application just breaks and after that I can no longer receive messages, someone with the same problem?
![Failure](https://user-images.githubusercontent.com/56692712/81815974-118a3e80-9501-11ea-9231-619b721a3fb6.jpeg)

**Comment by x00b** [comment]
This error happen when you try sending a message with wrong parameter(like the remote id without @s.whatsapp.net) or use some method of this library wrongly. You can see that restarting(closing the websocket) your software might stop the app error. But that's why it's happening.

**Comment by Mateus-pilo** [comment]
@x00b You're right, thank you very much, I will close de issue !
