### ISSUE TITLE
(bug) Problem with incoming message handlers when WhatsApp is a sleep. 

### ISSUE THREAD

**Issue by beshoo** [Rhymen/go-whatsapp#362]
Dear all.
If the device a sleep, WhatsApp will change the connection status into sleep mode (even if you are using the phone but WhatsApp app is not opened)

If someone send you a any type of message (text, media, gps, any type ... Etc)
The first alert you will got from json handler, which it changes the WhatsApp status from **asleep** to **Conn**.
Here is jsin handler logs
 ```
msg="[\"Conn\",{\"protoVersion\":[0,17],\"binVersion\":11,\"phone\":{\"wa_version\":\"2.20.157\",\"mcc\":\"417\",\"mnc\":\"001\",\"os_version\":\"10\",\"device_manufacturer\":\"samsung\",\"device_model\":\"a50\",\"os_build_number\":\"QP1A.190711.020.A505FDDS4BTD2\"},\"features\":{\"URL\":true,\"FLAGS\":\"EAEYASgBOAFAAUgBWAFgAWgBeAGYAQGgAQGwAQK4AQHIAQHYAQHoAQLwAQP4AQOIAgE=\"},\"pushname\":\"Mojeeb\"}]"

msg="[\"Props\",{\"camelotWeb\":false,\"preloadStickers\":false,\"webVoipInternalTester\":false,\"webCleanIncomingFilename\":1,\"webEnableModelStorage\":false,\"wsCanCacheRequests\":true,\"fbCrashlog\":true,\"bucket\":\"\",\"gifSearch\":\"giphy\",\"maxFileSize\":100,\"media\":64,\"maxSubject\":25,\"maxParticipants\":257,\"imageMaxKBytes\":1024,\"imageMaxEdge\":1600,\"statusVideoMaxDuration\":30,\"frequentlyForwardedMessages\":1,\"restrictGroups\":1,\"productCatalogOpenDeeplink\":1,\"multicastLimitGlobal\":5,\"finalLiveLocation\":1,\"frequentlyForwardedMax\":1,\"mmsMediaKeyTTL\":172800,\"stickers\":1,\"announceGroups\":1001,\"groupDescLength\":512,\"suspiciousLinks\":1,\"fwdUiStartTs\":1531267200}]"

```
This loged after sending image to my WhatsApp while it is on sleep mode (my phone screen is off for 1 hour) . 

The problem is the following :
The only triggered handler is json, but message handler still not aware about the income messages. 
In my case i sent an image to my WhatsApp. 
image handler dos not catch this message, and we missed this chat.

But once you send again, Image handler will triggered since the WhatsApp status is **Conn**.

I believe this is a bug in the library, since if you send a message to WhatsApp, even if the device is a sleep, web WhatsApp will catch up with you.

Any idea why this bug presents?

**Comment by beshoo** [comment]
@Rhymen any advice?

**Comment by beshoo** [comment]
It seems the connection speed play a great part here, i am testing with slow connection speed on my device, which i believe some home when WhatsApp receive *Conn* status, device need some time to follow up with the connection.
And since the connection is very slow, 512kbs... Web WhatsApp will report can not connect to the device... (I think). That is why I missed the first message while device is a sleep.

I am testing 4g connection right now and l will update you with the results.

**Comment by beshoo** [comment]
I confirm, it is connection problem, not a bug

**Comment by beshoo** [comment]
I test it again with a 5g connection, and it seems it is not related to the connection speed.
When Whats is asleep, it needs 2 messages tow wake up the handler!

Is this a bug ?

**Comment by Diden05** [comment]
> I test it again with a 5g connection, and it seems it is not related to the connection speed.
> When Whats is asleep, it needs 2 messages tow wake up the handler!
> 
> Is this a bug ?

Noticed the same behavior.

**Comment by beshoo** [comment]
> > I test it again with a 5g connection, and it seems it is not related to the connection speed.
> > When Whats is asleep, it needs 2 messages tow wake up the handler!
> > Is this a bug ?
> 
> Noticed the same behavior.

Thanks for your update, I hope relly we can find a fix for this behaviour

**Comment by beshoo** [comment]
@SchulteMK any advice.
