### ISSUE TITLE
Error Sending Image Message

### ISSUE THREAD

**Issue by juliowerner** [Rhymen/go-whatsapp#365]
I got the following error when sending image message:
`error sending message: image upload failed: Post https:///mms/image/Wj9a-bDlz3_IJXvdJGK-20lZ6rznV2tB4dqVwNs9e9c=?auth=&token=Wj9a-bDlz3_IJXvdJGK-20`

**Comment by beshoo** [comment]
Yes and we solved the problem, please check the pull request
