### ISSUE TITLE
Not receiving some MSGs

### ISSUE THREAD

**Issue by Mateus-pilo** [Rhymen/go-whatsapp#366]
I have a problem that some messages are not arriving, and some arrive normal, someone with the same problem?

**Comment by beshoo** [comment]
This problem is 100% related to the phone Internet connection.

Make sure that you have stady and fast connection in your phone. 

Regard

**Comment by cht368** [comment]
https://github.com/Rhymen/go-whatsapp/issues/351#issue-611351119

Maybe it's related to my issue?

**Comment by beshoo** [comment]
> [#351 (comment)](https://github.com/Rhymen/go-whatsapp/issues/351#issue-611351119)
> 
> Maybe it's related to my issue?

Please share your logs...

**Comment by beshoo** [comment]
I think you WhatsApp in asleep mode.

**Comment by Mateus-pilo** [comment]
thanks everyone, I resolved this.

**Comment by beshoo** [comment]
How?
