### ISSUE TITLE
Is using proxy important?  

### ISSUE THREAD

**Issue by beshoo** [Rhymen/go-whatsapp#369]
Hello all.
As we know we can create a connection between go-WhatsApp and mobile device over a proxy.
Well, let's say we have 1000 devices are using my server, Well, I am using the server IP address which is one IP address that serves all numbers.  

Do you believe this will trigger a spam flag to Whatsapp?
Someone told me that Whatsapp web connection is like a bridge between your device and the server but eventually your device who will send the message.

All communication between my server and my device is not reviled to Whatsapp servers.
Well, I am not sure!

Do you advise using a random proxy with each connection to protect the server IP address and the numbers which serve by the server! or it does not matter?

**Comment by AlmogBaku** [comment]
Theoretically, (if I'm not mistaken), you're getting connected through Whatsapp servers to your device, which decrypts the command and dispatch it.

The big, and unknown, question- is whether Whatsapp does check your messages between the web-client and the device... It looks like it doesn't, but nobody can assure you that.

**Comment by beshoo** [comment]
That's a big security problem we need to know that.

**Comment by beshoo** [comment]
My question is, well WhatsApp ban numbers if they use same IP ADDRESS?

**Comment by AlmogBaku** [comment]
> That's a big security problem we need to know that.

The data itself is signed. Whatsapp CANNOT view your content... however, some actions are not encrypted(such as login..), and they can obviously see the "envelope" of the message(headers and such).

> My question is, well WhatsApp ban numbers if they use same IP ADDRESS?

We don't know. I guess you'll have to tell us what you found.

**Comment by rhsobr** [comment]
Hi @beshoo , have you configured proxies to your connections' numbers?

**Comment by beshoo** [comment]
Yes and it works....
