### ISSUE TITLE
Link with preview

### ISSUE THREAD

**Issue by daviidmart** [Rhymen/go-whatsapp#370]
Im trying to send a text message with a link but no display preview of url. Heeeelp :c

**Comment by beshoo** [comment]
The display happened on the device by the app it self.

Regard

**Comment by Ased2235** [comment]
i think you're looking for this

`func Send_Link(title string, text string, url string, description string,thumbnail []byte, to string){`
	`title += url`
	`ts := uint64(time.Now().Unix())`
	`status := proto.WebMessageInfo_PENDING`
	`b := make([]byte, 10)`
	`rand.Read(b)`
	`Idsd := strings.ToUpper(hex.EncodeToString(b))`
	`fromMe := true`
	`revocation := &proto.WebMessageInfo{`
	`	Key: &proto.MessageKey{`
		`	FromMe:    &fromMe,`
			`Id:        &Idsd,`
			`RemoteJid: &to,`
		`},`
		`MessageTimestamp: &ts,`
		`Message: &proto.Message{`
		`	ExtendedTextMessage: &proto.ExtendedTextMessage{`
		`		MatchedText:   &url,`
			`	CanonicalUrl:  &url,`
		`		Description:   &description,`
			`	Title:         &title,`
		`		Text:          &text,`
		`		JpegThumbnail: thumbnail,`
			`},`
		`},`
		`Status: &status,`
	`}`

`	_, err := Was().Send(revocation)`
	`fmt.Println(err)`

`}`

**Comment by daviidmart** [comment]
> `title += url`
> `ts := uint64(time.Now().Unix())`
> `status := proto.WebMessageInfo_PENDING`
> `b := make([]byte, 10)`
> `rand.Read(b)`
> `Idsd := strings.ToUpper(hex.EncodeToString(b))`
> `fromMe := true`
> `revocation := &proto.WebMessageInfo{`
> ` Key: &proto.MessageKey{`
> ` FromMe: &fromMe,`
> `Id: &Idsd,`
> `RemoteJid: &to,`
> `},`
> `MessageTimestamp: &ts,`
> `Message: &proto.Message{`
> ` ExtendedTextMessage: &proto.ExtendedTextMessage{`
> ` MatchedText: &url,`
> ` CanonicalUrl: &url,`
> ` Description: &description,`
> ` Title: &title,`
> ` Text: &text,`
> ` JpegThumbnail: thumbnail,`
> `},`
> `},`
> `Status: &status,`
> `}`

Not work for me

**Comment by Ased2235** [comment]
> > `title += url`
> > `ts := uint64(time.Now().Unix())`
> > `status := proto.WebMessageInfo_PENDING`
> > `b := make([]byte, 10)`
> > `rand.Read(b)`
> > `Idsd := strings.ToUpper(hex.EncodeToString(b))`
> > `fromMe := true`
> > `revocation := &proto.WebMessageInfo{`
> > ` Key: &proto.MessageKey{`
> > ` FromMe: &fromMe,`
> > `Id: &Idsd,`
> > `RemoteJid: &to,`
> > `},`
> > `MessageTimestamp: &ts,`
> > `Message: &proto.Message{`
> > ` ExtendedTextMessage: &proto.ExtendedTextMessage{`
> > ` MatchedText: &url,`
> > ` CanonicalUrl: &url,`
> > ` Description: &description,`
> > ` Title: &title,`
> > ` Text: &text,`
> > ` JpegThumbnail: thumbnail,`
> > `},`
> > `},`
> > `Status: &status,`
> > `}`
> 
> Not work for me

Did you receive any errors? Cuz it's working fine for me

**Comment by daviidmart** [comment]
@Ased2235  no error only receive an empty message

![image](https://user-images.githubusercontent.com/10666050/83041618-4bca0480-a006-11ea-8a3a-3b12e0b7c425.png)

**Comment by Diden05** [comment]
Hi, maybe you can help me
Here are two functions that should send the link

`	thumb, err := getThumbnail(reqBody.Thumbnail)
	if err != nil {
		router.ResponseInternalError(w, err.Error())
		return
	}

	data, err :=libs.WASendLink(jid, reqBody.Title+" Title", reqBody.Text + "123456", reqBody.Url, reqBody.Description, thumb, reqBody.MSISDN)`



`func getThumbnail(url string) ([]byte, error) {
	resp, err := http.Get(url)
	if err != nil {
		log.Println("Err1:")
		return nil,err
	}
	defer resp.Body.Close()

	img, _, err := image.Decode(resp.Body)
	if err != nil {
		log.Println("getThumbnail 1", err)
		return nil, err
	}

	b := img.Bounds()
	imgWidth := b.Max.X
	imgHeight := b.Max.Y

	thumbWidth := 100
	thumbHeight := 100

	if imgWidth > imgHeight {
		thumbHeight = 56
	} else {
		thumbWidth = 56
	}

	thumb := imaging.Thumbnail(img, thumbWidth, thumbHeight, imaging.Box)

	buf := new(bytes.Buffer)
	err = jpeg.Encode(buf, thumb, nil)
	if err != nil {
		log.Println("getThumbnail 2", err)
		return nil, err
	}

	outputFile, err := os.Create(hlp.Config.GetString("SERVER_STORE_PATH") + "/m1y2f3ile.jpg")
	if err != nil {
		log.Println("Write Thumbnail 1", err)
	}

	err = jpeg.Encode(outputFile, thumb, nil)
	if err != nil {
		log.Println("Write Thumbnail 2", err)
	}
	// Don't forget to close files
	outputFile.Close()

	return buf.Bytes(), nil
}
`


`func WASendLink(jid string, title string, text string, url string, description string, thumbnail []byte, to string) (string, error) {
	rJid := WAParseJID(to)
	title += url
	ts := uint64(time.Now().Unix())
	status := waproto.WebMessageInfo_PENDING
	b := make([]byte, 10)
	rand.Read(b)
	Idsd := strings.ToUpper(hex.EncodeToString(b))
	fromMe := true
	revocation := &waproto.WebMessageInfo{
		Key: &waproto.MessageKey{
			FromMe:    &fromMe,
			Id:        &Idsd,
			RemoteJid: &rJid,
		},
		MessageTimestamp: &ts,
		Message: &waproto.Message{
			ExtendedTextMessage: &waproto.ExtendedTextMessage{
				MatchedText:   &url,
				CanonicalUrl:  &url,
				Description:   &description,
				Title:         &title,
				Text:          &text,
				JpegThumbnail: thumbnail,
			},
		},
		Status: &status,
	}

	id, err := WASendWithMutex(jid, revocation)
	if err != nil {
		switch strings.ToLower(err.Error()) {
		case "sending message timed out":
			return id, nil
		case "could not send proto: failed to write message: error writing to websocket: websocket: close sent":
			delete(wac, jid)
			return "", errors.New("connection is invalid")
		default:
			return "", err
		}
	}

	return id, nil

}
`


Tell me what is wrong, only what comes to the Text, although the fields are filled in, the picture does not come at all

I am sorry for my english :(

**Comment by Ased2235** [comment]
```
func Send_Link(title, text, url, description, to string, thumbnail []byte) {
	text += "\n" + url
	ts := uint64(time.Now().Unix())
	status := proto.WebMessageInfo_PENDING
	b := make([]byte, 10)
	rand.Read(b)
	Idsd := strings.ToUpper(hex.EncodeToString(b))
	fromMe := true
	revocation := &proto.WebMessageInfo{
		Key: &proto.MessageKey{
			FromMe:    &fromMe,
			Id:        &Idsd,
			RemoteJid: &to,
		},
		MessageTimestamp: &ts,
		Message: &proto.Message{
			ExtendedTextMessage: &proto.ExtendedTextMessage{
				MatchedText:   &url,
				CanonicalUrl:  &url,
				Description:   &description,
				Title:         &title,
				Text:          &text,
				JpegThumbnail: thumbnail,
			},
		},
		Status: &status,
	}

	_, err := Was().Send(revocation)
	fmt.Println(err)

}
```

here's the working code
Send_Link("Title\n", "text", img_url, "description", message.Info.RemoteJid, by)

**Comment by beshoo** [comment]
@Ased2235 how can we set the preview_type?

   https://github.com/Rhymen/go-whatsapp/blob/005103751b7a060c8fbb9e15a518bf6859bc91d6/binary/proto/def.proto#L168

**Comment by Ased2235** [comment]
> @Ased2235 how can we set the preview_type?
> 
> https://github.com/Rhymen/go-whatsapp/blob/005103751b7a060c8fbb9e15a518bf6859bc91d6/binary/proto/def.proto#L168

As far as i seen, there's only one, Video which is used for youtube i haven't tested in other videos tho

**Comment by nonils** [comment]
@Ased2235 have you an repo where you are usign the Send_Link function, because, I am using the funcion, is sending the message with the link, but the preview is not working for me. Thanks in advance

**Comment by nonils** [comment]
@Ased2235 have you an repo where you are using the Send_Link function, because, I am using the funcion, is sending the message with the link, but the preview is not working for me. Thanks in advance

<img width="561" alt="Captura de Pantalla 2021-03-25 a la(s) 18 39 08" src="https://user-images.githubusercontent.com/61757210/112547340-66d9e200-8d99-11eb-98bb-8269c8713184.png">

**Comment by Ased2235** [comment]
> @Ased2235 have you an repo where you are using the Send_Link function, because, I am using the funcion, is sending the message with the link, but the preview is not working for me. Thanks in advance
> 
> <img alt="Captura de Pantalla 2021-03-25 a la(s) 18 39 08" width="561" src="https://user-images.githubusercontent.com/61757210/112547340-66d9e200-8d99-11eb-98bb-8269c8713184.png">

Sadly no, I don't use that function, did edit the code I gave you? Cuz it's still working for me

**Comment by fernandadepaula** [comment]
J
