### ISSUE TITLE
Full Chat History - Max 3 years

### ISSUE THREAD

**Issue by steffenpelmer** [Rhymen/go-whatsapp#371]
Hi,

I'm trying to get a full history of some WhatsApp group chats.
These chats are big old groups with over 1000 files of media.

I was able to get it work with the functions "GetHistory" --> "LoadFullChatHistory". But the chats are not complete. It looks like this: 
All Images and Videos older than 3 years are missing. Today is the 22.05.20 and the last files from 2 different groups stopped loading around 22.05.2017. 
I know, that these groups have older media files, which don't show up.

The text messages are complete.

Is there any known max limit or time limit? I can still load these media files on my iPhone.

**Comment by SchulteMK** [comment]
Can you load the media files on [WAWeb](https://web.whatsapp.com/)?
I currently don't have chats this old to test it.

**Comment by steffenpelmer** [comment]
Yes, i can load the media.
