### ISSUE TITLE
Authorization without scanning a QR code

### ISSUE THREAD

**Issue by Spocher** [Rhymen/go-whatsapp#372]
Hi everyone, it’s possible that you wouldn’t be authorized by QR code, but as in the original application, enter the number and confirm with the code from SMS?

**Comment by beshoo** [comment]
No way.

**Comment by tulir** [comment]
This library is for the web app API, which links to your phone and is authorized with the QR code.

There are other libraries like [yowsup](https://github.com/tgalal/yowsup) that use the client API and thus log in with SMS, but WhatsApp tends to ban you immediately if you try to use those.
