### ISSUE TITLE
I'm not able to restore the session: restoring failed: admin login responded with 403

### ISSUE THREAD

**Issue by tguimmaraess** [Rhymen/go-whatsapp#378]
I'm getting the following error when trying to restore the session: 

`restoring failed: admin login responded with 403`

My login:

```
import (
	"fmt"
	"github.com/Baozisoftware/qrcode-terminal-go"
	"github.com/Rhymen/go-whatsapp"
	"os"
	"time"
)

func main() {
	wac, err := whatsapp.NewConn(20 * time.Second)
         wac.SetClientVersion(2, 2021, 4)

	if err != nil {
		panic(err)
	}

	qr := make(chan string)
	go func() {
		terminal := qrcodeTerminal.New()
		terminal.Get(<-qr).Print()
	}()

	session, err := wac.Login(qr)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error during login: %v\n", err)
	}
	fmt.Printf("login successful, session: %v\n", session)
}
```
I don't know how to save the session tho. 

I'm using this code for restoring the session: https://github.com/Rhymen/go-swhatsapp/tree/master/examples/restoreSession

The session seems to be saved (otherwise I would get a different error) tho but I'm not sure as I can't see any session file and the documentation says I have to implement the function save session myself like os.TempDir(sess) but I don't know how to do it; as result I'm unable to restore the session.

This part of the code is giving me the error:

```
	session, err = wac.RestoreWithSession(session)
		if err != nil {
			return fmt.Errorf("restoring failed: %v\n", err)
		}

```
If somebody could give me an example on how to save and restore the session I would be very much appreciated.

**Comment by adarosci** [comment]
add in your connection and see if it resolves!

wac.SetClientName("Mac OS", "Chrome", "10.15.4")

**Comment by tguimmaraess** [comment]
Thank you for yor reply. I still get the same error. I heard it's related to the token but I don't know how to save and restore it.

**Comment by ramacatur** [comment]
Remove your session file and try rescan qrcode.

**Comment by tguimmaraess** [comment]
> Remove your session file and try rescan qrcode.
@ramacatur , thank you for your reply. I'm beginner in Go Lang to be honest and this library is also new to me . Where the session file lies? Wouldn't I have to save session in a temp file using  the `os.TempDir()` function or something like this or it's generated automatically?

**Comment by ramacatur** [comment]
>  > Remove your session file and try rescan qrcode.
>  @ramacatur,  thank you for your reply. I'm beginner in Go Lang to be honest and this library is also new to me . Where the session file lies? Wouldn't I have to save session in a temp file using  the `os.TempDir()`  function or something like this or it's generated automatically? Like the documentation says I have to implement the save session function myself like adding `os.TempDir(sess`) or something after the login. I can't see any session file by the way. I'm looking for a folder called temp or a file called whatsapp.gob I can't find any.
> 
> 
> Update:
> 
> I solved the problem by using this code  https://github.com/Rhymen/go-whatsapp/tree/master/examples/sendTextMessages instead of my regular login code (because it has a function to save the session) , commenting the session verification code and logging in again, I uncommented the code afterwards and now it works. It seems like it overwrote the session file but I still don't know where the session file is located tho. Thank you very much anyway, you helped a lot.

Check your tmpdir with

`echo $TMPDIR
`

**Comment by tguimmaraess** [comment]
> > > Remove your session file and try rescan qrcode.
> > > @ramacatur,  thank you for your reply. I'm beginner in Go Lang to be honest and this library is also new to me . Where the session file lies? Wouldn't I have to save session in a temp file using  the `os.TempDir()`  function or something like this or it's generated automatically? Like the documentation says I have to implement the save session function myself like adding `os.TempDir(sess`) or something after the login. I can't see any session file by the way. I'm looking for a folder called temp or a file called whatsapp.gob I can't find any.
> > 
> > 
> > Update:
> > I solved the problem by using this code  https://github.com/Rhymen/go-whatsapp/tree/master/examples/sendTextMessages instead of my regular login code (because it has a function to save the session) , commenting the session verification code and logging in again, I uncommented the code afterwards and now it works. It seems like it overwrote the session file but I still don't know where the session file is located tho. Thank you very much anyway, you helped a lot.
> 
> Check your tmpdir with
> 
> `echo $TMPDIR `

I got this (I don't know what it means I can't find any tmp folder):

![tmp](https://user-images.githubusercontent.com/61233338/83256273-8b205e80-a188-11ea-8f18-3be8d83c73c2.png)
By the way I'm doing tests and now I'm trying to send an image but i get that error as you can see on the screenshot. I'm aware of the solution you found https://github.com/Rhymen/go-whatsapp/pull/364 however I'm not able to get it working as it imports directly from github which hasn't been updated yet. What should I do? Bare with me please i'm a completely beginner.

**Comment by ramacatur** [comment]
Find your GOPATH. Check `go version` for detail. 

After you find GOPATH, next find `src/github.com/Rhymen/go-whatsapp`

Edit file `media.go`

**Comment by tguimmaraess** [comment]
> Find your GOPATH. Check `go version` for detail.
> 
> After you find GOPATH, next find `src/github.com/Rhymen/go-whatsapp`
> 
> Edit file `media.go`

Thank you

`go version go1.14.3 windows/amd64`

I did a `echo $GOPATH`  and I found my Go path as well as I have edited the file media.go file but the import is still `"github.com/Rhymen/go-whatsapp"` how can I import the files in the src folder instead?

**Comment by ramacatur** [comment]
> 
> > Find your GOPATH. Check `go version` for detail.
> > 
> > After you find GOPATH, next find `src/github.com/Rhymen/go-whatsapp`
> > 
> > Edit file `media.go`
> 
> Thank you
> 
> `go version go1.14.3 windows/amd64`
> 
> I did a `echo $GOPATH`  and I found my Go path as well as I have edited the file `media.go` file but the import is still `"github.com/Rhymen/go-whatsapp"` how can I import the files in the src folder instead? Should I just put the path there? Like` import ("C:\Users\thiag\go\src\github.com\Rhymen\go-whatsapp")`  ?
> 
> 

Try run. It works or not?

**Comment by tguimmaraess** [comment]
> > > Find your GOPATH. Check `go version` for detail.
> > > After you find GOPATH, next find `src/github.com/Rhymen/go-whatsapp`
> > > Edit file `media.go`
> > 
> > 
> > Thank you
> > `go version go1.14.3 windows/amd64`
> > I did a `echo $GOPATH`  and I found my Go path as well as I have edited the file `media.go` file but the import is still `"github.com/Rhymen/go-whatsapp"` how can I import the files in the src folder instead? Should I just put the path there? Like` import ("C:\Users\thiag\go\src\github.com\Rhymen\go-whatsapp")`  ?
> 
> Try run. It works or not?

It didn't work.

**Comment by ramacatur** [comment]
Sorry for the late response. Does your problem have a solution?

**Comment by tguimmaraess** [comment]
> Sorry for the late response. Does your problem have a solution?

No problem. I'm very grateful for your attention. Thank you once again.

So, I'm still running into the same trouble. I believe that I'm doing something wrong. I think that I'm editing the wrong file, in the wrong path because even when I delete the whole `github.com` folder and files located in `C:\Users\myuser\go`, the main.go still works.  It means it's importing from elsewhere? But where? I don't understand it. 

 I have two Go paths:
 `C:\Users\myuser\go` (the github.com folder was automatically created in this path)

and 

`C:\Go`

I removed the github folder from  `C:\Users\myuser\go` but the `main.go`  still works. I don't know what the problem could be but it seems like it's importing from somewhere else, that's why the changes I make to the `media.go` file don't take effect.

**Comment by ramacatur** [comment]
For default, import will be use path src in $GOPATH, for example if you use `import "github.com/Rhymen/go-whatsapp"`, its means `$GOPATH/src/github.com/Rhymen/go-whatsapp`.

I thing you use go mod for this case. If you use go mod, when you run main.go, it will download package you need like go-whatsapp, and it will create folder github.com/Rhymen/go-whatsapp beside file main.go. Try edit file media.go in this package. I hope it will help you.

Sorry for my language.

**Comment by tguimmaraess** [comment]
Yes indeed I'm using go mod. I opened this file and i got this:

module bot

go 1.14

```
require (
	github.com/Baozisoftware/qrcode-terminal-go v0.0.0-20170407111555-c0650d8dff0f
	github.com/Rhymen/go-whatsapp v0.1.0
	github.com/gorilla/websocket v1.4.0
	github.com/pkg/errors v0.8.1
)
```

But I don't see any `github.com` folder.

I have checked my GOPATH I removed the gibthub folder from there (as I told you)  but still works.
So I changed media.go file in this path `C:\Users\myuser\go\pkg\mod\github.com\!rhymen\go-whatsapp@v0.1.0` and now it works but the media.go file was outdated (I don't know why. Maybe because it downloads the old version), I had to copy the `media.go` file from the previous one I had downloaded, but anyway, thank you very much!

By the way, what do you recommend me to use? Go mod or regular installation folder?
