### ISSUE TITLE
How share live location??

### ISSUE THREAD

**Issue by daviidmart** [Rhymen/go-whatsapp#379]
`wac.Send(whatsapp.LiveLocationMessage{
        Info: whatsapp.MessageInfo{
		RemoteJid: message.Info.RemoteJid,
	},
	AccuracyInMeters: 1,
	DegreesLongitude: -102.3437216,
	DegreesLatitude:  21.9605259,
	SequenceNumber:   1,
})`

![image](https://user-images.githubusercontent.com/10666050/83188932-0ab11d80-a0f6-11ea-9774-167a4446f9e3.png)

**Comment by beshoo** [comment]
Thank you
