### ISSUE TITLE
Replying to another message

### ISSUE THREAD

**Issue by Leonardo-Crespo** [Rhymen/go-whatsapp#382]
Is not working.
	

               quotedMessage := proto.Message{
		Conversation: &previousMessage,
	}

	ContextInfo := whatsapp.ContextInfo{
		QuotedMessage:   &quotedMessage,
		QuotedMessageID: "",
		Participant:     "", //Whot sent the original message
	}

	wppmsg := whatsapp.TextMessage{
		Info: whatsapp.MessageInfo{
			RemoteJid: remoteJid,
		},
		ContextInfo: ContextInfo,
		Text:        text,
	}

**Comment by tguimmaraess** [comment]
https://github.com/Rhymen/go-whatsapp/pull/217

**Comment by RafaelIngenium** [comment]
When upgrading to a newer version Reply to a message (also known as "Quoted message") Not working stopped working.
Someone with the same problem?
