### ISSUE TITLE
How do I get the Participant properties? Creator, admin, participant...

### ISSUE THREAD

**Issue by tguimmaraess** [Rhymen/go-whatsapp#384]
Hello. I wanted to get the participant properties. I tried to get the participant ID (not the RemoteJid but the SenderJid) and I got an error but I found out how to get the participant ID, but now I wanted to get the participant's properties, like, I want to know whether a participant is an admin or not.
Could somebody please help me?

Thank you in advance.

**Comment by mapodesta** [comment]
@tguimmaraess  send me an email : mathias643@gmail.com

**Comment by ramacatur** [comment]
What do you mean participants in group?  Check group.go, there is GetMetadata function.

**Comment by tguimmaraess** [comment]
> What do you mean participants in group? Check group.go, there is GetMetadata function.

I mean how can I identify whether a participant is an admin, or a regular member?

**Comment by ramacatur** [comment]
This is from incoming message group?

**Comment by tguimmaraess** [comment]
> This is from incoming message group?

Yes.

**Comment by ramacatur** [comment]
> > What do you mean participants in group? Check group.go, there is GetMetadata function.
> 
> @ramacatur I mean how can I identify whether a participant is an admin, or a regular member? Thank you for your reply.
> I have tried contacts.go and store.go. but I can't find anything related to this. I noticed the the file token.go has these properties but I don't know how to get them.
> 
> I'm using these to get the participant ID  but I would like to know how I get its "properties" 
> 
> ```
> message.Info.Source.GetParticipant()
> message.ContextInfo.Participant
> ```
> 

May be try use function `GetGroupMetaData` in group.go and you will get json data participants. In data participants, you will found IsAdmin and IsSuperAdmin in bool type.

**Comment by tguimmaraess** [comment]
> > > What do you mean participants in group? Check group.go, there is GetMetadata function.
> > 
> > 
> > @ramacatur I mean how can I identify whether a participant is an admin, or a regular member? Thank you for your reply.
> > I have tried contacts.go and store.go. but I can't find anything related to this. I noticed the the file token.go has these properties but I don't know how to get them.
> > I'm using these to get the participant ID  but I would like to know how I get its "properties"
> > ```
> > message.Info.Source.GetParticipant()
> > message.ContextInfo.Participant
> > ```
> 
> May be try use function `GetGroupMetaData` in group.go and you will get json data participants. In data participants, you will found IsAdmin and IsSuperAdmin in bool type.
Oh thank you very much. That's what I needed to know! Thank you.

**Comment by arisawali2014** [comment]
![gambar](https://user-images.githubusercontent.com/31904944/89278521-6ce74b00-d670-11ea-9f2b-813ae8716646.png)
i try do this but ended getting this.. 
![gambar](https://user-images.githubusercontent.com/31904944/89278544-72dd2c00-d670-11ea-9de0-8c9f9943d744.png)

**Comment by ramacatur** [comment]
> ![gambar](https://user-images.githubusercontent.com/31904944/89278521-6ce74b00-d670-11ea-9f2b-813ae8716646.png)
> i try do this but ended getting this..
> ![gambar](https://user-images.githubusercontent.com/31904944/89278544-72dd2c00-d670-11ea-9de0-8c9f9943d744.png)

It is output pointer. You can use `fmt.Println(*gmeta)`

**Comment by Ased2235** [comment]
> ![gambar](https://user-images.githubusercontent.com/31904944/89278521-6ce74b00-d670-11ea-9f2b-813ae8716646.png)
> i try do this but ended getting this..
> ![gambar](https://user-images.githubusercontent.com/31904944/89278544-72dd2c00-d670-11ea-9de0-8c9f9943d744.png)

It's a chan so use <-gmta
