### ISSUE TITLE
Getting status 400 on writeJson

### ISSUE THREAD

**Issue by Ased2235** [Rhymen/go-whatsapp#385]
I got this from Chrome  `["query","InvitedGroupMetadata",{"from":"xxxx@c.us","admin":"XXXX@c.us",
	"code":"1Z2Px3wMUVPXkpAf","expiration":"1591452276","gid":"XXXX-1591192999@g.us"}]` 
so i tired something like this

`type s struct {`
	`From       string `json:"from"``
	`Admin      string `json:"admin"``
	`Code       string `json:"code"``
	`Expiration string `json:"expiration"``
	`Gid        string `json:"gid"``
`}`

`re, _ := json.MarshalIndent(d, "", "  ")`
	`data := []interface{}{"query", "InvitedGroupMetadata", string(re)}`
        `fmt.Println(data)`
	`wac.writeJson(data)`

And the result is this
`[query InvitedGroupMetadata {`
  `"from": "xxxx@c.us",`
  `"admin": "xxx@c.us",`
  `"code": "1Z2Px3wMUVPXkpAf",`
  `"expiration": "1591452276",`
 ` "gid": "xxx-1591192999@g.us"`
`}]`
`{"status":400}`

Can anyone tell me what i'm going wrong?

**Comment by beshoo** [comment]
Is this a binary data you catch from a chrome socket?
If yes, how did you log it

**Comment by Ased2235** [comment]
> Is this a binary data you catch from a chrome socket?
> If yes, how did you log it

I got it from network tab in Developer Tools

**Comment by beshoo** [comment]
@Ased2235  so you have it as a string in the WS window not encoded !

**Comment by Ased2235** [comment]
> @Ased2235 so you have it as a string in the WS window not encoded !

Yes but I couldn't send it, can you tell me why?

**Comment by beshoo** [comment]
@SchulteMK What do you think why some post to WhatsApp is not going through!
