### ISSUE TITLE
 Group message

### ISSUE THREAD

**Issue by Mateus-pilo** [Rhymen/go-whatsapp#386]
How do I know that a message has been received from a group and how to deal with not receiving these messages, any solution for that?

Regard .

**Comment by tguimmaraess** [comment]
You have to check the message ID. Group ids end with @g.us

**Comment by ramacatur** [comment]
In handle incoming message, check JID. If JID have "-", its is message from group.

**Comment by Mateus-pilo** [comment]
Nice @ramacatur Thanks
