### ISSUE TITLE
Panic last commit

### ISSUE THREAD

**Issue by ftomza** [Rhymen/go-whatsapp#388]
```
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x928465]
Jun 09 12:20:26 pbx run.sh[67532]: goroutine 11 [running]:
Jun 09 12:20:26 pbx run.sh[67532]: sync.(*Mutex).Lock(...)
Jun 09 12:20:26 pbx run.sh[67532]:         /opt/hostedtoolcache/go/1.13.12/x64/src/sync/mutex.go:74
Jun 09 12:20:26 pbx run.sh[67532]: github.com/Rhymen/go-whatsapp.(*Conn).write(0xc0000c4000, 0x1, 0xc0000294d0, 0xe, 0xc0003cb5c0, 0x3e, 0x40, 0xa67100, 0xc0002dde10, 0xc0001630f8)
Jun 09 12:20:26 pbx run.sh[67532]:         /home/runner/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200604063454-9b4bc38abf9f/write.go:130 +0x45
Jun 09 12:20:26 pbx run.sh[67532]: github.com/Rhymen/go-whatsapp.(*Conn).writeJson(0xc0000c4000, 0xc0004e80f0, 0x3, 0x3, 0x0, 0x0, 0x0)
Jun 09 12:20:26 pbx run.sh[67532]:         /home/runner/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200604063454-9b4bc38abf9f/write.go:33 +0x353
Jun 09 12:20:26 pbx run.sh[67532]: github.com/Rhymen/go-whatsapp.(*Conn).Exist(0xc0000c4000, 0xc00038f8c0, 0x1b, 0x0, 0x0, 0xc00010af00)
Jun 09 12:20:26 pbx run.sh[67532]:         /home/runner/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200604063454-9b4bc38abf9f/contact.go:91 +0xbe
```

**Comment by ramacatur** [comment]
> ```
>  [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x928465]
> Jun 09 12:20:26 pbx run.sh[67532]: goroutine 11 [running]:
> Jun 09 12:20:26 pbx run.sh[67532]: sync.(*Mutex).Lock(...)
> Jun 09 12:20:26 pbx run.sh[67532]:         /opt/hostedtoolcache/go/1.13.12/x64/src/sync/mutex.go:74
> Jun 09 12:20:26 pbx run.sh[67532]: github.com/Rhymen/go-whatsapp.(*Conn).write(0xc0000c4000, 0x1, 0xc0000294d0, 0xe, 0xc0003cb5c0, 0x3e, 0x40, 0xa67100, 0xc0002dde10, 0xc0001630f8)
> Jun 09 12:20:26 pbx run.sh[67532]:         /home/runner/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200604063454-9b4bc38abf9f/write.go:130 +0x45
> Jun 09 12:20:26 pbx run.sh[67532]: github.com/Rhymen/go-whatsapp.(*Conn).writeJson(0xc0000c4000, 0xc0004e80f0, 0x3, 0x3, 0x0, 0x0, 0x0)
> Jun 09 12:20:26 pbx run.sh[67532]:         /home/runner/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200604063454-9b4bc38abf9f/write.go:33 +0x353
> Jun 09 12:20:26 pbx run.sh[67532]: github.com/Rhymen/go-whatsapp.(*Conn).Exist(0xc0000c4000, 0xc00038f8c0, 0x1b, 0x0, 0x0, 0xc00010af00)
> Jun 09 12:20:26 pbx run.sh[67532]:         /home/runner/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200604063454-9b4bc38abf9f/contact.go:91 +0xbe
> ```

can you give an explanation?

**Comment by ftomza** [comment]
I 'm sorry that I didn't write right away, I was looking for a problem. I understand that this started to appear after updating dependencies.

github.com/golang/protobuf v1.3.5 -> github.com/golang/protobuf v1.4.2

**Comment by SchulteMK** [comment]
I cannot imagine a relation between these dependency upgrades and your problem with the mutex.
Can you try to downgrade and test if the isse still presists?
