### ISSUE TITLE
Best API for WhatsApp

### ISSUE THREAD

**Issue by chatapi99** [Rhymen/go-whatsapp#39]
Have You Checked Chat-API?
----------------
- Easy to Use
- One of the best API for WhatsApp with WA2.0 Protocol.
- Latest Android Environment
- All Required Functions and Features
- No More Blocking
- Sample Bot
- Well Documented
----------------
Try Now On

https://chat-api.net

**Comment by asamsulfat** [comment]
Please close this issue

**Comment by LuaWaltzer** [comment]
Reported him.
