### ISSUE TITLE
After restoring the session, Handle* methods are triggered for old messages

### ISSUE THREAD

**Issue by KaanSK** [Rhymen/go-whatsapp#392]
As the title implies, after restoring a session old messages are triggering handle methods as if they are new messages. What is the reason and what could be the solution for this? My expectation is that after restoring a session, Handle* methods should only trigger for new messages.

**Comment by gabstv** [comment]
I believe that this is what `web.whatsapp` sends to the connected session. At least that's what the webapp uses to render the Whatsapp Web screen right after it authenticates

**Comment by beshoo** [comment]
That is completely fine. You have to check the timestamp.
As following 


	```
if message.Info.Timestamp < wh.startTime {
		return
	}

```

**Comment by KaanSK** [comment]
Thanks for the answers. I also thought about the same and implemented a custom logic to check timestamps. As a side effect, I wouldnt be able to get the emails in the period of application being not active but thats a trade-off I'm willing to take. Otherwise, I guess, I need to maintain a simple database with MessageIDs.
