### ISSUE TITLE
Tracking not working

### ISSUE THREAD

**Issue by 0xhex** [Rhymen/go-whatsapp#395]
is there a general issue about whatsapp?
online & offline last seen data

**Comment by beshoo** [comment]
I don't understand what you mean

**Comment by 0xhex** [comment]
if you check it out whatsapp online offline status not working you will see what i tell you.

**Comment by beshoo** [comment]
Yes it is general problem.... WhatsApp working on it

**Comment by 0xhex** [comment]
any progress or news about this issue?

**Comment by beshoo** [comment]
I will contact Facebook for you😅

**Comment by beshoo** [comment]
We fixed the issue 😅
