### ISSUE TITLE
How get battery percentage?

### ISSUE THREAD

**Issue by brunoferreiras** [Rhymen/go-whatsapp#396]
It is currently possible to obtain the battery percentage when connecting the device:
`wac.info.Battery # percentage of battery`

However, over time this information is not updated.

Is there a way to get the battery percentage without having to restart the process?

Any idea how I can do it?

**Comment by beshoo** [comment]
Updated session

**Comment by brunoferreiras** [comment]
@beshoo Isn't that the same thing as restarting the process?

**Comment by beshoo** [comment]
Yes.... True

**Comment by brunoferreiras** [comment]
I will assume that it is not possible to do this without restarting the process.

**Comment by Romerito007** [comment]
> Assumirei que não é possível fazer isso sem reiniciar o processo.

Implements an event handler to hear the battery status, WhatsApp sends every 2 minutes.
https://github.com/Rhymen/go-whatsapp/blob/master/handler.go#L375

`if message.Description == "action" {
	if con, ok := message.Content.([]interface{}); ok {
		//////////////////////////
	} else if con, ok := message.Content.([]binary.Node); ok {
		for a := range con {
			if con[a].Description == "battery" {
				wac.handle(baterry) ////// Implements an event handler to hear percentage of the battery,
			}
		}
	}
} else if message.Description == "response" && message.Attributes["type"] == "contacts" {
	////////////////////////
} else if message.Description == "response" && message.Attributes["type"] == "chat" {
	//////////////////////////
}`

**Comment by brunoferreiras** [comment]
@Romerito007 Thanks for the sugestion
