### ISSUE TITLE
How to set recipient of the text message? 

### ISSUE THREAD

**Issue by asamsulfat** [Rhymen/go-whatsapp#40]
When I try sent message, It sent to my number.

How to set it to my other friend number?

**Comment by LuaWaltzer** [comment]
Asamsulfat, Whatsapp uses a JID system for user identification. Look at this code fragment from the README.md.

```go
text := whatsapp.TextMessage{
    Info: whatsapp.MessageInfo{
        RemoteJid: "0123456789@s.whatsapp.net",
    },
    Text: "Hello Whatsapp",
}

err := wac.Send(text)
```
Please take note of the RemoteJid line. If you want to sent a message to somebody else, put their Jid here, or if you want to send a message to a group put its Jid there.

A persons Jid is structured like this: [phonenumber without + or 00]@s.whatsapp.net.
A group: [phonenumber of creator without + or 00]-[time of creation in UNIX]@g.us

Hope it helps,

Walthzer

**Comment by asamsulfat** [comment]
my fr number
0813 2708 5596

my countery number +62 (Indonesia)
So I remove 0 and +62

and
RemoteJid: "81327085596@s.whatsapp.net"

but it was sent to my own number, not my friend number.

**Comment by asamsulfat** [comment]
Wow this is awesome, thank you very much.

**Comment by sandeepmeenuga** [comment]
Is there anyway to read our all whatsapp contacts and can retrieve respective ReoteJIDs and can send message one by one.

**Comment by Deewai** [comment]
You can retrieve you whatsapp contacts by calling 
`wac.Contacts()`
Then the contact list in wac.Store.Contacts gets updated or you can make use of an handler to handle the list of contacts after calling the function above
`func (handler Handler) HandleContactList(contacts []whatsapp.Contact) {
	fmt.Print(contacts)
}`

**Comment by sandeepmeenuga** [comment]
Thanks @Deewai , is there any way to get Profile Pic URL from the contact list?

**Comment by codenoid** [comment]
@sandeepmeenuga use `wac.GetProfilePicThumb(RemoteJid)`

**Comment by sandeepmeenuga** [comment]
Thanks @codenoid, I am pretty new for this API. could you share any doc link or anything. So, I can go through once and start using.

**Comment by andig** [comment]
> No, keep the country code, but remove the + in front of the code. > 6281327085596@s.whatsapp.net;

This should be in the readme ;)
