### ISSUE TITLE
Download again

### ISSUE THREAD

**Issue by Valdenirmezadri** [Rhymen/go-whatsapp#426]
Good Morning! 

Does anyone know a way to retrieve a message and download again the image or files?

**Comment by rhsobr** [comment]
Hi @Valdenirmezadri , i'm sure this same question was answered in previous closed issues.
I looked for but couldn't find.

Summarily, you must load an historical chat of the contact looking for the specific message. It is possible loading previous or next messages based on a known WhatsAppMessageId using those functions below:

`func (wac *Conn) LoadMessagesBefore(jid, messageId string, fromMe bool, count int) (*binary.Node, error) {
	return wac.query("message", jid, messageId, "before", strconv.FormatBool(fromMe), "", count, 0)
}

func (wac *Conn) LoadMessagesAfter(jid, messageId string, fromMe bool, count int) (*binary.Node, error) {
	return wac.query("message", jid, messageId, "after", strconv.FormatBool(fromMe), "", count, 0)
}`

**Comment by Valdenirmezadri** [comment]
how can i work with binary.Node ?

**Comment by rhsobr** [comment]
I guess in this case you'll have a `[]proto.WebMessageInfo`. However, I suggest you do some debugs and try match with any known structure.

**Comment by rhsobr** [comment]
Nice!

**Comment by beshoo** [comment]
Buy polish it and make it usable as method or function.. Etc
