### ISSUE TITLE
Unchecked nil from ParseProtoMessage

### ISSUE THREAD

**Issue by andig** [Rhymen/go-whatsapp#427]
In https://github.com/Rhymen/go-whatsapp/blob/master/handler.go#L398 the result of `ParseProtoMessage` is handed to `wac.handle`:

    if v, ok := con[a].(*proto.WebMessageInfo); ok {
        wac.handle(v)
        wac.handle(ParseProtoMessage(v))
    }

 Investigating https://github.com/Rhymen/go-whatsapp/issues/410 I've noticed a number of messages that `ParseProtoMessage` could not decrypt and hence returns nil.

**Comment by beshoo** [comment]
Please can you write a PL? And i will confirm if it correct or not

**Comment by SchulteMK** [comment]
#484
