### ISSUE TITLE
Whatsapp: UPDATED to version 2.2033.7 and DEPRECATE clientVersion 

### ISSUE THREAD

**Issue by beshoo** [Rhymen/go-whatsapp#429]
Hi.
I am using this 
**var clientVersion = "10.15.14"**

But it seems there is no clientVersion in WhatsApp Chrome! 
![image](https://user-images.githubusercontent.com/4635115/89966167-30f74b80-dc57-11ea-9e31-517e7dace0da.png)

the **[2, 2031, 4]** is not the clientVirsion !

**Comment by beshoo** [comment]
@SchulteMK ? any idea

**Comment by beshoo** [comment]
https://github.com/Rhymen/go-whatsapp/pull/431/files#diff-f2fccfb96064097b73fbe8eeae3703ee

```
Client has version 0.4.2080
Server has version 2.2033.7
New major detected 2
```

**Comment by sthales** [comment]
ClientVersion = OS Version 
Here I’m using 10.15.4 (OS X Catalina)
![1E5B9076-B608-42DC-A79E-56D71D66C38C](https://user-images.githubusercontent.com/31826331/90214795-02e94700-ddd0-11ea-9c6a-15e5b553d456.jpeg)

**Comment by beshoo** [comment]
Yes it is working but all github talking about the new update. and if you run the 
**checkNewVersion**
it will report that

**Client has version 0.4.2080
Server has version 2.2033.7
New major detected 2**

**Comment by beshoo** [comment]
> ClientVersion = OS Version
> Here I’m using 10.15.4 (OS X Catalina)
> ![1E5B9076-B608-42DC-A79E-56D71D66C38C](https://user-images.githubusercontent.com/31826331/90214795-02e94700-ddd0-11ea-9c6a-15e5b553d456.jpeg)
> 
> ![06531286-4289-4C37-A920-824678203A31](https://user-images.githubusercontent.com/31826331/90214901-5a87b280-ddd0-11ea-83e6-d41ccaf0c0e1.jpeg)

I am reffring to waVersion which located in session.go

**Comment by beshoo** [comment]
https://github.com/Rhymen/go-whatsapp/pull/431
