### ISSUE TITLE
 check if the whatsapp number is valid.

### ISSUE THREAD

**Issue by Leonardo-Crespo** [Rhymen/go-whatsapp#434]
good night, i would like to know if you have any way of validating if the number belongs to whatsapp ...
it turns out that when i have to add a number that has the "9" more **(in some Brazilian states they added the 9 to all the numbers)**, he didn’t always add the number on whatsapp with 9, is there any way to check this ?? ??

**Comment by beshoo** [comment]
```
value, err := handler.Wac.Exist(wa.WidJidFromNumber(phoneNumber))

        if err != nil {
// no whatsapp account
        }

```

**Comment by liuguangchuan** [comment]
value, err := wac.Exist("918448631207")
	if err != nil {
		// no whatsapp account
		fmt.Printf("no: %v\n", value)
	}

like this，i can‘t get  result，would you like to give me  a demo？  thank you！

**Comment by beshoo** [comment]
your phone is not correct is 

it has to be like this 918448631207@s.whatsapp.net

**Comment by biji** [comment]
For me, `err` always nil and `value` is hex like `0xc000121b60`
how to interpret that value?

thanks
