### ISSUE TITLE
Problem create sticker

### ISSUE THREAD

**Issue by renosz** [Rhymen/go-whatsapp#435]
i successed send sticker.. but sticker crash in android, but in whatsapp web is working.. how to fix it?

**Comment by maderio** [comment]
> i successed send sticker.. but sticker crash in android, but in whatsapp web is working.. how to fix it?

same problem with me

**Comment by sthales** [comment]
Works fine here. Show your code.

**Comment by maderio** [comment]
> Works fine here. Show your code.

`stickers,err := os.Open(filename)

if err != nil {
	fmt.Fprintf(os.Stderr, "error opening file: %v\n", err)
}
_, err = client.wac.Send(whatsapp.StickerMessage{
	Info: whatsapp.MessageInfo{
		RemoteJid: message.Info.RemoteJid,
	},
	Type: "image/webp",
	Content: stickers,
})
if err != nil {
	fmt.Fprintf(os.Stderr, "error sending stickers: %v\n", err)
}`

**Comment by zharazhar17** [comment]
the solution is to make a variable, for example i = 0 and when in the handler or play it is given i ++, if the number of the trial reading session is> 10 os.Exit ()

success this way
