### ISSUE TITLE
How to use Android to scan and log in? 

### ISSUE THREAD

**Issue by liuguangchuan** [Rhymen/go-whatsapp#436]
How to use Android to scan and log in? please help me ，thanks！

**Comment by renosz** [comment]
same.. i dont know how to login in 1 device

**Comment by ramacatur** [comment]
Print QrCode and scan with your device.

**Comment by beshoo** [comment]
You need to ask the API to give you the Base64 QR code, then pass it via socket to your html page using sket.io

        ```
go func() {
                sessionID := params.SessionID.String()
                handler, err := wa.Login(qr, params.ProxyURL, sessionID)
                if err != nil {
                        errCh <- err
                }
                wa.Connections[sessionID] = handler
        }()

        case qrText := <-qr:
                return profile.NewScanQrOK().WithPayload(&models.QRCode{
                        Base64: qrText,
                })

        }
```

**Comment by liuguangchuan** [comment]
thank you，i will try it，hope it works

**Comment by liuguangchuan** [comment]
Hello，I still don't understand, can you add a demo, such as login, login through Android phone code scanning, I am very urgent need, the above code do not know how to use, please help me, thank you  @beshoo @Rhymen   thank you very much

**Comment by ramacatur** [comment]
> Hello，I still don't understand, can you add a demo, such as login, login through Android phone code scanning, I am very urgent need, the above code do not know how to use, please help me, thank you  @beshoo @Rhymen   thank you very much

You can use example code. Login and send Message.

**Comment by liuguangchuan** [comment]
thank you ，The demo can only be scanned with iPhone. I don't know how to scan and log in with Android phone. Would you like to help write a demo with Android phone scanning code to login and send messages，thanks very much！

**Comment by beshoo** [comment]
> thank you ，The demo can only be scanned with iPhone. I don't know how to scan and log in with Android phone. Would you like to help write a demo with Android phone scanning code to login and send messages，thanks very much！

NO WAY,You can scan the code via android and iPhone! it is not related to the device type!
