### ISSUE TITLE
please bump waVersion

### ISSUE THREAD

**Issue by denislee** [Rhymen/go-whatsapp#437]
Please bump to version 2.2035.14

I don't know how to create a pull request. 

Change file `session.go`

to this version
```
var waVersion =  []int{2, 2035, 14}
```

**Comment by denislee** [comment]
Actually I manage to create a pull request.

https://github.com/Rhymen/go-whatsapp/pull/438

**Comment by ramacatur** [comment]
I think you can use SetClientVersion to set WA Version.

**Comment by rhsobr** [comment]
> I think you can use SetClientVersion to set WA Version.

I guess WA Version could be a ENV VAR too. Each new version someone must open a new PR just to change numbers (in mostly scenarios). Does it sounds OK?

**Comment by lesmo** [comment]
> I guess WA Version could be a ENV VAR too. Each new version someone must open a new PR just to change numbers (in most scenarios). Does it sounds OK?

Maybe on initialization of WA instead of an ENV var?

**Comment by rhsobr** [comment]
```
New minor detected 2.2039.9

**Comment by beshoo** [comment]
What i did is the following to adubt each update
type version struct {
        major int
        minor int
        patch int
}
        wac, err = wa.NewConn()
        v, err := wa.CheckCurrentServerVersion()
        serverVersion := &version{major: v[0], minor: v[1], patch: v[2]}
        if err != nil {
                panic(err)
        }
        fmt.Printf("Server has version %d.%d.%d\n", serverVersion.major,
serverVersion.minor, serverVersion.patch)
        wac.SetClientVersion(serverVersion.major, serverVersion.minor,
serverVersion.patch)

**Comment by Valdenirmezadri** [comment]
Hello, how did you solve this problem
