### ISSUE TITLE
We need to understand How web whatsapp works (VERY IMPORTANT)

### ISSUE THREAD

**Issue by beshoo** [Rhymen/go-whatsapp#440]
Hi

When we open WhatsApp chrome, it creates a connection to "wss://web.whatsapp.com/ws"
Which means WhatsApp can read the messages which sent to web.whatsapp.com/ws

Now when you send a message via WhatsApp chrome, messages gos to WhatsApp, then it downloads to your phone, then your phone sent it back! 

if that true, then WhatsApp can read the messages 100%. since they have access to the kes in the local storage!
which means WhatsApp can know the server Ip Address which runs go-whatsapp, so we need to use a proxy. or WhatsApp can block the IP address
What do you think?

**Comment by lesmo** [comment]
As far as it is my understanding, an encrypted communication protocol between your phone and the web client is being created once you connect. All communication between the web client and your phone, even though traveling through WhatsApp servers, is encrypted and can only be read between these two parties.

That being said, WhatsApp could "calculate" if your client is an unofficial bot by analyzing behavior (online status, read receipts, etc.)... it's not impossible, but it's also something unheard of.

**Comment by beshoo** [comment]
The keys in localstorage, it is super easy to read it by whatsapp....

Regard

**Comment by lesmo** [comment]
Yes, I understand it is a very simple task to read that information... but that doesn't mean it's used like you say it is being used.

**Comment by beshoo** [comment]
Do you have any proof?

**Comment by sthales** [comment]
I agree with @lesmo

> The keys in localstorage, it is super easy to read it by whatsapp....
What do you mean with "it's super easy to read it by WhatsApp"?

**Comment by sthales** [comment]
The messages you send through WhatsApp Web are encrypted by the WebClient, decrypted by the phone, then re-encrypted to fit the end-to-end scheme and then sent to the recipient. Same thing the other way around.

**Comment by beshoo** [comment]
I understand but WhatsApp can easily read the key which they use to " encrypt " the messages - I can do it by my self.
I think there is a big problem, Whatsapp can read the key, save it to there servers and decrypt the messages.

How can you prove that they don't do that in any way!
They can inject a script in nay time to steal the key!

**Comment by lesmo** [comment]
> Do you have any proof?

Well... to be honest this is a fair point. I don't have proof, but do you have proof of them doing that? I could hack the CIA with my computer, but that doesn't mean I actually have the expertise for that or that I'll even  try.

They'll just have to trust I won't, and that their security measures will deter me from trying ;)

> The messages you send through WhatsApp Web are encrypted by the WebClient, decrypted by the phone, then re-encrypted to fit the end-to-end scheme and then sent to the recipient. Same thing the other way around.

Given that this is how it works, the weakest link on the chain is as you point out: the encryption key stored on the user's browser. However, there's also another weak point in that chain: the phone itself.

WhatsApp can update the App after a vetting process from Google and Apple respectively (which you can try to fool, but if caught means your app will no longer be on their stores), and they can potentially take the end-to-end encryption key, save it on their servers, and retrieve the original contents of all messages being sent.

Does that mean they do it? We can't be 100% certain, but I'm pretty confident they don't. The App even though is closed source, has a lot of eyes on it: researchers and even hacker groups are constantly auditing it for vulnerabilities. If WhatsApp transmitted and saved the encryption key generated on the phone, we would already know...

Going back to the browser, it's the same thing. We don't know for certain. I'll agree with you that there's a greater risk of that happening given that the Web app is easier to update (no third-party vetting process)... but it also has a lot of eyes on it (namely us), so the chances of them actually doing it are very slim.

Again, not impossible but very, very slim.

**Comment by beshoo** [comment]
Well, I can say with big confidence that they do it every single day but we don't know how! why I am sure?
DATA WORTH EVERYTHING even WhatsApp credibility! 

Why! My friend, it is Whatsapp. there is a service online which asks you to download an app and it will decrypt the backup database folders and show you the messages. I am not sure if WhatsApp saves the key inside the files but after this local storage, I can expect anything! 

I can agree with you that it is hard to Man In The Middle to attack WhatsApp even chrome plugins, yes they can read the key super easy   "I did it with 10 lines of code", but we can not reach the socket traffic BUT we can throw any exe app.

Via Wireshark, I can record each request in and out. and use the keys to decrypt.
 It is a problem of trust, and I don't trust Facebook after the "Cambridge Analytica" issue.

It is a very big backdoor any normal hacker can use it. 
I am not sure how som company decrypts the backup files which are already encrypted!

But ate the end of the day, What software can do, a software can undo!

Thank you so much for your replay

**Comment by lesmo** [comment]
That's a really valid standpoint, and I agree it really boils down to the chain of trust.

However, I don't think this discussion or potential actions to take are in the scope of this library. This is just an implementation of the findings from [sigalor/whatsapp-web-reveng](https://github.com/sigalor/whatsapp-web-reveng), so perhaps you'll find that more useful and perhaps this discussion makes more sense there.

**Comment by ramonck** [comment]
What I have seen overtime is that Whatsapp has behaviour mechanism analysis they look for and they pin your connection to lock you out, at least lock your session out instead of your IP. 
If your try to use something like yowsap they will ban your account in a couple of hours you can put your number in the garbage.
So yes there's some machine learning they built to do analysis behaviour on top of the eJabberd and with that they do the session flagging to lock you out or maybe ban your account if you're doing direct access without authorization like in yowsap.
It's all automatic, very impressive.
