### ISSUE TITLE
Login Not working

### ISSUE THREAD

**Issue by medicalmomcare** [Rhymen/go-whatsapp#447]
error during login: error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}

<img width="1383" alt="Screenshot 2020-09-15 at 5 42 11 PM" src="https://user-images.githubusercontent.com/70239134/93208893-eba8cb00-f77a-11ea-8448-38bd0d715f44.png">

Have the latest version of library

**Comment by beshoo** [comment]
I just scanned the QR and logged in without any problem.

**Comment by medicalmomcare** [comment]
QR-code is not printing for me in the terminal. It is throwing the above error

**Comment by beshoo** [comment]
check the client version

**Comment by medicalmomcare** [comment]
I have the following version 
var waVersion = []int{0, 3, 3324}

**Comment by beshoo** [comment]
2.2037.6

**Comment by beshoo** [comment]
2.2039.9

**Comment by beshoo** [comment]
it seems it is your client version,
Please close this issue
