### ISSUE TITLE
Upload images and Documentos error: TLS handshake timeout

### ISSUE THREAD

**Issue by borigoto** [Rhymen/go-whatsapp#454]
Hi

I have two errors when i try to send images or documents:

error sending file: image upload failed: Post https://mmh.whatsapp.net/mms/image/M81cIuZlcjLkgAFLFTHP_5F1qMCQunPbTyGdIIi6qHM=?auth=AWSp7GOVvnWMNZBXa8p-iV8SqsJO4wUwkQNlamLvEVHtweuE8eF6fQ_exEU&token=M81cIuZlcjLkgAFLFTHP_5F1qMCQunPbTyGdIIi6qHM%3D: net/http: TLS handshake timeout - 8B323E33AD34801094AA

error sending file: document upload failed: Post https://mmh.whatsapp.net/mms/document/g00KTmwREBCsUSK3FQjzwCbHG-cgXcwm9KXEXFLBg7M=?auth=AWR_bi5JXy36uF9g6sWbMl-w4bD9leHWuhuqXLijyqQlX-8o3FuhlqY-V9o&token=g00KTmwREBCsUSK3FQjzwCbHG-cgXcwm9KXEXFLBg7M%3D: dial tcp 18.184.79.173:443: i/o timeout - 5779736BE78B6678C198

Sometimes one or other. 

After some tests works, but little time stopped again.

I Tried change DNSs from navigation and see other things from network and nothing..

Somebody have this errors?

[] s

**Comment by beshoo** [comment]
it is a connection problem check your connection

**Comment by borigoto** [comment]
@beshoo , this occurred at servers on DigitalOcean.. I have other on Vultr and works fine.. i will try test on new vps.

**Comment by beshoo** [comment]
DigitalOcean has long connection problems history
https://www.google.com/search?sxsrf=ALeKk007VqumtJFQRV7SyU9oP_M8HzTyiQ:1600538765278&q=DigitalOcean+connection+timed+out&spell=1&sa=X&ved=2ahUKEwidvbbE5_XrAhXsx4UKHcwsDlsQBSgAegQIEBAl&biw=1440&bih=757

**Comment by borigoto** [comment]
i use DO for many years without problems, and have webservers, mysql, postgres, firebird, and many instances running go-whatsapp from long.. 
Well, snapshot on Vultr need long.. but, i send message when tested

**Comment by borigoto** [comment]
Okay, solved.. +-.

After migrate VPS from datacenter NYC3 to NYC1, images and documents sending ok!

TFA!

[] s
