### ISSUE TITLE
Panic!

### ISSUE THREAD

**Issue by MassiveBox** [Rhymen/go-whatsapp#458]
Hello guys, here's a fresh runtime error for you:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x792c29]

goroutine 857 [running]:
github.com/Rhymen/go-whatsapp.(*Conn).readPump.func1(0xc00016a620, 0xc00029ff40, 0xc000292c30, 0xc000292c20, 0xc0000294a0)
        /root/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.0/read.go:27 +0x29
created by github.com/Rhymen/go-whatsapp.(*Conn).readPump
        /root/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.0/read.go:26 +0x149
exit status 2
```
The werid thing is, when I open the file read.go on Github without switching to v0.1.0, lines 26 and 27 seem not to be relevant, so pheraps there's something wrong with the latest version, and a new tag should be created?
Or generally speaking, how can I import a package straight from github not caring about the tags but directly importing the package from the files on the repo?

**Comment by beshoo** [comment]
Please show us your code
