### ISSUE TITLE
 Send listened audio status

### ISSUE THREAD

**Issue by Valdenirmezadri** [Rhymen/go-whatsapp#460]
just like .Read (), have any function for sending listened audio?

**Comment by beshoo** [comment]
Interested... ♥️

**Comment by Ased2235** [comment]
You mean if they finished the audio or read it?

**Comment by beshoo** [comment]
> You mean if they finished the audio or read it?

```
Message Tag: 883.--31
got unhandled node of desc: received
Node {
    desc: "received",
    attributes: {
        "index": D571CDBD8DA66D0AC23935ECA738CC65,
        "type": played,
        "from": 966565537761@c.us,
    },
    content: None,
}

```

what is the correct function , you are the master :+1:

**Comment by Ased2235** [comment]
> > You mean if they finished the audio or read it?
> 
> ```
> Message Tag: 883.--31
> got unhandled node of desc: received
> Node {
>     desc: "received",
>     attributes: {
>         "index": D571CDBD8DA66D0AC23935ECA738CC65,
>         "type": played,
>         "from": 966565537761@c.us,
>     },
>     content: None,
> }
> ```
> 
> what is the correct function , you are the master 👍

Just to make sure, this is sent or received?

**Comment by beshoo** [comment]
Sent...

**Comment by Valdenirmezadri** [comment]
How can I debug this to develop? I do not even know where to begin with

**Comment by Romerito007** [comment]
> How can I debug this to develop? I do not even know where to begin with

I use this code, just pass the message id

`func (wac *Conn) Played(jid, id string) (<-chan string, error) {
	ts := time.Now().Unix()
	tag := fmt.Sprintf("%d.--%d", ts, wac.msgCount)

	n := binary.Node{
		Description: "action",
		Attributes: map[string]string{
			"type":  "set",
			"epoch": strconv.Itoa(wac.msgCount),
		},
		Content: []interface{}{
			binary.Node{
				Description: "received",
				Attributes: map[string]string{
					"index": id,
					"type":  "played",
					"from":  jid,
				},
				Content: "None",
			},
		},
	}

	return wac.writeBinary(n, message, ignore, tag)
}`

**Comment by Valdenirmezadri** [comment]
work like a charm

> > How can I debug this to develop? I do not even know where to begin with
> 
> I use this code, just pass the message id
> 
> `func (wac *Conn) Played(jid, id string) (<-chan string, error) {
> ts := time.Now().Unix()
> tag := fmt.Sprintf("%d.--%d", ts, wac.msgCount)
> 
> ```
> n := binary.Node{
> 	Description: "action",
> 	Attributes: map[string]string{
> 		"type":  "set",
> 		"epoch": strconv.Itoa(wac.msgCount),
> 	},
> 	Content: []interface{}{
> 		binary.Node{
> 			Description: "received",
> 			Attributes: map[string]string{
> 				"index": id,
> 				"type":  "played",
> 				"from":  jid,
> 			},
> 			Content: "None",
> 		},
> 	},
> }
> 
> return wac.writeBinary(n, message, ignore, tag)
> ```
> 
> }`
