### ISSUE TITLE
How to receive contact list in message

### ISSUE THREAD

**Issue by brunoferreiras** [Rhymen/go-whatsapp#463]
Good morning guys,
I'm in the following situation. When a contact sends a list of contacts (2 or more), those contacts do not fall into the HandleContactMessage, it is as if this message was not recognized (i received in HandleRawMessage).

When I get just one contact, it works perfectly. However, I need him to also receive it when there is a list of contacts in the same message.

Has anyone ever needed or done this?

**Comment by Valdenirmezadri** [comment]
I used this:

https://github.com/Rhymen/go-whatsapp/pull/309
