### ISSUE TITLE
AdminTest logic

### ISSUE THREAD

**Issue by Valdenirmezadri** [Rhymen/go-whatsapp#465]
Good afternoon.

I've done a lot of tests but I still have doubts about AdminTest()

I believe that I did not understand the logic behind it

When to use it, why does it exist?

**Comment by beshoo** [comment]
you don't have to use it, the API will manage that for you.
The target behind AdminTest to ping pong Whatsapp in order to keep a live connection between your server and WhatsApp server.

**Comment by rhsobr** [comment]
Hi @Valdenirmezadri ,

Open a dev tools instance of WhatsApp Web, go to Network -> WS tab and then put your cell phone in airplane mode. You'll see Admin Test in action.

**Comment by Valdenirmezadri** [comment]
> Olá @Valdenirmezadri ,
> 
> Abra uma instância de ferramentas de desenvolvimento do WhatsApp Web, vá para Rede -> aba WS e coloque seu celular no modo avião. Você verá o teste de administração em ação.


I've already done this test, my question in this case is when to start testing it

**Comment by Valdenirmezadri** [comment]
> você não precisa usá-lo, a API irá gerenciar isso para você.
> O alvo por trás do AdminTest para executar ping no WhatsApp para manter uma conexão ativa entre o seu servidor e o servidor WhatsApp.

So it does not serve to test the connection of the cell phone, but the connection of the WhatsApp server with my server?

**Comment by Valdenirmezadri** [comment]
> you don't have to use it, the API will manage that for you.
> The target behind AdminTest to ping pong Whatsapp in order to keep a live connection between your server and WhatsApp server.

So it does not serve to test the connection of the cell phone, but the connection of the WhatsApp server with my server?

**Comment by Valdenirmezadri** [comment]
> Hi @Valdenirmezadri ,
> 
> Open a dev tools instance of WhatsApp Web, go to Network -> WS tab and then put your cell phone in airplane mode. You'll see Admin Test in action.

I've already done this test, my question in this case is when to start testing it

**Comment by rhsobr** [comment]
Oh, sorry @Valdenirmezadri 

When I debugged I didn't figured out how WhatsApp Web knows that connection with cell phone is lost. But certainly, they use repeated Admin Tests to assure that.

In my usage, I ping with Admin Test after each received `Stream asleep` and also delayed intervals between 5 and 10 minutes.
With that I know when phone is really unreachable.

If you know how waking cell phone up or how being more assertive, let us know, please.

**Comment by ramacatur** [comment]
> AdminTest()

I use  AdminTest() before send message because sometimes I get error "timed out"

**Comment by Valdenirmezadri** [comment]
> Oh, sorry @Valdenirmezadri
> 
> When I debugged I didn't figured out how WhatsApp Web knows that connection with cell phone is lost. But certainly, they use repeated Admin Tests to assure that.
> 
> In my usage, I ping with Admin Test after each received `Stream asleep` and also delayed intervals between 5 and 10 minutes.
> With that I know when phone is really unreachable.
> 
> If you know how waking cell phone up or how being more assertive, let us know, please.

in which handler do you listen to streem asleep?
