### ISSUE TITLE
menssage timeout problem

### ISSUE THREAD

**Issue by leonetosoft** [Rhymen/go-whatsapp#469]
Hello good afternoon,

I get the error message timeout sporadically when the connection is slow.

I even understand that it's the connection problem.

But we have no way to control and get the message ID because it remains in Loop.

Would it be possible after the timeout error to immediately cancel the sending of this message, so that I can do it again and get an ID message?

**Comment by ramacatur** [comment]
> Hello good afternoon,
> 
> I get the error message timeout sporadically when the connection is slow.
> 
> I even understand that it's the connection problem.
> 
> But we have no way to control and get the message ID because it remains in Loop.
> 
> Would it be possible after the timeout error to immediately cancel the sending of this message, so that I can do it again and get an ID message?

I have same problem. This method maybe can help you. Before you send message, you can set id message. If you get error timed out, you can delete message with RevokeMessage function.

This is how to create message id 

```
b := make([]byte, 10)
rand.Read(b)
msgID := strings.ToUpper(hex.EncodeToString(b))
to := "xxxxxx"

msg := whatsapp.TextMessage{
		Info: whatsapp.MessageInfo{
			Id:        msgID,
			RemoteJid: to,
		},
		Text: "hey",
	}
```

**Comment by leonetosoft** [comment]
Simply splendid!
Thank you!
I will test and return here.
Currently I did a "gambiarra" to solve, send the message and assign it a timestamp, after that with the handleJsonMsg method when I verify that an ID message does not exist in my database I search it in that client's message history until I find it the timestamp that was generated earlier.
