### ISSUE TITLE
Message received with status: ERROR

### ISSUE THREAD

**Issue by brunoferreiras** [Rhymen/go-whatsapp#470]
When observing the receipt of messages, all messages received are coming with status: ERROR, but it does not impact the functioning of the library.

```json
{"key":{"remoteJid":"55XXXXXXXX@s.whatsapp.net","fromMe":false,"id":"3EB0C04EF39A0DABA9DE"},"message":{"conversation":"test"},"messageTimestamp":"1603488276","status":"ERROR"}
```

However, when using the reading mark as read, why is the message status not marked with the status: READ?
```go
handler.c.Read(message.Info.RemoteJid, message.Info.Id)
```
From what I observed, the status of the message comes only READ, when the device has the contact window open in device.

Is it possible to have the same behavior using this lib?

**Comment by kirya-dev** [comment]
Message must be encoded

**Comment by brunoferreiras** [comment]
Can you the show an example?

**Comment by DonovanDiamond** [comment]
I was having the same issue. It is not as big of a deal for me but almost all the messages I have saved show "ERROR" status.

**Comment by kirya-dev** [comment]
Hmm, its normal? In my mind must be PENDING status

**Comment by brunoferreiras** [comment]
@beshoo @Why you closed? For me, it's not resolved.

**Comment by beshoo** [comment]
The status from whatsapp and no one can control tge status of the message, or maybe your connection has to be stable.

I can not see how community can help you with this issue. 

Regard

**Comment by brunoferreiras** [comment]
I understand, I just do not agree to close without any justification.

**Comment by beshoo** [comment]
You got a notification once l closed it, and l am replying to you
justifying the closing reason.

Regard
