### ISSUE TITLE
Reply a message (aka "Quoted message") Not working

### ISSUE THREAD

**Issue by RafaelIngenium** [Rhymen/go-whatsapp#474]
When upgrading to a newer version Reply to a message (also known as "Quoted message") Not working stopped working.
Someone with the same problem?

**Comment by beshoo** [comment]
I have no problem, you have to set fromMe and the message id correctly.

Regard

**Comment by RafaelIngenium** [comment]
In the previous version it worked. Was there a change in the parameters?

**Comment by beshoo** [comment]
We dont touch it at all.

**Comment by RafaelIngenium** [comment]
Thank you, I will review here what can be.

**Comment by RafaelIngenium** [comment]
Just to clarify. The test I'm doing is my number for the client.

**Comment by RafaelIngenium** [comment]
Just to clarify. The test I'm doing is  my number for to the client.
