### ISSUE TITLE
Issues on iPhone connection

### ISSUE THREAD

**Issue by rhsobr** [Rhymen/go-whatsapp#475]
Since October I started having a lot of issues on successfully connecting iPhone 7 and iPhone X to WhatsApp.

I tried all the bellow actions:
- switching wi-fi to 4G (and vice-versa)
- connecting directly to WhatsApp Web (usually works there)
- closing and reopening the app
- charging battery 'til 100% and keeping connected to power
- verified app background running
- turning plane mode on and off
- verified app updates
- verified ios updates
- turning phone off and on
- increased timeout in go-whatsapp up to 60 seconds
- finished session in Wpp app and re-read QRCode

After many many many retries, iPhone connects suddenly but with an unknown reason and unknown fix.

Has anyone dealing with same behaviour?
Is there some successful steps?

**Comment by beshoo** [comment]
Internet connection problem 99% of the time

**Comment by rhsobr** [comment]
Thanks for your reply.
I'll keep my eyes on internet connection/speedy.

**Comment by tgssb** [comment]
solucionou ?

**Comment by fernandadepaula** [comment]
> 
Duplicate of #
