### ISSUE TITLE
ProtoVersion 17 being banned

### ISSUE THREAD

**Issue by moon182** [Rhymen/go-whatsapp#48]
Hey guys, I was testing the api, and it works like charm, but for some cases, the number is banned right after reading the qr code.

What i investigated is the following: 
for newly created whatsapp accounts, the received protoversion in CONN is 17 and when you read the qr code you are banned maybe because we are talking in an old protobuff version.

I tried with a previous number that i had and the protoversion in this case is 15 and the api works like a charm.

do you guys have any ideia about this? have you ever faced something similar?

**Comment by abedp1** [comment]
i have same issue how i can solve it ?

**Comment by SchulteMK** [comment]
What is your exact definition of being banned? You cannot use WhatsApp Web in a normal browser any more?

**Comment by Rhymen** [comment]
I can still use WhatsApp with the package and with the default web client without getting banned. What @SchulteMK asked is still not answered so I'm going to close this issue as well.

**Comment by williamoliveira** [comment]
Maybe they save the current version when you create a new account and if you ever login with a lower version you are banned?
