### ISSUE TITLE
Returning QR base64

### ISSUE THREAD

**Issue by wagnerfillio** [Rhymen/go-whatsapp#480]
at login, i would like to return just a base64 string and convert it to qrCode using PHP. Still testing GoLang! Can you help me to return base64 QR in json format and not a QRcode in the terminal? I'm using the login example so far

#436 didn't help me

**Comment by beshoo** [comment]
```
terminal := qrcodeTerminal.New()
qrCode := <-qr
terminal.Get(qrCode).Print()
qrToImg(qrCode)

func qrToImg(qrCode string) {

	err := qrcode.WriteFile(qrCode, qrcode.Medium, 256, "qr.png")
	if err != nil {
		fmt.Fprintf(os.Stderr, "No se pudo crear el archivo de imagen QR")
	} 
}
```

**Comment by SchulteMK** [comment]
The `qrCode` variable contains the raw QR-code as a string. You can do with it whatever you want.
 Maybe check out one of the HTTP-Rest projects implementing this project (e.g. [go-whatsapp-rest](https://github.com/dimaskiddo/go-whatsapp-rest)). Maybe it is easier to integrate the REST-API within your PHP project.
