### ISSUE TITLE
images and stickers not uploading

### ISSUE THREAD

**Issue by TGS963** [Rhymen/go-whatsapp#481]
I tried using the one provided in the example folder but it shows

`error sending message: image upload failed: Post "https:///mms/image/8Iy_tBEAQPGhHRcBbyfAjpE4o7cnMuEtHKEgupssrAA=?auth=&token=8Iy_tBEAQPGhHRcBbyfAjpE4o7cnMuEtHKEgupssrAA%3D": http: no Host in request URLexit status 1
`
It was working a few days ago though

**Comment by ramacatur** [comment]
Please update library

`go get -u github.com/Rhymen/go-whatsapp`

**Comment by TGS963** [comment]
> Please update library
> 
> `go get -u github.com/Rhymen/go-whatsapp`

Hey, I did that but it still shows the same error

Thanks for the reply

**Comment by TGS963** [comment]
Sorry, I didn't update properly. It is working now. Thank you
