### ISSUE TITLE
 qr code scan timed out

### ISSUE THREAD

**Issue by mericsoft** [Rhymen/go-whatsapp#487]
Even though I've set higher timeout values and my internet speed is good, i always receive timed out error. What should I do?

**Comment by SchulteMK** [comment]
Did your phone scan the QR-code successfully?

**Comment by mericsoft** [comment]
i have to run the code on a ubuntu babsed server, not a phone.

**Comment by SchulteMK** [comment]
To log in you have to scan a QR code with your phone, which is sent by the returned channel from `login()`.

**Comment by mericsoft** [comment]
Ok, i'll try it

**Comment by SchulteMK** [comment]
Maybe try out one of the [examples ](https://github.com/Rhymen/go-whatsapp/tree/master/examples)
