### ISSUE TITLE
Can't send stickers after updating the library?

### ISSUE THREAD

**Issue by TGS963** [Rhymen/go-whatsapp#490]
I had successfully implemented sending stickers in the previous version but after updating recently due to media files not uploading, everything except stickers upload file. It shows error:

`error sending message: cannot match type whatsapp.StickerMessage, use message types declared in the package`

while it handles StickerMessages quite well

**Comment by hrizal** [comment]
https://github.com/Rhymen/go-whatsapp/issues/420#issuecomment-674389279
