### ISSUE TITLE
Exiting application

### ISSUE THREAD

**Issue by cassianogo** [Rhymen/go-whatsapp#5]
Hello,

I put the application to run, but after a while it automatically exits.
Is it a bug?

**Comment by SchulteMK** [comment]
Can you reproduce the issue, or give any further information? At home I can run my program over 24h and never disconnects. Even if I am on the move with my phone and leave the WLAN the connects stays connected. Do you get any errors dispatched via the HandleError function?

**Comment by Rhymen** [comment]
Did you run the example code? It keeps the application running for 5 minutes `<-time.After(5 * time.Minutes)` and then exits.  You can check out the [Go by Example: Signals](https://gobyexample.com/signals) page on how to shut down a program gracefully.

**Comment by cassianogo** [comment]
Yes, I ran the example code. That's it, it closes after 5 minutes. I use this https://gobyexample.com/signals ??

**Comment by SchulteMK** [comment]
You can replace the <-time.After(5 * time.Minutes) line with select{} and the program will not shut down any more.

**Comment by cassianogo** [comment]
Thank you @SchulteMK and @Rhymen
