### ISSUE TITLE
Easy way to get chat history as TextMessage/ImageMessage/…

### ISSUE THREAD

**Issue by sbruder** [Rhymen/go-whatsapp#50]
I want to create a tool to export a chat. Getting the chat history with `LoadMessages` works fine. The problem is, that it returns `*proto.WebMessageInfo` (in `Node.Content`) that has to be parsed with `parseProtoMessage` which isn’t exported. It is possible to parse it manually, but it is too complex considering that such a function already exists.

Am I missing an easy way to get `TextMessage`s, `ImageMessage`s, etc… via `LoadMessages`?

Do you think exporting `parseProtoMessage` is an option? I implemented this as a workaround and it seems to work well.

**Comment by SchulteMK** [comment]
I needed it also and did exactly the same thing as you did. Basically I see no problem to export the function. We are thinking about to redesign the handler system. If we dispatch `*proto.WebMessageInfo` messages and export the `parseProtoMessage` function, then we could drastically simplify the whole system.

**Comment by kaxap** [comment]
You don't need to export parseProtoMessage, imo. Just pass a message handler(s) to ChatHistory func and let dispatcher handle raw messages for you, e.g. my [attempt](https://github.com/kaxap/go-whatsapp/blob/250a33edec6a444a647c037bc7a854f6b65f251f/chat_history.go#L67) at it

**Comment by SchulteMK** [comment]
@kaxap I like your approach. It also gives the opportunity to implement different handlers for old Messages. I already considered to dispatch the messages the normal way, but I didn´t like that. This is a nice alternative, because it uses the default handlers only if you haven´t passed any spefic ones.

**Comment by kaxap** [comment]
@SchulteMK Would you like me to create a pull request based on this attempt?

**Comment by adarshsrivastava11** [comment]
@kaxap I looked at your implementation, what could be the best way to find all the ` jid `s ? Can you supply an example that could help in understanding how load chat history function works?

**Comment by kaxap** [comment]
@adarshsrivastava11 do you need all user jids who posted a message in a given group?

**Comment by adarshsrivastava11** [comment]
@kaxap No not in a group but in my inbox. `jid`s of all the people who's text in there in my inbox. Is it possible?

**Comment by kaxap** [comment]
The only "trick" I was able to think of is to collect all the jids in raw message handler, e.g.

```go
HandleRawMessage(message *proto.WebMessageInfo) {
	jid := *message.Key.RemoteJid
       ....
}
```

The idea is to store all jids from incoming raw messages to a Set since Whatsapp would (re)send last messages from chats/groups when a new connection is established.
