### ISSUE TITLE
Sometimes I can get the contact's profile picture and sometimes I can't

### ISSUE THREAD

**Issue by GabrielBragaGit** [Rhymen/go-whatsapp#500]
When using GetProfilePicThumb sometimes I get de URL and sometimes not, from the same contacts... Any idea to how can I resolve this?

**Comment by Diden05** [comment]
I cache pictures on my side =)

**Comment by GabrielBragaGit** [comment]
Ok, thanks for your reply, no doubt this could be a solution, however I would like to understand why this happens.

**Comment by beshoo** [comment]
It is related to the privacy options, if user chooses to share the avatar or not.

Regard
