### ISSUE TITLE
GetProfilePicThumb always returning 401

### ISSUE THREAD

**Issue by Valdenirmezadri** [Rhymen/go-whatsapp#507]
Good afternoon, I can't recover the contact profile images anymore, it started on 12/01/2021

**Comment by beshoo** [comment]
It is working just fine, Make sure your contacts allow access to their photos.

**Comment by Valdenirmezadri** [comment]
i make tests but still receive 401 error, and in whatsapp.web the profile pic shows

**Comment by beshoo** [comment]
Thats strange, try to refresh the sessions, try again with a proxy...
