### ISSUE TITLE
encryptBinaryMessage invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Valdenirmezadri** [Rhymen/go-whatsapp#508]
some times i receive this error:

an 14 15:46:46 localhost.localdomain relay[25535]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 14 15:46:46 localhost.localdomain relay[25535]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x93cb88]
Jan 14 15:46:46 localhost.localdomain relay[25535]: goroutine 50736 [running]:
Jan 14 15:46:46 localhost.localdomain relay[25535]: github.com/Valdenirmezadri/go-whatsapp.(*Conn).encryptBinaryMessage(0xc005713000, 0xf5f474, 0x5, 0xc003a70510, 0x0, 0x0, 0xc0000488
Jan 14 15:46:46 localhost.localdomain relay[25535]: /home/junior/go/pkg/mod/github.com/!valdenirmezadri/go-whatsapp@v0.1.5/write.go:159 +0x88
Jan 14 15:46:46 localhost.localdomain relay[25535]: github.com/Valdenirmezadri/go-whatsapp.(*Conn).writeBinary(0xc005713000, 0xf5f474, 0x5, 0xc003a70510, 0x0, 0x0, 0x8004, 0xc0012bdb2
Jan 14 15:46:46 localhost.localdomain relay[25535]: /home/junior/go/pkg/mod/github.com/!valdenirmezadri/go-whatsapp@v0.1.5/write.go:55 +0xe8
Jan 14 15:46:46 localhost.localdomain relay[25535]: github.com/Valdenirmezadri/go-whatsapp.(*Conn).query(0xc005713000, 0xf5f3d9, 0x5, 0xc000dc9100, 0x1b, 0xc000dc92c0, 0x20, 0x0, 0x0,
Jan 14 15:46:46 localhost.localdomain relay[25535]: /home/junior/go/pkg/mod/github.com/!valdenirmezadri/go-whatsapp@v0.1.5/contact.go:202 +0x36a
Jan 14 15:46:46 localhost.localdomain relay[25535]: github.com/Valdenirmezadri/go-whatsapp.(*Conn).LoadMediaInfo(...)
Jan 14 15:46:46 localhost.localdomain relay[25535]: /home/junior/go/pkg/mod/github.com/!valdenirmezadri/go-whatsapp@v0.1.5/contact.go:56
Jan 14 15:46:46 localhost.localdomain relay[25535]: github.com/Valdenirmezadri/whatsapp_relay/apis/whatsappapi.(*waHandler).documentDownload(0xc002fc3c20, 0xc000dc92c0, 0x20, 0xc000dc
Jan 14 15:46:46 localhost.localdomain relay[25535]: /home/junior/go/src/github.com/Valdenirmezadri/whatsapp_relay/apis/whatsappapi/api_whatsapp_download.go:76 +0x1c5
Jan 14 15:46:46 localhost.localdomain relay[25535]: github.com/Valdenirmezadri/whatsapp_relay/apis/whatsappapi.(*waHandler).HandleDocumentMessage(0xc002fc3c20, 0xc000dc92c0, 0x20, 0xc
Jan 14 15:46:46 localhost.localdomain relay[25535]: /home/junior/go/src/github.com/Valdenirmezadri/whatsapp_relay/apis/whatsappapi/api_whatsapp_handlers.go:219 +0xb8
Jan 14 15:46:46 localhost.localdomain relay[25535]: created by github.com/Valdenirmezadri/go-whatsapp.(*Conn).handleWithCustomHandlers
Jan 14 15:46:46 localhost.localdomain relay[25535]: /home/junior/go/pkg/mod/github.com/!valdenirmezadri/go-whatsapp@v0.1.5/handler.go:266 +0xf98
Jan 14 15:46:46 localhost.localdomain systemd[1]: relay.service: main process exited, code=exited, status=2/INVALIDARGUMENT

**Comment by dbrgn** [comment]
I just had the same error. Is it possible that you loaded an old session but never called `wac.RestoreWithSession` on it?

**Comment by Valdenirmezadri** [comment]
Maybe, I'll do some tests
