### ISSUE TITLE
Rhymen look pl !!!

### ISSUE THREAD

**Issue by artem-webdev** [Rhymen/go-whatsapp#513]
Rhymen look pl, my english is bad, this dude (https://github.com/beshoo) can't figure out the code and closes pl !!!
here is the pl itself https://github.com/Rhymen/go-whatsapp/pull/512

**Comment by beshoo** [comment]
Thanks for the feedback, l just closed the first PL since it is not organized, you closed the second one.. 
Thats for the record.

More over, l do understand what is the modification, but l can not see how it is a security problem and where is the panic report that code claims to address. 

Thank you for your PL. 

Regard

**Comment by artem-webdev** [comment]
Can't you see panic here?
```
var ch chan string
	if answerMessageTag != "" {
		ch = make(chan string, 1)

		wac.listener.Lock()
		wac.listener.m[answerMessageTag] = ch
		wac.listener.Unlock()
	}

	if wac == nil || wac.ws == nil {
		return nil, ErrInvalidWebsocket
	}
```

**Comment by artem-webdev** [comment]
https://github.com/Rhymen/go-whatsapp/blob/8029c28f5c5a82145e324af228ac64354f07b4e8/write.go#L125

**Comment by artem-webdev** [comment]
# safer use of api library  - I gave examples about it! 

#### Here is my suggestion. Api will be safer, especially for novice programmers
#### in this case it will not be necessary to return the function before reading from the channel
```
go function(){

       chanRead, err := wac.Read(message.Info.RemoteJid, message.Info.Id)
        if err != nil {
            log.Println(err)   
       }

        // there will be no blocking even with this error ! 
        <-chanRead

}()

```

### in the current implementation with explicit nil
``` 
go function(){

       chanRead, err := wac.Read(message.Info.RemoteJid, message.Info.Id)
        if err != nil {
            log.Println(err)   
       }

        // nil channel leading to eternal blocking in case of programmer error ! 
        <-chanRead

}()

```

**Comment by artem-webdev** [comment]
beshoo what do not you understand ?

**Comment by artem-webdev** [comment]
I'm sorry, I accidentally closed it, I don't know how it happened, I thought about you

**Comment by artem-webdev** [comment]
@Rhymen I just reopened PR. Please review changes.
