### ISSUE TITLE
INSERTING WHATSAPP CONTENT IN POSTGRES

### ISSUE THREAD

**Issue by jonatasjeff** [Rhymen/go-whatsapp#529]
Hello guys. First of all, I would like to congratulate the community for having developed and reimplemented this incredible project.
I have the following question: I am developing a personalized whatsapp project and I am in the stage of inserting the content in a Postgresql database (messages, contact info, chat history, etc.), but I am a little lost in this process. Could someone help me on how can I resolve this issue? either with materials or concepts for me to study. Thanks in advance!!!

**Comment by beshoo** [comment]
Not related
