### ISSUE TITLE
Message button suggets

### ISSUE THREAD

**Issue by tgssb** [Rhymen/go-whatsapp#531]
Has anyone managed to implement the message button?

Example, in the message I have suggestions

1 - Option 1
2 - Option 2

Right after the message I would like to put 2 buttons
| Option 1 | Option 2 |

If he clicks Option 2, the message is sent

**Comment by beshoo** [comment]
No you can not

**Comment by Diden05** [comment]
Only in business API

**Comment by Romerito007** [comment]
> Has anyone managed to implement the message button?
> 
> Example, in the message I have suggestions
> 
> 1 - Option 1
> 2 - Option 2
> 
> Right after the message I would like to put 2 buttons
> | Option 1 | Option 2 |
> 
> If he clicks Option 2, the message is sent

https://github.com/Rhymen/go-whatsapp/issues/296

**Comment by fernandadepaula** [comment]
H

**Comment by fernandadepaula** [comment]
> H
