### ISSUE TITLE
Get real user number from QRCODE link generated in Whatsapp Application

### ISSUE THREAD

**Issue by rodrigo-p-a** [Rhymen/go-whatsapp#533]
Is possible decode QR CODE contact generate by Whatsapp app? Whatsapp generate code like this: https://wa.me/qr/XXXXXXXXXXXXXX ( 14 chars XXXXXXXXXXXXXX ) not as number.

Can get use whatsapp-go and got real number of user?

**Comment by beshoo** [comment]
I think we can not. the ( 14 chars XXXXXXXXXXXXXX ) is an ID stored on Whatsapp servers
