### ISSUE TITLE
Get broadcast recipients

### ISSUE THREAD

**Issue by luizpvas** [Rhymen/go-whatsapp#543]
Hey there everyone.

Is there an API to get a broadcast list recipients (the contacts of the list)?

I tried with `GetGroupMetaData` but it didn't return anything.

I know it's possible because it's available on whatsapp web. Maybe we can get this data with a custom query?
Thanks!

**Comment by luizpvas** [comment]
I didn't figure out how to capture brodcast recipients, but was able to "gather" this from ack events (delivery and read confirmation).

**Comment by Romerito007** [comment]
> I didn't figure out how to capture brodcast recipients, but was able to "gather" this from ack events (delivery and read confirmation).

Example JID:   1623673422@broadcast

`func (wac *Conn) GetBroadcastMetaData(jid string) (<-chan string, error) {
	data := []interface{}{"query", "contact", jid}
	return wac.writeJson(data)
}`
