### ISSUE TITLE
Whatsapp says message wasn't sent, but it was

### ISSUE THREAD

**Issue by paulocsanz** [Rhymen/go-whatsapp#566]
Hey, today we started experiencing a weird issue on whatsapp.

Some of our clients send messages using go-whatsapp and they are appearing with the red exclamation point next to them, like if they weren't sent at all. But the other person is in fact receiving them (and replying to them).

![image](https://user-images.githubusercontent.com/6289779/121376885-48a36d00-c918-11eb-8b42-db6770448f74.png)

We are suspecting that this has something to do with whatsapp-web's version change, and since go-whatsappuses an older version is making the app confused.

It seems wise that the community documents and investigates more this version change, because it may start causing real problems soon.

**Comment by ramacatur** [comment]
Same issue. However, for WhatsApp applications that have not been updated, this does not happen.

**Comment by ramacatur** [comment]
I've found solution and it worked

Whatsapp changes the status value in the node format, where previously it was 0 (error) to 1 (pending). so in the `message.go` file, `Send(msg interface{})`, before

`ch, err := wac.sendProto(msgProto)`

Add this code to change status:

```
status := proto.WebMessageInfo_PENDING
msgProto.Status = &status
```

Try this solution

Thanks

**Comment by leonetosoft** [comment]
Same issue.

**Comment by leonetosoft** [comment]
`status := proto.WebMessageInfo_PENDING
msgProto.Status = &status`

![image](https://user-images.githubusercontent.com/3596786/121560818-e153ee80-c9e5-11eb-8e2b-97b9a4930534.png)

Solved!
Tanks @ramacatur

**Comment by beshoo** [comment]
Please make a PL

Regard

**Comment by leonetosoft** [comment]
@beshoo  I think it's fair that @ramacatur  does it because he found the solution!
Or do you want me to do it?

**Comment by leonetosoft** [comment]
Thanks @ramacatur for providing my first PR

**Comment by ramacatur** [comment]
> Thanks @ramacatur for providing my first PR

Ok, you are welcome.

**Comment by rhsobr** [comment]
Thanks @leonetosoft for the PR

**Comment by jairforero** [comment]
> `status := proto.WebMessageInfo_PENDING msgProto.Status = &status`
> 
> ![image](https://user-images.githubusercontent.com/3596786/121560818-e153ee80-c9e5-11eb-8e2b-97b9a4930534.png)
> 
> ¡resuelto!
> Tanques @ramacatur

Excelente , Very tks!!

**Comment by rafaelaraujobsb** [comment]
@ramacatur thank you!

What did you do to discover this solution? Did you decrypt the message whatsapp web was sending?

**Comment by ramacatur** [comment]
> @ramacatur thank you!
> 
> What did you do to discover this solution? Did you decrypt the message whatsapp web was sending?

Yes, decrypt binary message in whatsapp web.

**Comment by cassioseffrin** [comment]
> Thanks @ramacatur for providing my first PR

@leonetosoft : There is an estimative when your  PR will be deployed on master ?

**Comment by RobertoOrtis** [comment]
> sapp changes the status value in the node format, where prev

I applied the changes but still not working.

**Comment by RobertoOrtis** [comment]
> I've found solution and it worked
> 
> Whatsapp changes the status value in the node format, where previously it was 0 (error) to 1 (pending). so in the `message.go` file, `Send(msg interface{})`, before
> 
> `ch, err := wac.sendProto(msgProto)`
> 
> Add this code to change status:
> 
> ```
> status := proto.WebMessageInfo_PENDING
> msgProto.Status = &status
> ```
> 
> Try this solution
> 
> Thanks

I applied these changes but still not working

**Comment by aryahmph** [comment]
Still not working
