### ISSUE TITLE
Login/Restore not working

### ISSUE THREAD

**Issue by emauro** [Rhymen/go-whatsapp#571]
Something changed during the login/restore handshake. The following error appears:

Restoring failed: error decoding login connResp: json: cannot unmarshal array into Go value of type map[string]interface {}

The following json is received:

["cmd", {"type": "update"}]

Code fails in line 393 of session.go. Note that JSON does not contain entry "status", which is expected.

**Comment by fredjsf** [comment]
Me too

**Comment by laercioamatuzzi** [comment]
I got the same issue here: "error decoding login connResp: json: cannot unmarshal array into Go value of type map[string]interface {}".

**Comment by Stasich** [comment]
try new version for whatsApp:  SetClientVersion(2, 2121, 6)

**Comment by SheIITear** [comment]
This happens because of outdated wa web version given to whatsapp. Change the version to newer one like @Stasich said and you can connect again.

**Comment by laercioamatuzzi** [comment]
Worked for me, thx guys :)

**Comment by paulocsanz** [comment]
It worked here too! All of our clients got broken today.

**Comment by fredjsf** [comment]
When I changed to new version we received new error: qr code scan timed out.

**Comment by emauro** [comment]
Solved!

**Comment by ravern** [comment]
Is there a programmatic way of automatically figuring out the next version numbers?

**Comment by Faeziix** [comment]
How can I change the version?
