### ISSUE TITLE
Login error response (cannot unmarshal array into Go value of type map[string]interface {})

### ISSUE THREAD

**Issue by luizpvas** [Rhymen/go-whatsapp#573]
QR Code generation started returning this this aftertoon:

`error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}`

Is anyone else seeing this?
Thanks!

**Comment by bhavesh53** [comment]
same error got any solution ??

**Comment by Fernando-Erd** [comment]
Solution here https://github.com/Rhymen/go-whatsapp/issues/571

**Comment by pedroufo51warick** [comment]
Update waVersion 
to 
var waVersion = []int{2, 2121, 6} in session.go
