### ISSUE TITLE
server closed connection,code: 1000,text:

### ISSUE THREAD

**Issue by zharazhar17** [Rhymen/go-whatsapp#575]
after update go-whatsapp cannot get QR and response look this server closed connection,code: 1000,text:,

what the solution , and other people same problem like me ? thanks guys

**Comment by firstyanto** [comment]
Please check #574 , it will solve your problem

**Comment by zharazhar17** [comment]
thanks sir, and then after change version in session.go ,i have other problem like this ,
panic: close of closed channel

goroutine 8 [running]:
github.com/Rhymen/go-whatsapp.(*Conn).Disconnect(0x1952460, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)

any solution sir about my problem like this ? thanks

**Comment by zharazhar17** [comment]
solved am change version like this #574

**Comment by jairforero** [comment]
You need work with repo local in vendor, go to folder github.com/rhymen/go-whatsapp open file session.go in line 21  where is "var waVersion" change valur for version of whatsapp app
