### ISSUE TITLE
Hello, I have a problem, the message is coming but this symbol is left to resend, can someone help me?

### ISSUE THREAD

**Issue by Nelsonguiana** [Rhymen/go-whatsapp#576]
See image below
![Captura de tela 2021-06-18 110815](https://user-images.githubusercontent.com/86115696/122573945-82195e00-d025-11eb-84e7-1a045769d684.png)

**Comment by firstyanto** [comment]
Please check #566 . It will solve it.

**Comment by Nelsonguiana** [comment]
@firstyanto Thx man !
