### ISSUE TITLE
Error during login: error decoding login resp

### ISSUE THREAD

**Issue by devk33** [Rhymen/go-whatsapp#578]
Hello everyone!

I got an error while receiving QR:
`error during login: error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}`

I've worked with 0.4.1307 before.
`wac.SetClientVersion(0, 4, 1307)`

Does anyone have a similar problem?

**Comment by devk33** [comment]
New version solved:
`wac.SetClientVersion(2, 2123, 7)`

**Comment by excaliburapp** [comment]
> New version solved:
> `wac.SetClientVersion(2, 2123, 7)`

In which file can I find this code?

**Comment by beshoo** [comment]
Session.go
