### ISSUE TITLE
error decoding binary: error decoding binary: invalid jid pair: rci -

### ISSUE THREAD

**Issue by jhow2892** [Rhymen/go-whatsapp#58]
Good afternoon Guys, I'm getting this error when I just connected and are receiving the messages

error decoding binary: error decoding binary: invalid jid pair: rci -

**Comment by SchulteMK** [comment]
Can you give any backround Information? Do you know which message it is that fails? Does the sender has a 'special' number? Does the error occur every time you connect? Do other messages decode correctly?

**Comment by rushib1** [comment]
It's my first time using this package today and got the same bug, so I have tried to debug for past 6-7hrs with no luck(I haven't read the spec). Looks like the data being sent by whatsapp has problem. this bug appears at decoder.go at line 193 with the following sample data [78, 105, 107, 104, 105, 252, 0, 248, 5, 95, 45, 250, 255, 140, 145, 150, 102, 137, 120, 151, 161, 69, 54, 67, 152, 79, 35]

**Comment by Rhymen** [comment]
I deleted rushib1 comment because he may have posted sensitive information by accident.
As I can't seem to replicate this I'm going to close the issue.

**Comment by Deewai** [comment]
I'm also experiencing this issue. It has to do with getting list of contacts from my phone.
I think its a problem with the jid of  a particular contact. I've tried two different phones with different contact list and it only occurs on one.

**Comment by Deewai** [comment]
Please any help?
I keep experiencing this issue, if i'm not mistaken it occurs while trying to get contacts at login. Also subsequent try to update contacts gives error "error processing data: received invalid data"

**Comment by Deewai** [comment]
@Rhymen Please take a look at this

**Comment by curchunflo13** [comment]
Hi, I am receiving this error too, any information about how to fix it?

**Comment by curchunflo13** [comment]
this is the full error gowhatsapp: error occoured: error processing data: error decoding binary: could not decode binary: invalid jid pair: Fpf. Rrhh -

thanks in advance

**Comment by Deewai** [comment]
Couldn't fix it. Had to change the number i was using to connect to whatsapp and didn't face the issue again. I think its an issue when getting lists of contacts/chats. Probably a contact with an unsupported character.

**Comment by curchunflo13** [comment]
I think you are right because the error appears when at start when it
download all messages, there is some way to avoid that?

**Comment by Deewai** [comment]
The only solution that worked for me was changing the number i used in connecting to whatsapp.
I tried deleting all contacts an messages on the former number but i kept on getting the error.
