### ISSUE TITLE
is this library still working?

### ISSUE THREAD

**Issue by rbadillo** [Rhymen/go-whatsapp#582]
I'm getting this error:

```
error caught in handler: message type not implemented
exit status 1
```

I had to bump the WAversion as per other comments I saw but is still not working. Can somebody help please?

**Comment by beshoo** [comment]
What is the code you are using, it seems an error with your implementation.

**Comment by rbadillo** [comment]
This is my code:

```
func main() {

	fmt.Println("Trying to connect")
	wac, err := whatsapp.NewConn(60 * time.Second)
	fmt.Println("After NewConnect")
	if err != nil {
		fmt.Fprintf(os.Stderr, "error creating connection: %v\n", err)
		return
	}

	fmt.Println("Adding Handler")
	wac.AddHandler(&waHandler{wac, uint64(time.Now().Unix())})
	fmt.Println("Done Adding Handler")

	if err = login(wac); err != nil {
		fmt.Fprintf(os.Stderr, "error logging in: %v\n", err)
		return
	}

	fmt.Println("Waiting for Messages")
	c := make(chan struct{})
	<-c
}
```

**Comment by hrizal** [comment]
its still working smoothly ! without problem.
24 June 2021

Pada tanggal Rab, 23 Jun 2021 pukul 06.03 Roberto Badillo <
***@***.***> menulis:

**Comment by danielspk** [comment]
The library continues to operate as of June 24, 2021.

In your `HandleError` function do not exit. Consider that there may be types of messages not implemented by the library. Just ignore those kinds of messages and don't end your boot.

**Comment by rbadillo** [comment]
I was able to get it working by adding this line of code:

```
wac.SetClientVersion(2, 2123, 7)
```

Thank you guys for your help.

**Comment by excaliburapp** [comment]
> I was able to get it working by adding this line of code:
> 
> ```
> wac.SetClientVersion(2, 2123, 7)
> ```
> 
> Thank you guys for your help.

where to add the code?

**Comment by rbadillo** [comment]
@excaliburapp 

```
	wac, err := whatsapp.NewConn(60 * time.Second)
	wac.SetClientVersion(2, 2123, 7)
```
