### ISSUE TITLE
When QRCode is scanned messages are not arriving in whatsapp mobile app.

### ISSUE THREAD

**Issue by paulocsanz** [Rhymen/go-whatsapp#586]
This is a _very_ weird bug we started experiencing today.

A client of ours had go-whatsapp scanned and was using instead of whatsapp-web, today they stopped receiving messages on their mobile app. The moment they invalidated our session token the messages started arriving again.

And in the same spirit another client wasn't able to remove our session in the mobile app, it kept returning. 

It seems whatsapp has a few bugs, but probably our integration has to be adapted too.

I will be back with more data, but I'm posting here so if anybody else experiences this we can speed debugging up.

**Comment by josergm86** [comment]
I see that a new whatsapp web version is available. It is was updated recently to 2.2123.8.

**Comment by fredjsf** [comment]
This issue occurs with us 5-7 times. I think this is a spam list. The message not arrive on their mobile app and mobile app does nos connect to whatsapp-web. But the app can send messages.

**Comment by fredjsf** [comment]
anyone else with this problem?

**Comment by fredjsf** [comment]
Paulo, can you share how you solved?

**Comment by paulocsanz** [comment]
It stopped happening, we suspect it's related to a bunch of messages enqueued. Specially a bunch of big files. Like retrieving the entire history when new messages are arriving. Overloading the app, we changed our logic to avoid that, but I can't be sure this solved the issue.
