### ISSUE TITLE
Change icon client

### ISSUE THREAD

**Issue by danielspk** [Rhymen/go-whatsapp#587]
Hello, is it possible to change the client icon? Chrome Example:

![image](https://user-images.githubusercontent.com/5874643/123662721-18ab0380-d80c-11eb-95b4-8dbd3584c9a3.png)

SetClientName() only allows to change the short/long name and the version.

Thanks.

**Comment by danielspk** [comment]
I have been trying to assign in shortName the texts "chrome", "firefox" and "opera" and in all cases the icon of the web browser is assigned automatically. Does anyone know of other valid options?

**Comment by globalmac** [comment]
<img width="529" alt="whatsapp.NewConnWithOptions" src="https://user-images.githubusercontent.com/3147814/124002523-84dd6100-d9de-11eb-9cdb-c55a1df3cc46.png">

Use `whatsapp.NewConnWithOptions` with params

**Comment by danielspk** [comment]
Thanks @globalmac 

So far the possible values for the *shortclientName* that I tested - and change the icon - are: `Chrome`, `Opera`, `Firefox`, `Edge`, `electron`

Does anyone know any more?
