### ISSUE TITLE
Request Timeout

### ISSUE THREAD

**Issue by Nelsonguiana** [Rhymen/go-whatsapp#590]
Does anyone know it's happening every time I try to recover a saved session, on timeout connection, and I can pull the qrcode normally, sometimes it works, and sometimes it doesn't.

**Comment by danielspk** [comment]
Hello @Nelsonguiana.

Check that the cell phone has an internet connection and it is unlocked (see home screen) when reconnecting the session.

**Comment by Nelsonguiana** [comment]
> Hello @Nelsonguiana.
> 
> Check that the cell phone has an internet connection and it is unlocked (see home screen) when reconnecting the session.

There is some problem in my session, I deleted it and it came back thanks.
