### ISSUE TITLE
Update packages

### ISSUE THREAD

**Issue by danielspk** [Rhymen/go-whatsapp#591]
Hi I am having performance problems - memory increase. When profiling, I notice that the websocket and encryption take most of it. I see that the dependency packages are out of date. What do you think of updating to the latest stable versions?

**Comment by maeverson** [comment]
Hi, 
My API disconects after 30 minutes without communication. Recently, I'd updated all dependencies and now I'm trying to discover if that issue was corrected on dependencies upgrade.
