### ISSUE TITLE
Receive only new messages

### ISSUE THREAD

**Issue by juanpmarin** [Rhymen/go-whatsapp#6]
Hi, first of all, thank you for this great work

I wonder if is there any way to receive only the new messages when I restore the session

**Comment by Rhymen** [comment]
Hi,

WhatsApps Server API does not provide a functionality like this. This needs to be implemented on the client side. You could set up a database, save every message and then compare which messages you didn't already safe.

**Comment by juanpmarin** [comment]
@Rhymen thanks for answering, I'm closing this now
