### ISSUE TITLE
Unmarshal error during login

### ISSUE THREAD

**Issue by dstdfx** [Rhymen/go-whatsapp#612]
Hi, I'm trying to run [login example](https://github.com/Rhymen/go-whatsapp/blob/master/examples/login/main.go) but it's falling with: 
`error during login: error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}`

I've changed the code of the library a bit in order to check what's inside the [response](https://github.com/Rhymen/go-whatsapp/blob/master/session.go#L224) and looks like the format has changed: 
`["Cmd",{"type":"update"}]`

**Comment by adzimzf** [comment]
I got the same issue when trying this

**Comment by dstdfx** [comment]
@adzimzf It's working, indeed! Thanks! Looks like the examples still need to be fixed.
