### ISSUE TITLE
Can anyone help me fix this error?

### ISSUE THREAD

**Issue by Nelsonguiana** [Rhymen/go-whatsapp#614]
The error is giving, when I try to generate qrcode, some more devices work normally, after a while the api falls.

![image](https://user-images.githubusercontent.com/86115696/132131096-8852b542-4c98-491f-9ff7-a28b4c152cd6.png)

**Comment by gjongenelen** [comment]
The line above (which isn't included in the screenshot) is essential. Please attach it.
Also, generally speaking it is better to copy/paste your errors, as people might be having the same issue and images aren't indexed in search-engines.

**Comment by Nelsonguiana** [comment]
![image](https://user-images.githubusercontent.com/86115696/132215918-bddda61c-2dbf-478c-bdef-091767ea59ff.png)

Yes sorry because I'm having this problem and my api is dropping all the time, it's causing a lot of stress to my clients, if you can help me I would be grateful, there's the line above missing

**Comment by danielspk** [comment]
@gjongenelen see #601

**Comment by Nelsonguiana** [comment]
Thanks, we know this is the problem with whatsapp beta so :/ sad
