### ISSUE TITLE
whatsapp支持手机离线发送消息正在公测，我使用测试版本发现现在的二维码不能用，怎么办？

### ISSUE THREAD

**Issue by zhengshengjie666** [Rhymen/go-whatsapp#616]
详情参考：
https://faq.whatsapp.com/general/download-and-installation/about-multi-device-beta

**Comment by Romerito007** [comment]
> 详情参考：
> https://faq.whatsapp.com/general/download-and-installation/about-multi-device-beta

https://github.com/mateusmirandaalmeida/multidevice

**Comment by zhengshengjie666** [comment]
> > 详情参考：
> > https://faq.whatsapp.com/general/download-and-installation/about-multi-device-beta
> 
> https://github.com/mateusmirandaalmeida/multidevice

非常感谢，这对我帮助很大
