### ISSUE TITLE
Unable to create new sessions

### ISSUE THREAD

**Issue by vocuzi** [Rhymen/go-whatsapp#627]
Unable to create or restore sessions, getting the following error :

`error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}`

**Comment by GizmoOAO** [comment]
https://github.com/Rhymen/go-whatsapp/blob/29b13751fedc61341e8b6fc365629f84b3d71eaf/session.go#L21

```go
var waVersion = []int{2, 2142, 12}
```

**Comment by 0xhex** [comment]
> https://github.com/Rhymen/go-whatsapp/blob/29b13751fedc61341e8b6fc365629f84b3d71eaf/session.go#L21
> 
> ```go
> var waVersion = []int{2, 2142, 12}
> ```

thank you it is working,

how can i find out the whatsapp version?

**Comment by ajaydeta** [comment]
@GizmoOAO thank you it is working.

**Comment by RafaelIngenium** [comment]
The error still persists even when updating :
var waVersion = []int{2, 2142, 12}

**Comment by tavidian** [comment]
> The error still persists even when updating : var waVersion = []int{2, 2142, 12}

I'm having the same issue

**Comment by beshoo** [comment]
I have no problem restoring the session.

**Comment by beshoo** [comment]
and I have no problem creating a new session!
