### ISSUE TITLE
Unable to create or restore sessions,=

### ISSUE THREAD

**Issue by RafaelIngenium** [Rhymen/go-whatsapp#630]
Unable to create or restore sessions, getting the following error :

error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}

**Comment by beshoo** [comment]
I am not sure but I have no problem with that!

**Comment by RafaelIngenium** [comment]
Here continues with the error for new numbers as for restart separation

**Comment by RafaelIngenium** [comment]
complementing, in the version that went up I'm also wrong, where it appears as undefined:

whatsapp.ErrMediaDownloadFailedWith410

 whatsapp.ErrMediaDownloadFailedWith404
