### ISSUE TITLE
cannot unmarshal array into go value of type map[string]interface {}

### ISSUE THREAD

**Issue by maeverson** [Rhymen/go-whatsapp#631]
Hi. 
My API works fine until last monday (01 Nov 2021).
Today, I can't generate QRCODE. API return this message: 
`
{"label":"http-access","level":"error","msg":"error decoding login resp: json: cannot unmarshal array into go value of type map[string]interface {}\n","service":"go-whatsapp-rest","time":"2021-11-03T10:00:46.488955064-03:00"}`

Someone get this error too? It's the end?

Thanks.

**Comment by hagen00** [comment]
Yes..me. I tried this:
```
wac, err := whatsapp.NewConn(3 * time.Minute)
// added this 
wac.SetClientVersion(2, 2123, 7)
```
but It still doesn't work for me. If you look at the other open issues, this may not be fixable (unless someone can tell me how to fix??)

It does however look like this library is not a long term solution --> https://github.com/Rhymen/go-whatsapp/issues/622

**Comment by maeverson** [comment]
Changing for `SetClientVersion(2, 2142, 12)` as last version of WhatsApp Web .. still fails.

**Comment by beshoo** [comment]
try my api

https://github.com/beshoo/go-whatsapp-rest-api

**Comment by gabstv** [comment]
> try my api https://github.com/beshoo/go-whatsapp-rest-api

it is a drop-in replacement? nice!

**Comment by gabstv** [comment]
btw:
`error decoding login connResp: json: cannot unmarshal array into Go value of type map[string]interface {}\n`
it seems that the error is happening with new connections; restoring existing connections is still working

**Comment by gabstv** [comment]
> try my api https://github.com/beshoo/go-whatsapp-rest-api
> […](#)

I updated go-whatsapp to the same version of your project's go.mod (`v0.1.2-0.20210615184944-2b8a3e9b8aa2`) and the error still happens, so I guess it's also happening in your rest service too.

**Comment by gabstv** [comment]
I was able to get the raw message:
```["Cmd",{"type":"update"}]```
it looks like WhatsApp bumped their min required version again

**Comment by gabstv** [comment]
I updated to:
`conn.SetClientVersion(2, 3147, 10)`
and it worked
I randomly guessed 3147 so I don't know if it is a real version or not

**Comment by maeverson** [comment]
> I was able to get the raw message: `["Cmd",{"type":"update"}]` it looks like WhatsApp bumped their min required version again
> 
> Edit: I updated to: `conn.SetClientVersion(2, 3147, 10)` and it worked I randomly guessed 3147 so I don't know if it is a real version or not

Work's here with another random number.

**Comment by hagen00** [comment]
Thanks, I can confirm that `conn.SetClientVersion(2, 3147, 10)` works for me as well.
