### ISSUE TITLE
Multiple devices and no cell phone is connected

### ISSUE THREAD

**Issue by RafaelIngenium** [Rhymen/go-whatsapp#634]
Does anyone know how the project will behave after using multiple devices and without the phone being connected to the internet?

**Comment by fredjsf** [comment]
Hi Rafael,

This version of go-WhatsApp will be deprecated soon since WhatsApp is going to the MD.

**Comment by RafaelIngenium** [comment]
> Hi Rafael,
> 
> This version of go-WhatsApp will be deprecated soon since WhatsApp is going to the MD.

Do you have any idea how long it takes for this version to become obsolete?
