### ISSUE TITLE
Not a issue [Can someone help in describing algo and payload structure for sending message]

### ISSUE THREAD

**Issue by tiwarishrijan** [Rhymen/go-whatsapp#64]
Hi Team,
I am contributing in [Sigalor whatsapp-web-reveng](https://github.com/sigalor/whatsapp-web-reveng) and stuck in sent message function.

I have created payload and able to send message but it does not work sometimes. Can someone describes the payload structure and sample code for help.

**Comment by SchulteMK** [comment]
What kind of payload have you created? Did you create a custom `*proto.WebMessageInfo` or did you use one of our message types?

**Comment by tiwarishrijan** [comment]
> What kind of payload have you created? Did you create a custom `*proto.WebMessageInfo` or did you use one of our message types?

I have used [Sigalor whatsapp-web-reveng ](https://github.com/sigalor/whatsapp-web-reveng) structure to create custom payload in python.

**Comment by SchulteMK** [comment]
Ahh sorry I misread that. Probably you are better of creating an issue over at Sigalor´s repository.
Media handling is described quite well in the README his repository. [See](https://github.com/sigalor/whatsapp-web-reveng#dealing-with-e2e-media)
You can look at our implementation [here](https://github.com/Rhymen/go-whatsapp/blob/fd35ed50821362de2c766c451dfb1a11e12b5c4e/media.go#L90).

**Comment by tiwarishrijan** [comment]
> Ahh sorry I misread that. Probably you are better of creating an issue over at Sigalor´s repository.
> Media handling is described quite well in the README his repository. [See](https://github.com/sigalor/whatsapp-web-reveng#dealing-with-e2e-media)
> You can look at our implementation [here](https://github.com/Rhymen/go-whatsapp/blob/fd35ed50821362de2c766c451dfb1a11e12b5c4e/media.go#L90).

Thanks @SchulteMK , I am able to upload media but issue i am facing in sending text/media to user.

Can you please reference in your code, as i am new to Go.

**Comment by SchulteMK** [comment]
All protobuf messages get send via this [method](https://github.com/Rhymen/go-whatsapp/blob/fd35ed50821362de2c766c451dfb1a11e12b5c4e/message.go#L82). `wac.writeBinary` writes the data onto the websocket connection. [Source](https://github.com/Rhymen/go-whatsapp/blob/fd35ed50821362de2c766c451dfb1a11e12b5c4e/conn.go#L232)
`metric` and `flag` are important constants to be set, otherwise the message won´t send. Our `metric` is `message` (16) and our `flag` is `ignore` (128). We used the same values for every message.

**Comment by tiwarishrijan** [comment]
Thanks @SchulteMK, I will try to convert this into python.
