### ISSUE TITLE
Any way to update client's status through api

### ISSUE THREAD

**Issue by apoorvcodes** [Rhymen/go-whatsapp#640]
Is there a way to update status of client using go-whatsapp?

**Comment by apoorvcodes** [comment]
any help guys?

**Comment by DonovanDiamond** [comment]
Unfortunately, this package is not being actively maintained currently and will soon be unusuable as WhatsApp updates to multi-device. Please look at tulir/whatsmeow for a Go WhatsApp Web API that is actively maintained and supports WhatsApp multi-device.

**Comment by apoorvcodes** [comment]
I would like to help maintain it tbh, a lot of people are using it for there bots and not maintaining it would not do justice to them

**Comment by apoorvcodes** [comment]
@Rhymen

**Comment by apoorvcodes** [comment]
@enskpl Nope sadly was thinking to fork this and maintain it cos its pretty much un-maintained project
