### ISSUE TITLE
error creating connection: couldn't dial whatsapp web websocket: websocket: bad handshake

### ISSUE THREAD

**Issue by mqnoy** [Rhymen/go-whatsapp#651]
anyone have a problem like this ? 

```
error creating connection: couldn't dial whatsapp web websocket: websocket: bad handshake
```

**Comment by rvp98** [comment]
Same here 
![image](https://user-images.githubusercontent.com/54128956/160312858-cbd0a260-3d6b-44b2-a8ae-02906fc5b72d.png)

**Comment by felixyangsen** [comment]
me too

**Comment by TrooperBr** [comment]
> anyone have a problem like this ? 
> 
> ```
> error creating connection: couldn't dial whatsapp web websocket: websocket: bad handshake
> ```

U try use a other IP ?

**Comment by mqnoy** [comment]
closed, i decide to using https://github.com/tulir/whatsmeow
