### ISSUE TITLE
qrcode scan issue from Whatsapp Bussines after today update

### ISSUE THREAD

**Issue by manishswami** [Rhymen/go-whatsapp#653]
qrcode scan issue from Whatsapp Bussines after today update .. Any update

**Comment by biji** [comment]
change client version to `2.2210.9`

**Comment by slackale** [comment]
Hello, this didn't work for us :(

**Comment by Allu9221** [comment]
any update on this?

**Comment by beshoo** [comment]
It stop working all together, since whatsapp shift to MD.
