### ISSUE TITLE
Redirection to web.wh****pp.com

### ISSUE THREAD

**Issue by wazowski78** [Rhymen/go-whatsapp#66]
Hi everyone, and thank you to @Rhymen for his work. 

I would like to know if is it possible to use go-whatsapp to make a login to WhatsApp Web, and load the oficial web.whatsapp.com site with the login credentials. I mean, load the QR from go-whatsapp and after that make a redirection to whastapp web.

Thanks in advance.

**Comment by SchulteMK** [comment]
You can put the generated `MacKey`, `EncKey`, `ClientID`, `ClientToken `and `ServerToken` inside your Browsers Storage (Chrome: F12 -> Application -> Local Storage -> whatsapp -> WASecretBundle etc.). I don´t know how to automate that or if it is even possible. Manually copying these values works.

**Comment by SchulteMK** [comment]
Just for personal interest, @wazowski78 what are you trying to achieve?

**Comment by wazowski78** [comment]
Jejeje... well I am just trying to login and relogin form JavaScript. I have managed to use your app and the WhatsApp-web-server to generate my credentials. So I can read the MacKey, EncKey, etc... values. My "problem" is that I have a lot of WhatsApp accounts, personal, freelance and my job phone too. Three accounts that I just want to control from one phone, and I do not need to use them at the same time. So I want to make a script that closes and opens one session on WhatsApp web. Localstorage is a good tip here, so I am going to try to make it manually and after that try to automate it some way.
What do you think?

**Comment by SchulteMK** [comment]
If you want to develop a JavaScript solution for your account switching, I would try to extract the stored data directly from the browser and save it. You can swap these afterwards for other credentials and reload the page to switch accounts.

**Comment by wazowski78** [comment]
Yes, I am trying to do it, but I am getting some problems find the correct values, and at this moment, I have no clues in how to create the cookie, so I think I have to see how is the cookie or localstorage stored and try to switch between them.

**Comment by Rhymen** [comment]
As this is not a problem regarding the go-whatsapp package I'm going to close the issue.
