### ISSUE TITLE
query nouns?

### ISSUE THREAD

**Issue by Mikolasek93** [Rhymen/go-whatsapp#67]
Hello, 
I'm trying to add some features to your existing solution (delete chat for now), I have only one question.
Where do you get all these nouns used in writebinary, query. 
I mean like "exist", "remove", "status" etc.

Thanks a lot!

**Comment by Rhymen** [comment]
Hello @Mikolasek93 ,

we got the commands by debugging WhatsApp Web. Just open it, set breakpoints at the right lines (for example right before the messages are encrypted and send) and check the values of the variables. As WhatsApp updates their code constantly I can't give you any exact line numbers so you have to search for yourself sorry.
