### ISSUE TITLE
Where to get query nouns?

### ISSUE THREAD

**Issue by Mikolasek93** [Rhymen/go-whatsapp#68]
Hello, 
I'm trying to add some features to your existing solution (delete chat for now), I have only one question.
Where do you get all these nouns used in writebinary, query. 
I mean like "exist", "remove", "status" etc.

Thanks a lot!

**Comment by SchulteMK** [comment]
Basically you have to debug the whatsapp-web javascript file. Search for the send method of the websocket and set a breakpoint there. The execution will hold on every message/request send to the servers. You should be able to see a debugObject which holds all protobuf definitions and all pramameters used for sending.

**Comment by Rhymen** [comment]
Duplicate of #67
