### ISSUE TITLE
error logging in: restoring failed: restore session connection timed out

### ISSUE THREAD

**Issue by tkovs** [Rhymen/go-whatsapp#7]
After I removed the whatsapp web session on the phone, the go-whatsapp became unusable.

I'm not a go developer, so I can understand the source, but the architecture I have no idea. Where is the session saved?

**Comment by Rhymen** [comment]
The library does not save the session anywhere, instead it is returned by the `login` and `restoreSession` function. If you use the code that is provided by the example section, the  session is saved in `os.TempDir()` and is called _whatsappSession.gob_

See https://golang.org/pkg/os/#TempDir

**Comment by tkovs** [comment]
Thank you! Yes, I was using the sample code. Now I'm trying to implement a detection of disconnected and terminated sections. The Whatsapp Web realizes the difference, but the examples provided do not.

Disconnected session
![image](https://user-images.githubusercontent.com/8717661/43098246-ec58dc30-8e94-11e8-8ecf-b42227c8e6ab.png)

Closed session
![image](https://user-images.githubusercontent.com/8717661/43098911-e557bcd8-8e96-11e8-8d31-7939fbad9e8d.png)

**Comment by SchulteMK** [comment]
If the session gets taken over by another client, you will get a disconnect message via the JsonHandler and the websocket get closed afterwards. The closing of the socket gets communicated via the HandleError function.
