### ISSUE TITLE
How to send composing presence?

### ISSUE THREAD

**Issue by xxi123** [Rhymen/go-whatsapp#75]
Hi I am trying to send a presence composing using `res, err := wac.Presence("contact_number@c.us", "composing")` but the status in whatsapp app in my contact's cell phone not show "composing". But when I try to send available presence `res, err := wac.Presence("contact_number@c.us", "available")` , the status in Whatsapp app show "Online".

**Comment by highness28** [comment]
I think you have to read this #23

**Comment by AlmogBaku** [comment]
The issue was an incomplete implementation, I fixed that in PR #80
