### ISSUE TITLE
Checking if whatsapp number is valid

### ISSUE THREAD

**Issue by kickbox** [Rhymen/go-whatsapp#78]
Using the `wac.Exist() `method, I get same `{"status":400}` response for both valid and invalid whatsapp numbers. I tried to do this using the support code provided [here](https://github.com/kaxap/go-whatsapp/commit/a5607be7076e9892489838c39182f7dd363f7e27)

```
ch, err := client.Exist(number+"@c.net")
if err != nil {
  panic(err)
}
resp := <- ch
fmt.Println(resp) // always returns {"status":400} 
```
Am I doing something wrong?

**Comment by Rhymen** [comment]
Hey @kickbox ,

Status 400 indicated a client side error. When I send a correct number a receive a status of 200, if I send a incorrect one a status of 404. Did you connect to WhatsApp before you tried to check the number? Your code works for me at least.

**Comment by VinothJ7** [comment]
Replace "@c.net" with "@s.whatsapp.net"

**Comment by Ekopriyo024** [comment]
I want to build a WhatsApp checker tool, but I can't code, please help me get it
