### ISSUE TITLE
How can i get Presence updates ? 

### ISSUE THREAD

**Issue by beratakuzum** [Rhymen/go-whatsapp#81]
Hello.
I would like to find out if a number is online or offline.
Using this code, i get the response: "presence message from chat a: {"status":200}"
```
chA, err := wac.SubscribePresence("number@c.us")
	if err != nil {
	fmt.Fprintf(os.Stderr, "error subscribing to presence of chat a: %v\n", err)
	}

	fmt.Printf("presence message from chat a: %v\n", <-chA)
```

How can i get the online, offline info ?
Thank you so much. @AlmogBaku @Rhymen

**Comment by beratakuzum** [comment]
I still need help guys. Can anybody help me ?

**Comment by Rhymen** [comment]
As @highness28 says you need to implement the JsonHandler interface and subscribe to the presence of the number you want to check.

**Comment by theflyingmantis** [comment]
How to subscribe to presence of the number with the json handler? After 10 minutes, we have to subscribe to the number again. We can get the presence update in `HandleJsonMessage` but how to subscribe?

**Comment by hiwaleakshay** [comment]
@theflyingmantis Did your number stays online always? The number which you used to scan qr code..

**Comment by theflyingmantis** [comment]
@hiwaleakshay Yes. Its always online

**Comment by hiwaleakshay** [comment]
How are you doing that? By keeping mobile screen on always and keep whatsapp in foreground or by code? I tried echo example. I got login and can echo message but my number shows offline. Any idea?

**Comment by theflyingmantis** [comment]
@hiwaleakshay Presently am keeping it by running whatsapp in foreground. Saw your issue. Will reply if am able to do by code.

**Comment by hiwaleakshay** [comment]
By the way what do you mean by after 10 mins?
If you have started a chat with that contact then simply 
`wac.SubscribePresence("wa_number@c.us")`
will update the presence in jsonHandler. As far as internet connection on your mobile is on you will recv the presence update. I am receiving it. Only condition is you have to initiate a chat with that contact and as soon as go-whatsapp logs you in you have to subscribe for the presence.

**Comment by theflyingmantis** [comment]
Yeah. My bad. My phone use to sleep after 10 minutes. Also from this - https://github.com/Rhymen/go-whatsapp/issues/23#issuecomment-417444421 , I took 10 min deadline. But experimenting now - it works. There is no 10 min limit. The only condition being your whatsapp mobile app be kept online. 
Also is there any way to get the presence for numbers with which we haven't started a chat. @hiwaleakshay

**Comment by theflyingmantis** [comment]
@hiwaleakshay After about 10 minutes of inactivity (with mobile kept online), whatsapp resets the connection and you have to subscribe for presence again. Read this.
https://github.com/Rhymen/go-whatsapp/issues/23#issuecomment-417444421

**Comment by hiwaleakshay** [comment]
@theflyingmantis I dont have any issue in subscribing presence again after 10 mins. My issue is can we subscribe presence for the contacts with whom we have not initiated a chat. 
Or even after subscribing presence for that contact we have to go manually to their chat screen on mobile and then we start getting presence updates that too for 10 to 15 mins only. Any workaround for this?

**Comment by theflyingmantis** [comment]
You can't subscribe presence if you haven't initiated the chat with the user. Yes, you have to manually go to the mobile and click again as far as I know. Maybe you can write a script in android to automate it. As of 1st May 2018, thats the only thing as whatsapp does not allow presence stalking. Let me know if you get a side around. Could mail me on abhinav.rai.1996@gmail.com. Lets share the findings.

**Comment by hiwaleakshay** [comment]
@theflyingmantis agree. But there must be some way to do this in go. What other data with presence subscribe did whatsapp send when we manually click on the contact? I tried web.whatsapp/ws in debug mode and analyzed the json's. Could't find anything except presence subscribe.

**Comment by un000** [comment]
You just should wait like 10 seconds after login and subscribe.
It works to me.
