### ISSUE TITLE
How to renew info

### ISSUE THREAD

**Issue by tgssb** [Rhymen/go-whatsapp#82]
How to renew device informations without disconnect ?
`
wac.Info = newInfoFromReq(info)
`

**Comment by Rhymen** [comment]
This is not possible yet, but it should be. WhatsApp Web shows low battery hints so the Info must be updated somehow. I don't know if we can retrieve the new Info or if we have to wait for it to be send again. This needs more testing.

**Comment by tgssb** [comment]
I modify a temporary adjustment in my code.
I created a logout / login loop every 30 minutes, so I refresh the information. The only problem is that when the device is offline (no internet). I try reconnections in a short period of time, but if the device stays too long, it loses the session and when it comes back I need to renew the qr code. Do you have any suggestions?

**Comment by gabstv** [comment]
> I created a logout / login loop every 30 minutes, so I refresh the information. The only problem is that when the device is offline (no internet). I try reconnections in a short period of time, but if the device stays too long, it loses the session and when it comes back I need to renew the QR code. Do you have any suggestions?

I don't think that this is an issue when the device is offline, since the WhatsApp web API only works if the device is connected since it's only a bridge between your API and your device (the device receives/sends the messages and then broadcasts it to the latest we.whats session.

Unfortunately the whatsapp-web-reveng project also didn't figure out how to renew the device info (without dropping and restoring the session).

**Comment by ahmadyusri** [comment]
> Hello
> I am renewing the information by disconnecting and connecting again.
> 
> But it is not 100% stable, when the device is missing from the internet, it can not reconnect, so I loop the attempts ..
> 
> To restore, the device can not be missing too long
> 
> When the device is gone for a long time offline, and it gets internet connection again, the session does not restore. I am required to generate a new qr
> 
> ```
> session, err := wac.Disconnect()
> session, err = wac.RestoreWithSession(session)
> ```
> 
> Can you help me with some improvement?

Is there a solution for updating info without reconnection?

**Comment by victormedranop** [comment]
I have the same problem. happened twice a week.
