### ISSUE TITLE
How to send message to many number ?

### ISSUE THREAD

**Issue by roggerlie** [Rhymen/go-whatsapp#83]
sorry im new in go lang, please how to send message to many number ?
the number from my database like array or json format

**Comment by Rhymen** [comment]
Hello @roggerlie ,

as this is no problem concerning the go-whatsapp package I'm going to close this issue. For general questions I suggest you ask the folks over at [stackoverflow](https://stackoverflow.com). If you want to learn golang I highly advice you to do [A Tour Of Go](https://tour.golang.com/welcome/1).

Maybe this helps you along the way.
```
	jids := []string{"num1@s.whatsapp.net", "num2@s.whatsapp.net"}
	text := "Message sent by github.com/Rhymen/go-whatsapp"

	for _, jid := range jids {
		msg := whatsapp.TextMessage{
			Info: whatsapp.MessageInfo{
				RemoteJid: jid,
			},
			Text: text,
		}

		wac.Send(msg)
	}
```

**Comment by roggerlie** [comment]
thank you rhymen
