### ISSUE TITLE
get phone is connected

### ISSUE THREAD

**Issue by tgssb** [Rhymen/go-whatsapp#85]
How to know if your phone is connected to the internet without reconnecting ?

**Comment by Rhymen** [comment]
Hello @tgssb 

I'm not sure if this is possible atm If you connect to the WhatsApp Web client and disconnect your mobile phone from the internet no hint is shown whatsoever. I inspected the websocket as well and couldn't find any messages indicating a network change.

**Comment by tgssb** [comment]
Yes I was checking the documentation of the web-reveng and did not find something that could solve. I am closing this question. Thank you, I am gaining new opportunities thanks to your repository. Good job..

**Comment by houstondapaz** [comment]
After an time inactive (don't receive or send message) the whatsapp web starts to send "ping" to the server, imagine this is to verify phone connectivity.

Anyone has ideia how to implement this? @kaxap @SchulteMK 

![image](https://user-images.githubusercontent.com/1082511/61719264-fc0e1300-ad3a-11e9-8c22-dc2ed6662983.png)
