### ISSUE TITLE
message.Info.SenderJid is nil when message.Info.Source.Participant is not

### ISSUE THREAD

**Issue by coolnickname** [Rhymen/go-whatsapp#86]
`message.Info.Source.GetKey().Participant` is nil, so `message.Info.SenderJid` is too.

`message.Info.RemoteJid` is the group JID, not the sender's.

**Comment by KrzysztofMadejski** [comment]
Hi @Rhymen , I have the same case, message is sent in a group, senderJid is empty. It can be retrieved from deeper structure as you suggested.

Why not fill it out? I see others are doing similar workarounds: https://github.com/tulir/mautrix-whatsapp/blob/513eb18e2d59bada0dd515ee1abaaf38a3bfe3d5/portal.go#L529-L533

**Comment by KrzysztofMadejski** [comment]
Maybe an `||` would suffice here: https://github.com/Rhymen/go-whatsapp/blob/0704a4ae717bf66e724682f32053ac7b6e4fcca0/message.go#L129

**Comment by coolnickname** [comment]
> Hello @coolnickname ,
> 
> I just tried and I think `message.Info.Source.GetParticipant()` should work.

Can confirm this solved it, sorry for the long wait. 

I'm leaving this issue open for now as a reminder to do some fix for message.Info.SenderJid like the one @KrzysztofMadejski suggested.

**Comment by Lucipher** [comment]
Can not get SenderJid when use HandleTextMessage handler
message.Info.Source.GetKey().Participant is nil,  so message.Info.SenderJid is too.
message.Info.Source.GetParticipant()  not work too.

**Comment by KrzysztofMadejski** [comment]
@Lucipher how does your message looks like on WhatsApp? Send a screenshot. Please check also `message.Info.Source.Participant`

**Comment by Lucipher** [comment]
@KrzysztofMadejski 
![image](https://user-images.githubusercontent.com/1323545/53682296-3b59aa00-3d2f-11e9-85d8-797194bfbc5f.png)


![image](https://user-images.githubusercontent.com/1323545/53682284-0cdbcf00-3d2f-11e9-9574-c8b3cfa685de.png)

**Comment by coolnickname** [comment]
Are you sure the message is sent from a group? If it's from a private chat it's always nil.

**Comment by Lucipher** [comment]
@coolnickname 
Thanks, IC

**Comment by KrzysztofMadejski** [comment]
- [ ] It would be good if it was set also in private chats.

**Comment by Lucipher** [comment]
@KrzysztofMadejski @SchulteMK 
Is there any way to get sender phone in private chats?

**Comment by RynKings** [comment]
hmm anyone have fix this on private chat ?

**Comment by adarshsrivastava11** [comment]
Hi what is the current status on this issue?
