### ISSUE TITLE
Message timed out

### ISSUE THREAD

**Issue by lutpiero** [Rhymen/go-whatsapp#9]
I try this go-whatsapp, its always showing message timed out.

Althought sometimes the message delivered.
I've tried both on linux (centos 7) and windows, in average the connection timeout always occured.

When I'm increasing 5 to 50 
wac, err := whatsapp.newConn(5 * time.Second)

The timeout error gone, but the sending process are too slow.

**Comment by Rhymen** [comment]
This seems to be a problem with your local internet connection. Try a faster and more stable connection please. Not only your computer, but your phone needs a good connection as well.

**Comment by lutpiero** [comment]
My Internet connection 27Mbps, Phone and Computer using the same network. 
I dont think its internet connection speed related problems. 
For the first run (login) the qrcode showing fast, but when sending text message it's too slow.

**Comment by lutpiero** [comment]
Okay I got it, so its the whole process that tooks so long, sending message is quick.
I'm closing this issue.
