### ISSUE TITLE
Invalid hmac on mp3

### ISSUE THREAD

**Issue by highness28** [Rhymen/go-whatsapp#92]
Whenever the package receives a document message from the `HandleDocumentMessage` method `(message.Download() function)` with a file extension of .mp3 an error is always occuring that I'm using an invalid hmac

here is the line where i catches the error on `media.go`
```
if !hmac.Equal(h.Sum(nil)[:10], mac) {
	return fmt.Errorf("invalid media hmac")
}
```

**Comment by SchulteMK** [comment]
For me mp3 files are received through the `AudioMessageHandler` with its method `HandleAudioMessage`. How were these files sent? Through go-whatsapp or through the regular WhatsApp app?
