### ISSUE TITLE
Always stay online?

### ISSUE THREAD

**Issue by hiwaleakshay** [Rhymen/go-whatsapp#94]
I tried the example echo message.
But it wont keep my number online. Any idea how to do that.
I mean i keep whatsapp open on my mobile after scanning qr code. Messages are echoed. but after some time the account shows offline. but still echo the message. How can i keep the account remain online always. Than you.

**Comment by theflyingmantis** [comment]
Were you able to achieve it? Post the closing arguments also :)

**Comment by hiwaleakshay** [comment]
`wac.Presence(WA_NUM+"@c.us", "available")`

set this when you do login. But it works from 10 to 15 min only. Then again offline.
