### ISSUE TITLE
Get real id registered in WhatsApp.

### ISSUE THREAD

**Issue by Romerito007** [Rhymen/go-whatsapp#95]
Is there a way to get the WhatsApp id real?

The reason for my question is that in Brazil we have recently added a 9 in all cell numbers, and when I check the two numbers, WhatsApp says everything is fine. But I need to send the message only to the real id.
Number without digit 9 - 55448439-9886 Returns status 200, Number with digit 9 - 554498439-9886 Returns status 200.

Ship to 55448439-9886 sending successfully.
Send to 554498439-9886 not sent.

Function used Exist(jid string) with @ s.whatsapp.net, @c.us

**Comment by kaxap** [comment]
> Ship to 55448439-9886 sending successfully.
> Send to 554498439-9886 not sent.

Sorry, the numbers are the same, aren't they?

**Comment by Romerito007** [comment]
yes, but when sent with the digit 9 it does not send, but some numbers in Brazil were registered in WhatsApp with digit 9. I'm sorry, my English
![Attachment Example](https://user-images.githubusercontent.com/13719169/52537938-9cefaf80-2d53-11e9-8a91-64a72696e227.jpeg)

**Comment by kaxap** [comment]
Oh, I see.

I guess those are totally different numbers from the client's perspective. Thus, such numbers should be handled server side.

Many countries have different phone number formats, e.g. in United Kingdom there are at least two possible number formats: 

1) international, starting with +4400
2) national mobile numbers, starting with 07

But they resolve to the same ID by whatsapp servers.

Most probably WhatsApp will fix your issue soon.

**Comment by Romerito007** [comment]
Thank you for your help.
