### ISSUE TITLE
Feature request: Public invite link

### ISSUE THREAD

**Issue by KrzysztofMadejski** [Rhymen/go-whatsapp#97]
It would be great to obtain a public invite link for a group.

**Comment by SchulteMK** [comment]
It should be pretty straigt forward I think. If I've got time I will implement it tomorrow.

Quick notes:

Query:
621.--137,,["query","inviteCode","491xxxxxx-1550606659@g.us"]

Answer:
621.--137,{status: 200, code: "KyvTtKp6ixxxxx"}

Resulting invite link:
https://chat.whatsapp.com/KyvTtKp6ixxxxx

**Comment by SchulteMK** [comment]
Sorry for beeing late. But better late than never :)
